import {
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  Mail,
  MailOpen,
  Send,
  MessageSquare,
  MessageCircle,
  Video,
  Calendar,
  CalendarCheck,
  Clock,
  Users,
  UserPlus,
  Handshake,
  FileText,
  FileSignature,
  ClipboardList,
  CheckCircle2,
  AlertCircle,
  Star,
  Flag,
  Target,
  TrendingUp,
  DollarSign,
  Gift,
  Coffee,
  MapPin,
  Briefcase,
  type LucideIcon,
} from "lucide-react";

export const ACTIVITY_ICON_REGISTRY: Record<string, LucideIcon> = {
  phone: Phone,
  "phone-call": PhoneCall,
  "phone-incoming": PhoneIncoming,
  "phone-outgoing": PhoneOutgoing,
  "phone-missed": PhoneMissed,
  mail: Mail,
  "mail-open": MailOpen,
  send: Send,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  video: Video,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  clock: Clock,
  users: Users,
  "user-plus": UserPlus,
  handshake: Handshake,
  "file-text": FileText,
  "file-signature": FileSignature,
  "clipboard-list": ClipboardList,
  "check-circle": CheckCircle2,
  "alert-circle": AlertCircle,
  star: Star,
  flag: Flag,
  target: Target,
  "trending-up": TrendingUp,
  "dollar-sign": DollarSign,
  gift: Gift,
  coffee: Coffee,
  "map-pin": MapPin,
  briefcase: Briefcase,
};

export const ACTIVITY_ICON_NAMES = Object.keys(ACTIVITY_ICON_REGISTRY);

export function getActivityIcon(name: string): LucideIcon | undefined {
  return ACTIVITY_ICON_REGISTRY[name];
}
