import { MutationCtx } from "../../_generated/server";
import { internal } from "../../_generated/api";
import { Id } from "../../_generated/dataModel";
import { resolveScope } from "../../documents/scopeResolver";

/**
 * Auto-generate formDocuments for an appointment based on its treatment's
 * requiredFormTemplates configuration.
 *
 * Called after an appointment is created. For each required template:
 * 1. Resolves scope data (patient, employee, treatment, appointment, org)
 * 2. Creates a formDocument with pre-filled data
 * 3. If the template requires a signature, schedules a signing email
 */
export async function autoGenerateAppointmentDocuments(
  ctx: MutationCtx,
  args: {
    organizationId: Id<"organizations">;
    appointmentId: Id<"gabinetAppointments">;
    treatmentId: Id<"gabinetTreatments">;
    patientId: Id<"gabinetPatients">;
    createdBy: Id<"users">;
  },
): Promise<Id<"formDocuments">[]> {
  const treatment = await ctx.db.get(args.treatmentId);
  if (!treatment) return [];

  const requiredTemplates = treatment.requiredFormTemplates ?? [];
  if (requiredTemplates.length === 0) return [];

  // Resolve scope data once for all templates (appointment context)
  const scopeData = await resolveScope(
    ctx,
    args.organizationId,
    "appointment",
    args.appointmentId as string,
  );

  // Flatten scope to dot-notation for responseData pre-fill
  const prefilledData: Record<string, string> = {};
  for (const [entityType, fields] of Object.entries(scopeData)) {
    if (typeof fields !== "object" || fields === null) continue;
    for (const [key, value] of Object.entries(
      fields as Record<string, unknown>,
    )) {
      if (value !== null && value !== undefined) {
        prefilledData[`${entityType}.${key}`] = String(value);
      }
    }
  }

  const now = Date.now();
  const createdDocIds: Id<"formDocuments">[] = [];

  for (const entry of requiredTemplates) {
    const template = await ctx.db.get(entry.templateId);
    if (!template || !template.isActive) continue;

    // Determine initial status based on signature requirement
    const status = template.requiresSignature
      ? ("pending_signature" as const)
      : ("draft" as const);

    // Generate signing token if signature is needed
    let signingToken: string | undefined;
    let signingTokenExpiresAt: number | undefined;
    if (template.requiresSignature) {
      signingToken = crypto.randomUUID();
      signingTokenExpiresAt = now + 48 * 60 * 60 * 1000; // 48 hours
    }

    const docId = await ctx.db.insert("formDocuments", {
      organizationId: args.organizationId,
      templateId: entry.templateId,
      title: template.name,
      responseData: JSON.stringify(prefilledData),
      entityType: "appointment",
      entityId: args.appointmentId as string,
      scopeEntities: JSON.stringify({
        patient: args.patientId,
        treatment: args.treatmentId,
      }),
      status,
      timing: entry.timing,
      autoGenerated: true,
      signingToken,
      signingTokenExpiresAt,
      createdBy: args.createdBy,
      createdAt: now,
      updatedAt: now,
    });

    createdDocIds.push(docId);

    // If signature required, send signing email to patient
    if (template.requiresSignature && signingToken) {
      const patient = await ctx.db.get(args.patientId);
      if (patient?.email) {
        const patientName = `${patient.firstName}${patient.lastName ? " " + patient.lastName : ""}`;
        await ctx.scheduler.runAfter(
          0,
          internal.documents.signing.sendSigningEmailInternal,
          {
            documentId: docId,
            recipientEmail: patient.email,
            recipientName: patientName,
          },
        );
      }
    }
  }

  return createdDocIds;
}
