import { QueryCtx } from "../../_generated/server";
import { Id } from "../../_generated/dataModel";

export type DocumentGateResult = {
  canProceed: boolean;
  missing: Array<{
    title: string;
    documentId: Id<"formDocuments">;
    status: string;
  }>;
  total: number;
  completed: number;
};

/**
 * Check whether all auto-generated documents for a given appointment and timing
 * gate have been completed/signed. Used to gate appointment status transitions.
 *
 * - "before_start" gate: checked when transitioning to in_progress
 * - "after_completion" gate: checked when transitioning to completed
 */
export async function checkDocumentGate(
  ctx: QueryCtx,
  appointmentId: Id<"gabinetAppointments">,
  timing: "before_start" | "after_completion",
): Promise<DocumentGateResult> {
  // Query formDocuments linked to this appointment
  const docs = await ctx.db
    .query("formDocuments")
    .withIndex("by_entity", (q) =>
      q.eq("entityType", "appointment").eq("entityId", appointmentId as string),
    )
    .collect();

  // Filter to auto-generated docs matching the requested timing
  const relevantDocs = docs.filter(
    (d) => d.timing === timing && d.autoGenerated === true,
  );

  // A document is "done" if it is signed or completed
  const missing = relevantDocs.filter(
    (d) => d.status !== "signed" && d.status !== "completed",
  );

  return {
    canProceed: missing.length === 0,
    missing: missing.map((d) => ({
      title: d.title,
      documentId: d._id,
      status: d.status,
    })),
    total: relevantDocs.length,
    completed: relevantDocs.length - missing.length,
  };
}
