import { Id } from "../../_generated/dataModel";
import { createSupabaseDb } from "../../_helpers/supabaseDb";

export type DocumentGateResult = {
  canProceed: boolean;
  missing: Array<{
    title: string;
    documentId: Id<"formDocuments">;
    status: string;
  }>;
  total: number;
  completed: number;
};

/**
 * Check whether all auto-generated documents for a given appointment and timing
 * gate have been completed/signed. Used to gate appointment status transitions.
 *
 * - "before_start" gate: checked when transitioning to in_progress
 * - "during_visit" gate: checked when transitioning to completed
 * - "after_completion" docs are generated AT completion (no gate)
 */
export async function checkDocumentGate(
  appointmentId: Id<"gabinetAppointments">,
  timing: "before_start" | "during_visit" | "after_completion",
): Promise<DocumentGateResult> {
  const supabaseDb = createSupabaseDb();

  // Query form_documents from Supabase (all writes go there via autoGenerateDocuments.ts)
  const relevantDocs = await supabaseDb
    .query("formDocuments")
    .eq("entityType", "appointment")
    .eq("entityId", appointmentId as string)
    .eq("timing", timing)
    .eq("autoGenerated", true)
    .collect();

  // A document is "done" if it is signed, completed, or voided (voided docs are no longer applicable).
  // Only required documents (isRequired !== false) block the gate; optional docs are excluded.
  // NULL is treated as required for backward compatibility with pre-migration rows.
  const missing = relevantDocs.filter(
    (d) =>
      (d.isRequired as boolean | null | undefined) !== false &&
      d.status !== "signed" &&
      d.status !== "completed" &&
      d.status !== "voided",
  );

  return {
    canProceed: missing.length === 0,
    missing: missing.map((d) => ({
      title: d.title as string,
      documentId: d._id as Id<"formDocuments">,
      status: d.status as string,
    })),
    total: relevantDocs.length,
    completed: relevantDocs.length - missing.length,
  };
}

// ---------------------------------------------------------------------------
// D28 — Per-appointment document completeness
// ---------------------------------------------------------------------------

export type AppointmentDocumentStatus =
  | "satisfied"       // signed/completed and within validity period
  | "expired"         // signed but expiresAt has passed
  | "pending"         // exists but not yet completed (draft/pending_signature)
  | "missing"         // no document found, required by rule
  | "not_applicable"; // frequency rule means this doc is not needed for this visit

export type AppointmentDocumentItem = {
  templateId: string;
  title: string;
  timing: "before_start" | "during_visit" | "after_completion" | null;
  isRequired: boolean;
  frequency: "once" | "first_visit_only" | "before_each_visit" | "every_n_days" | "on_expiry";
  validityDays: number | null;
  status: AppointmentDocumentStatus;
  /** True when isRequired and the document is missing, expired, or only pending. */
  blocksCompletion: boolean;
  document: {
    documentId: string;
    status: string;
    signedAt: number | null;
    expiresAt: number | null;
  } | null;
};

export type AppointmentDocumentCompleteness = {
  /** True when no required document is missing, expired, or pending. */
  isComplete: boolean;
  items: AppointmentDocumentItem[];
  summary: {
    total: number;
    satisfied: number;
    expired: number;
    pending: number;
    missing: number;
    notApplicable: number;
    /** Count of items where blocksCompletion is true. */
    blocking: number;
  };
};

function emptyCompleteness(): AppointmentDocumentCompleteness {
  return {
    isComplete: true,
    items: [],
    summary: {
      total: 0,
      satisfied: 0,
      expired: 0,
      pending: 0,
      missing: 0,
      notApplicable: 0,
      blocking: 0,
    },
  };
}

/**
 * Compute the documentation completeness for a specific appointment.
 *
 * For each document template required by the appointment's treatment (and any
 * org-level required templates), determines whether the document has been
 * satisfied, is pending, is missing, has expired, or is not applicable to
 * this visit based on the frequency rule.
 *
 * Handles all D27 frequency variants:
 *   - once              — satisfied by any prior signed copy across patient appointments
 *   - first_visit_only  — not_applicable on second+ visits for the same treatment
 *   - before_each_visit — must exist for this specific appointment
 *   - every_n_days      — satisfied while a signed copy is within its validity window
 *   - on_expiry         — same as every_n_days but driven by explicit expiresAt
 */
export async function getAppointmentDocumentCompleteness(
  appointmentId: Id<"gabinetAppointments">,
): Promise<AppointmentDocumentCompleteness> {
  const supabaseDb = createSupabaseDb();
  const now = Date.now();

  // 1. Load the appointment
  const appointment = await supabaseDb.get("gabinetAppointments", String(appointmentId));
  if (!appointment) return emptyCompleteness();

  const orgId = String(appointment.organizationId);
  const patientId = String(appointment.patientId);
  const treatmentId = appointment.treatmentId ? String(appointment.treatmentId) : null;

  // 2. Load treatment's required templates
  type TemplateEntry = {
    templateId: string;
    timing?: "before_start" | "during_visit" | "after_completion";
    isRequired?: boolean;
    frequency?: "once" | "first_visit_only" | "before_each_visit" | "every_n_days" | "on_expiry";
    validityDays?: number;
    isOneTime?: boolean;
  };

  let requiredTemplates: TemplateEntry[] = [];
  if (treatmentId) {
    const treatment = await supabaseDb.get("gabinetTreatments", treatmentId);
    if (treatment) {
      requiredTemplates = (treatment.requiredFormTemplates as TemplateEntry[] | undefined) ?? [];
    }
  }

  // 3. Merge org-level required templates (same logic as autoGenerateDocuments)
  const orgRequiredRows = await supabaseDb
    .query("formTemplates")
    .eq("organizationId", orgId)
    .eq("isOrgRequired", true)
    .eq("isActive", true)
    .collect();

  if (orgRequiredRows.length > 0) {
    const treatmentTemplateIds = new Set(requiredTemplates.map((t) => t.templateId));
    for (const row of orgRequiredRows) {
      const id = String(row._id);
      if (!treatmentTemplateIds.has(id)) {
        requiredTemplates = [
          ...requiredTemplates,
          { templateId: id, timing: "before_start", frequency: "once", isOneTime: true },
        ];
      }
    }
  }

  if (requiredTemplates.length === 0) return emptyCompleteness();

  // 4. Load all formDocuments for this appointment in one query
  const appointmentDocs = await supabaseDb
    .query("formDocuments")
    .eq("entityType", "appointment")
    .eq("entityId", String(appointmentId))
    .collect();

  const appointmentDocByTemplateId = new Map(
    appointmentDocs.map((d) => [String(d.templateId), d as Record<string, unknown>]),
  );

  // 5. Patient appointment IDs — loaded lazily for cross-appointment lookups
  let cachedPatientApptIds: string[] | null = null;
  async function getPatientApptIds(): Promise<string[]> {
    if (cachedPatientApptIds !== null) return cachedPatientApptIds;
    const appts = await supabaseDb
      .query("gabinetAppointments")
      .eq("patientId", patientId)
      .eq("organizationId", orgId)
      .collect();
    cachedPatientApptIds = appts.map((a) => String(a._id));
    return cachedPatientApptIds;
  }

  // 6. Resolve per-template status
  const items: AppointmentDocumentItem[] = [];

  for (const entry of requiredTemplates) {
    const effectiveFrequency: AppointmentDocumentItem["frequency"] =
      entry.frequency ?? (entry.isOneTime ? "once" : "before_each_visit");
    const isRequired = entry.isRequired !== false; // null treated as required (backward compat)
    const validityDays = entry.validityDays ?? null;

    // Resolve template title (used when no formDocument exists for this appointment)
    let templateTitle = entry.templateId;
    const template = await supabaseDb.get("formTemplates", entry.templateId);
    if (template) templateTitle = String(template.name);

    const apptDoc = appointmentDocByTemplateId.get(entry.templateId) ?? null;

    let resolvedStatus: AppointmentDocumentStatus;
    let resolvedDoc: AppointmentDocumentItem["document"] = null;

    if (apptDoc && String(apptDoc.status) !== "voided") {
      // A non-voided document was generated for this appointment
      const docStatus = String(apptDoc.status);
      const signedAt = (apptDoc.signedAt as number | null | undefined) ?? null;
      const expiresAt = (apptDoc.expiresAt as number | null | undefined) ?? null;

      resolvedDoc = {
        documentId: String(apptDoc._id),
        status: docStatus,
        signedAt,
        expiresAt,
      };

      if (docStatus === "signed" || docStatus === "completed") {
        resolvedStatus = expiresAt !== null && expiresAt < now ? "expired" : "satisfied";
      } else {
        // draft or pending_signature
        resolvedStatus = "pending";
      }
    } else {
      // No (useful) document for this appointment — resolve via frequency rule
      if (effectiveFrequency === "first_visit_only") {
        if (treatmentId) {
          const prior = await supabaseDb
            .query("gabinetAppointments")
            .eq("patientId", patientId)
            .eq("organizationId", orgId)
            .eq("treatmentId", treatmentId)
            .in("status", ["completed"])
            .collect();
          const priorCount = prior.filter((a) => String(a._id) !== String(appointmentId)).length;
          resolvedStatus = priorCount > 0 ? "not_applicable" : "missing";
        } else {
          resolvedStatus = "missing";
        }
      } else if (effectiveFrequency === "once") {
        const apptIds = await getPatientApptIds();
        if (apptIds.length > 0) {
          const priorSigned = await supabaseDb
            .query("formDocuments")
            .eq("templateId", entry.templateId)
            .eq("organizationId", orgId)
            .eq("entityType", "appointment")
            .in("status", ["signed", "completed"])
            .in("entityId", apptIds)
            .first() as Record<string, unknown> | null;
          if (priorSigned) {
            resolvedStatus = "satisfied";
            resolvedDoc = {
              documentId: String(priorSigned._id),
              status: String(priorSigned.status),
              signedAt: (priorSigned.signedAt as number | null | undefined) ?? null,
              expiresAt: (priorSigned.expiresAt as number | null | undefined) ?? null,
            };
          } else {
            resolvedStatus = "missing";
          }
        } else {
          resolvedStatus = "missing";
        }
      } else if (effectiveFrequency === "every_n_days" || effectiveFrequency === "on_expiry") {
        const apptIds = await getPatientApptIds();
        if (apptIds.length > 0) {
          const priorSigned = await supabaseDb
            .query("formDocuments")
            .eq("templateId", entry.templateId)
            .eq("organizationId", orgId)
            .eq("entityType", "appointment")
            .in("status", ["signed", "completed"])
            .in("entityId", apptIds)
            .first() as Record<string, unknown> | null;
          if (priorSigned) {
            const signedAt = (priorSigned.signedAt as number | null | undefined) ?? null;
            const expiresAt = (priorSigned.expiresAt as number | null | undefined) ?? null;
            const validityMs = (validityDays ?? 0) * 24 * 60 * 60 * 1000;
            const effectiveExpiry =
              expiresAt ?? (signedAt != null && validityMs > 0 ? signedAt + validityMs : null);
            resolvedDoc = {
              documentId: String(priorSigned._id),
              status: String(priorSigned.status),
              signedAt,
              expiresAt: effectiveExpiry ?? null,
            };
            resolvedStatus =
              effectiveExpiry !== null && effectiveExpiry < now ? "expired" : "satisfied";
          } else {
            resolvedStatus = "missing";
          }
        } else {
          resolvedStatus = "missing";
        }
      } else {
        // before_each_visit — must be generated for this specific appointment
        resolvedStatus = "missing";
      }
    }

    const blocksCompletion =
      isRequired &&
      (resolvedStatus === "missing" ||
        resolvedStatus === "expired" ||
        resolvedStatus === "pending");

    items.push({
      templateId: entry.templateId,
      title: apptDoc ? String(apptDoc.title ?? templateTitle) : templateTitle,
      timing: (entry.timing ?? null) as AppointmentDocumentItem["timing"],
      isRequired,
      frequency: effectiveFrequency,
      validityDays,
      status: resolvedStatus,
      blocksCompletion,
      document: resolvedDoc,
    });
  }

  // 7. Aggregate summary
  const summary = {
    total: items.length,
    satisfied: items.filter((i) => i.status === "satisfied").length,
    expired: items.filter((i) => i.status === "expired").length,
    pending: items.filter((i) => i.status === "pending").length,
    missing: items.filter((i) => i.status === "missing").length,
    notApplicable: items.filter((i) => i.status === "not_applicable").length,
    blocking: items.filter((i) => i.blocksCompletion).length,
  };

  return {
    isComplete: summary.blocking === 0,
    items,
    summary,
  };
}
