/**
 * Gabinet Treatment Packages Mapper — Supabase ↔ Frontend
 *
 * The `treatments` column is JSONB in PostgreSQL and returns `unknown`
 * from Supabase. We type it as an array of treatment config objects.
 */

import type { GabinetTreatmentPackageRow } from "../../database.types";
import { createEntityMapper } from "../generic";

/** Shape of a single treatment entry inside the JSONB treatments array. */
export interface PackageTreatmentEntry {
  treatmentId: string;
  variantId?: string;
  quantity: number;
  name?: string;
}

export interface MappedGabinetTreatmentPackage {
  _id: string;
  _creationTime: number;
  organizationId: string;
  name: string;
  description?: string;
  treatments: PackageTreatmentEntry[];
  totalPrice: number;
  currency?: string;
  discountPercent?: number;
  validityDays?: number;
  isActive: boolean;
  loyaltyPointsAwarded?: number;
  autoGeneratedForTreatmentId?: string;
  createdBy: string;
  createdAt: number;
  updatedAt: number;
  _source: "supabase";
}

const mapper = createEntityMapper<
  GabinetTreatmentPackageRow,
  MappedGabinetTreatmentPackage
>({});

/** Map from Supabase, casting the JSONB `treatments` column to its typed array. */
export function mapGabinetTreatmentPackageFromSupabase(
  row: GabinetTreatmentPackageRow,
): MappedGabinetTreatmentPackage {
  const base = mapper.mapFromSupabase(row);
  return {
    ...base,
    _creationTime: base.createdAt,
    treatments: (row.treatments ?? []) as PackageTreatmentEntry[],
  };
}

export const mapGabinetTreatmentPackageToSupabase = mapper.mapToSupabase;
