/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _helpers_activities from "../_helpers/activities.js";
import type * as _helpers_activityEnvelope from "../_helpers/activityEnvelope.js";
import type * as _helpers_auth from "../_helpers/auth.js";
import type * as _helpers_authAction from "../_helpers/authAction.js";
import type * as _helpers_gabinetRolePermissions from "../_helpers/gabinetRolePermissions.js";
import type * as _helpers_html from "../_helpers/html.js";
import type * as _helpers_logged from "../_helpers/logged.js";
import type * as _helpers_permissionTypes from "../_helpers/permissionTypes.js";
import type * as _helpers_permissions from "../_helpers/permissions.js";
import type * as _helpers_portalSession from "../_helpers/portalSession.js";
import type * as _helpers_products from "../_helpers/products.js";
import type * as _helpers_seatLimits from "../_helpers/seatLimits.js";
import type * as _helpers_supabaseDb from "../_helpers/supabaseDb.js";
import type * as _helpers_supabaseRows from "../_helpers/supabaseRows.js";
import type * as _test from "../_test.js";
import type * as _test_helpers from "../_test_helpers.js";
import type * as activities from "../activities.js";
import type * as activityTypes from "../activityTypes.js";
import type * as app from "../app.js";
import type * as auditLog from "../auditLog.js";
import type * as auth from "../auth.js";
import type * as automation from "../automation.js";
import type * as automationRegistry from "../automationRegistry.js";
import type * as calls from "../calls.js";
import type * as categoryDefinitions from "../categoryDefinitions.js";
import type * as companies from "../companies.js";
import type * as contacts from "../contacts.js";
import type * as crm__registry from "../crm/_registry.js";
import type * as crm_documentDataSources from "../crm/documentDataSources.js";
import type * as crm_seed from "../crm/seed.js";
import type * as crons from "../crons.js";
import type * as csvExport from "../csvExport.js";
import type * as csvImport from "../csvImport.js";
import type * as customFields from "../customFields.js";
import type * as dashboard from "../dashboard.js";
import type * as dev_emails from "../dev/emails.js";
import type * as dev_helpers from "../dev/helpers.js";
import type * as documentDataSources from "../documentDataSources.js";
import type * as documentInstances from "../documentInstances.js";
import type * as documentTemplateFields from "../documentTemplateFields.js";
import type * as documentTemplates from "../documentTemplates.js";
import type * as documents from "../documents.js";
import type * as documents_completeMissingData from "../documents/completeMissingData.js";
import type * as documents_components from "../documents/components.js";
import type * as documents_documents from "../documents/documents.js";
import type * as documents_generate from "../documents/generate.js";
import type * as documents_resolveComponents from "../documents/resolveComponents.js";
import type * as documents_scopeResolver from "../documents/scopeResolver.js";
import type * as documents_scopeResolver_supabase from "../documents/scopeResolver_supabase.js";
import type * as documents_seed from "../documents/seed.js";
import type * as documents_signing from "../documents/signing.js";
import type * as documents_templates from "../documents/templates.js";
import type * as email_index from "../email/index.js";
import type * as email_providers from "../email/providers.js";
import type * as email_templates_invitationEmail from "../email/templates/invitationEmail.js";
import type * as email_templates_subscriptionEmail from "../email/templates/subscriptionEmail.js";
import type * as emailAccounts from "../emailAccounts.js";
import type * as emailBrandConfig from "../emailBrandConfig.js";
import type * as emailEventBindings from "../emailEventBindings.js";
import type * as emailEventTrigger from "../emailEventTrigger.js";
import type * as emailEvents from "../emailEvents.js";
import type * as emailLayouts from "../emailLayouts.js";
import type * as emailSending from "../emailSending.js";
import type * as emailSequences from "../emailSequences.js";
import type * as emailTemplateSeed from "../emailTemplateSeed.js";
import type * as emailTemplates from "../emailTemplates.js";
import type * as emails from "../emails.js";
import type * as emails_internal from "../emails_internal.js";
import type * as env from "../env.js";
import type * as errorLogs from "../errorLogs.js";
import type * as gabinet__availability from "../gabinet/_availability.js";
import type * as gabinet__availability_supabase from "../gabinet/_availability_supabase.js";
import type * as gabinet__e2eTest from "../gabinet/_e2eTest.js";
import type * as gabinet__helpers_autoGenerateDocuments from "../gabinet/_helpers/autoGenerateDocuments.js";
import type * as gabinet__helpers_documentGate from "../gabinet/_helpers/documentGate.js";
import type * as gabinet__registry from "../gabinet/_registry.js";
import type * as gabinet_appointmentReminders from "../gabinet/appointmentReminders.js";
import type * as gabinet_appointmentSms from "../gabinet/appointmentSms.js";
import type * as gabinet_appointmentWorkflow from "../gabinet/appointmentWorkflow.js";
import type * as gabinet_appointments from "../gabinet/appointments.js";
import type * as gabinet_documentDataSources from "../gabinet/documentDataSources.js";
import type * as gabinet_employees from "../gabinet/employees.js";
import type * as gabinet_equipment from "../gabinet/equipment.js";
import type * as gabinet_leaveTypes from "../gabinet/leaveTypes.js";
import type * as gabinet_locations from "../gabinet/locations.js";
import type * as gabinet_loyalty from "../gabinet/loyalty.js";
import type * as gabinet_nudges from "../gabinet/nudges.js";
import type * as gabinet_onboarding from "../gabinet/onboarding.js";
import type * as gabinet_packages from "../gabinet/packages.js";
import type * as gabinet_patientAuth from "../gabinet/patientAuth.js";
import type * as gabinet_patientPortal from "../gabinet/patientPortal.js";
import type * as gabinet_patients from "../gabinet/patients.js";
import type * as gabinet_scheduling from "../gabinet/scheduling.js";
import type * as gabinet_seed from "../gabinet/seed.js";
import type * as gabinet_sidebarWidgets from "../gabinet/sidebarWidgets.js";
import type * as gabinet_treatments from "../gabinet/treatments.js";
import type * as gabinetRoles from "../gabinetRoles.js";
import type * as google__helpers from "../google/_helpers.js";
import type * as google_calendar from "../google/calendar.js";
import type * as google_calendarSync from "../google/calendarSync.js";
import type * as google_calendarSyncHelpers_supabase from "../google/calendarSyncHelpers_supabase.js";
import type * as google_gmail from "../google/gmail.js";
import type * as google_oauth from "../google/oauth.js";
import type * as googleCalendarSyncConfigs from "../googleCalendarSyncConfigs.js";
import type * as http from "../http.js";
import type * as init from "../init.js";
import type * as invitations from "../invitations.js";
import type * as leads from "../leads.js";
import type * as lostReasons from "../lostReasons.js";
import type * as mail_adapter from "../mail/adapter.js";
import type * as mail_adapters_google from "../mail/adapters/google.js";
import type * as mail_adapters_mailgun from "../mail/adapters/mailgun.js";
import type * as mail_adapters_microsoft from "../mail/adapters/microsoft.js";
import type * as mail_adapters_resend from "../mail/adapters/resend.js";
import type * as mail_emailShell from "../mail/emailShell.js";
import type * as mail_testConnectionNode from "../mail/testConnectionNode.js";
import type * as mailProviders from "../mailProviders.js";
import type * as microsoft_oauth from "../microsoft/oauth.js";
import type * as migrations_backfillMailProviders from "../migrations/backfillMailProviders.js";
import type * as migrations_backfillTreatmentCategories from "../migrations/backfillTreatmentCategories.js";
import type * as migrations_emailTemplateMigrations from "../migrations/emailTemplateMigrations.js";
import type * as migrations_migrateGabinetDocuments from "../migrations/migrateGabinetDocuments.js";
import type * as notes from "../notes.js";
import type * as notifications from "../notifications.js";
import type * as nudges from "../nudges.js";
import type * as oauthConnections from "../oauthConnections.js";
import type * as orgSettings from "../orgSettings.js";
import type * as organizations from "../organizations.js";
import type * as otp_ResendOTP from "../otp/ResendOTP.js";
import type * as otp_VerificationCodeEmail from "../otp/VerificationCodeEmail.js";
import type * as payments from "../payments.js";
import type * as permissions from "../permissions.js";
import type * as pipelineStageActions from "../pipelineStageActions.js";
import type * as pipelines from "../pipelines.js";
import type * as platformAdmins from "../platformAdmins.js";
import type * as platformSettings from "../platformSettings.js";
import type * as productSubscriptions from "../productSubscriptions.js";
import type * as products from "../products.js";
import type * as recentlyViewed from "../recentlyViewed.js";
import type * as relationships from "../relationships.js";
import type * as resourceInvites from "../resourceInvites.js";
import type * as savedViews from "../savedViews.js";
import type * as scheduledActivities from "../scheduledActivities.js";
import type * as schema_automation from "../schema/automation.js";
import type * as schema_crm from "../schema/crm.js";
import type * as schema_documents from "../schema/documents.js";
import type * as schema_gabinet from "../schema/gabinet.js";
import type * as schema_platform from "../schema/platform.js";
import type * as search from "../search.js";
import type * as seedDefaults from "../seedDefaults.js";
import type * as seedEmailEvents from "../seedEmailEvents.js";
import type * as seedTemplates from "../seedTemplates.js";
import type * as sidebarWidgets from "../sidebarWidgets.js";
import type * as signatureRequests from "../signatureRequests.js";
import type * as signingEmails from "../signingEmails.js";
import type * as sms from "../sms.js";
import type * as sources from "../sources.js";
import type * as stripe from "../stripe.js";
import type * as supabase_activities from "../supabase/activities.js";
import type * as supabase_auditLog from "../supabase/auditLog.js";
import type * as supabase_automationRunSteps from "../supabase/automationRunSteps.js";
import type * as supabase_automationRuns from "../supabase/automationRuns.js";
import type * as supabase_backfill from "../supabase/backfill.js";
import type * as supabase_client from "../supabase/client.js";
import type * as supabase_emailEventLog from "../supabase/emailEventLog.js";
import type * as supabase_emails from "../supabase/emails.js";
import type * as supabase_formDocuments from "../supabase/formDocuments.js";
import type * as supabase_jwt from "../supabase/jwt.js";
import type * as supabase_organizations from "../supabase/organizations.js";
import type * as supabase_subscriptions from "../supabase/subscriptions.js";
import type * as supabase_syncAudit from "../supabase/syncAudit.js";
import type * as supabase_users from "../supabase/users.js";
import type * as supabase_usersHelpers from "../supabase/usersHelpers.js";
import type * as tagDefinitions from "../tagDefinitions.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "_helpers/activities": typeof _helpers_activities;
  "_helpers/activityEnvelope": typeof _helpers_activityEnvelope;
  "_helpers/auth": typeof _helpers_auth;
  "_helpers/authAction": typeof _helpers_authAction;
  "_helpers/gabinetRolePermissions": typeof _helpers_gabinetRolePermissions;
  "_helpers/html": typeof _helpers_html;
  "_helpers/logged": typeof _helpers_logged;
  "_helpers/permissionTypes": typeof _helpers_permissionTypes;
  "_helpers/permissions": typeof _helpers_permissions;
  "_helpers/portalSession": typeof _helpers_portalSession;
  "_helpers/products": typeof _helpers_products;
  "_helpers/seatLimits": typeof _helpers_seatLimits;
  "_helpers/supabaseDb": typeof _helpers_supabaseDb;
  "_helpers/supabaseRows": typeof _helpers_supabaseRows;
  _test: typeof _test;
  _test_helpers: typeof _test_helpers;
  activities: typeof activities;
  activityTypes: typeof activityTypes;
  app: typeof app;
  auditLog: typeof auditLog;
  auth: typeof auth;
  automation: typeof automation;
  automationRegistry: typeof automationRegistry;
  calls: typeof calls;
  categoryDefinitions: typeof categoryDefinitions;
  companies: typeof companies;
  contacts: typeof contacts;
  "crm/_registry": typeof crm__registry;
  "crm/documentDataSources": typeof crm_documentDataSources;
  "crm/seed": typeof crm_seed;
  crons: typeof crons;
  csvExport: typeof csvExport;
  csvImport: typeof csvImport;
  customFields: typeof customFields;
  dashboard: typeof dashboard;
  "dev/emails": typeof dev_emails;
  "dev/helpers": typeof dev_helpers;
  documentDataSources: typeof documentDataSources;
  documentInstances: typeof documentInstances;
  documentTemplateFields: typeof documentTemplateFields;
  documentTemplates: typeof documentTemplates;
  documents: typeof documents;
  "documents/completeMissingData": typeof documents_completeMissingData;
  "documents/components": typeof documents_components;
  "documents/documents": typeof documents_documents;
  "documents/generate": typeof documents_generate;
  "documents/resolveComponents": typeof documents_resolveComponents;
  "documents/scopeResolver": typeof documents_scopeResolver;
  "documents/scopeResolver_supabase": typeof documents_scopeResolver_supabase;
  "documents/seed": typeof documents_seed;
  "documents/signing": typeof documents_signing;
  "documents/templates": typeof documents_templates;
  "email/index": typeof email_index;
  "email/providers": typeof email_providers;
  "email/templates/invitationEmail": typeof email_templates_invitationEmail;
  "email/templates/subscriptionEmail": typeof email_templates_subscriptionEmail;
  emailAccounts: typeof emailAccounts;
  emailBrandConfig: typeof emailBrandConfig;
  emailEventBindings: typeof emailEventBindings;
  emailEventTrigger: typeof emailEventTrigger;
  emailEvents: typeof emailEvents;
  emailLayouts: typeof emailLayouts;
  emailSending: typeof emailSending;
  emailSequences: typeof emailSequences;
  emailTemplateSeed: typeof emailTemplateSeed;
  emailTemplates: typeof emailTemplates;
  emails: typeof emails;
  emails_internal: typeof emails_internal;
  env: typeof env;
  errorLogs: typeof errorLogs;
  "gabinet/_availability": typeof gabinet__availability;
  "gabinet/_availability_supabase": typeof gabinet__availability_supabase;
  "gabinet/_e2eTest": typeof gabinet__e2eTest;
  "gabinet/_helpers/autoGenerateDocuments": typeof gabinet__helpers_autoGenerateDocuments;
  "gabinet/_helpers/documentGate": typeof gabinet__helpers_documentGate;
  "gabinet/_registry": typeof gabinet__registry;
  "gabinet/appointmentReminders": typeof gabinet_appointmentReminders;
  "gabinet/appointmentSms": typeof gabinet_appointmentSms;
  "gabinet/appointmentWorkflow": typeof gabinet_appointmentWorkflow;
  "gabinet/appointments": typeof gabinet_appointments;
  "gabinet/documentDataSources": typeof gabinet_documentDataSources;
  "gabinet/employees": typeof gabinet_employees;
  "gabinet/equipment": typeof gabinet_equipment;
  "gabinet/leaveTypes": typeof gabinet_leaveTypes;
  "gabinet/locations": typeof gabinet_locations;
  "gabinet/loyalty": typeof gabinet_loyalty;
  "gabinet/nudges": typeof gabinet_nudges;
  "gabinet/onboarding": typeof gabinet_onboarding;
  "gabinet/packages": typeof gabinet_packages;
  "gabinet/patientAuth": typeof gabinet_patientAuth;
  "gabinet/patientPortal": typeof gabinet_patientPortal;
  "gabinet/patients": typeof gabinet_patients;
  "gabinet/scheduling": typeof gabinet_scheduling;
  "gabinet/seed": typeof gabinet_seed;
  "gabinet/sidebarWidgets": typeof gabinet_sidebarWidgets;
  "gabinet/treatments": typeof gabinet_treatments;
  gabinetRoles: typeof gabinetRoles;
  "google/_helpers": typeof google__helpers;
  "google/calendar": typeof google_calendar;
  "google/calendarSync": typeof google_calendarSync;
  "google/calendarSyncHelpers_supabase": typeof google_calendarSyncHelpers_supabase;
  "google/gmail": typeof google_gmail;
  "google/oauth": typeof google_oauth;
  googleCalendarSyncConfigs: typeof googleCalendarSyncConfigs;
  http: typeof http;
  init: typeof init;
  invitations: typeof invitations;
  leads: typeof leads;
  lostReasons: typeof lostReasons;
  "mail/adapter": typeof mail_adapter;
  "mail/adapters/google": typeof mail_adapters_google;
  "mail/adapters/mailgun": typeof mail_adapters_mailgun;
  "mail/adapters/microsoft": typeof mail_adapters_microsoft;
  "mail/adapters/resend": typeof mail_adapters_resend;
  "mail/emailShell": typeof mail_emailShell;
  "mail/testConnectionNode": typeof mail_testConnectionNode;
  mailProviders: typeof mailProviders;
  "microsoft/oauth": typeof microsoft_oauth;
  "migrations/backfillMailProviders": typeof migrations_backfillMailProviders;
  "migrations/backfillTreatmentCategories": typeof migrations_backfillTreatmentCategories;
  "migrations/emailTemplateMigrations": typeof migrations_emailTemplateMigrations;
  "migrations/migrateGabinetDocuments": typeof migrations_migrateGabinetDocuments;
  notes: typeof notes;
  notifications: typeof notifications;
  nudges: typeof nudges;
  oauthConnections: typeof oauthConnections;
  orgSettings: typeof orgSettings;
  organizations: typeof organizations;
  "otp/ResendOTP": typeof otp_ResendOTP;
  "otp/VerificationCodeEmail": typeof otp_VerificationCodeEmail;
  payments: typeof payments;
  permissions: typeof permissions;
  pipelineStageActions: typeof pipelineStageActions;
  pipelines: typeof pipelines;
  platformAdmins: typeof platformAdmins;
  platformSettings: typeof platformSettings;
  productSubscriptions: typeof productSubscriptions;
  products: typeof products;
  recentlyViewed: typeof recentlyViewed;
  relationships: typeof relationships;
  resourceInvites: typeof resourceInvites;
  savedViews: typeof savedViews;
  scheduledActivities: typeof scheduledActivities;
  "schema/automation": typeof schema_automation;
  "schema/crm": typeof schema_crm;
  "schema/documents": typeof schema_documents;
  "schema/gabinet": typeof schema_gabinet;
  "schema/platform": typeof schema_platform;
  search: typeof search;
  seedDefaults: typeof seedDefaults;
  seedEmailEvents: typeof seedEmailEvents;
  seedTemplates: typeof seedTemplates;
  sidebarWidgets: typeof sidebarWidgets;
  signatureRequests: typeof signatureRequests;
  signingEmails: typeof signingEmails;
  sms: typeof sms;
  sources: typeof sources;
  stripe: typeof stripe;
  "supabase/activities": typeof supabase_activities;
  "supabase/auditLog": typeof supabase_auditLog;
  "supabase/automationRunSteps": typeof supabase_automationRunSteps;
  "supabase/automationRuns": typeof supabase_automationRuns;
  "supabase/backfill": typeof supabase_backfill;
  "supabase/client": typeof supabase_client;
  "supabase/emailEventLog": typeof supabase_emailEventLog;
  "supabase/emails": typeof supabase_emails;
  "supabase/formDocuments": typeof supabase_formDocuments;
  "supabase/jwt": typeof supabase_jwt;
  "supabase/organizations": typeof supabase_organizations;
  "supabase/subscriptions": typeof supabase_subscriptions;
  "supabase/syncAudit": typeof supabase_syncAudit;
  "supabase/users": typeof supabase_users;
  "supabase/usersHelpers": typeof supabase_usersHelpers;
  tagDefinitions: typeof tagDefinitions;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
