/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _ai_documentAnalyzer from "../_ai/documentAnalyzer.js";
import type * as _ai_invoiceMatching from "../_ai/invoiceMatching.js";
import type * as _ai_kinds_formTemplate from "../_ai/kinds/formTemplate.js";
import type * as _ai_kinds_invoice from "../_ai/kinds/invoice.js";
import type * as _ai_providers_openaiDocumentAnalyzer from "../_ai/providers/openaiDocumentAnalyzer.js";
import type * as _ai_registry from "../_ai/registry.js";
import type * as _helpers_activities from "../_helpers/activities.js";
import type * as _helpers_activityEnvelope from "../_helpers/activityEnvelope.js";
import type * as _helpers_auth from "../_helpers/auth.js";
import type * as _helpers_authAction from "../_helpers/authAction.js";
import type * as _helpers_formatCurrency from "../_helpers/formatCurrency.js";
import type * as _helpers_gabinetRolePermissions from "../_helpers/gabinetRolePermissions.js";
import type * as _helpers_html from "../_helpers/html.js";
import type * as _helpers_logged from "../_helpers/logged.js";
import type * as _helpers_logger from "../_helpers/logger.js";
import type * as _helpers_permissionTypes from "../_helpers/permissionTypes.js";
import type * as _helpers_permissions from "../_helpers/permissions.js";
import type * as _helpers_portalSession from "../_helpers/portalSession.js";
import type * as _helpers_products from "../_helpers/products.js";
import type * as _helpers_seatLimits from "../_helpers/seatLimits.js";
import type * as _helpers_supabaseDb from "../_helpers/supabaseDb.js";
import type * as _helpers_supabaseRows from "../_helpers/supabaseRows.js";
import type * as _test from "../_test.js";
import type * as _test_helpers from "../_test_helpers.js";
import type * as activities from "../activities.js";
import type * as activityTypes from "../activityTypes.js";
import type * as admin_entitlements from "../admin/entitlements.js";
import type * as app from "../app.js";
import type * as auditLog from "../auditLog.js";
import type * as auth from "../auth.js";
import type * as automation from "../automation.js";
import type * as automationRegistry from "../automationRegistry.js";
import type * as categoryDefinitions from "../categoryDefinitions.js";
import type * as crm__registry from "../crm/_registry.js";
import type * as crm_calls from "../crm/calls.js";
import type * as crm_companies from "../crm/companies.js";
import type * as crm_contacts from "../crm/contacts.js";
import type * as crm_csvExport from "../crm/csvExport.js";
import type * as crm_csvImport from "../crm/csvImport.js";
import type * as crm_documentDataSources from "../crm/documentDataSources.js";
import type * as crm_documents from "../crm/documents.js";
import type * as crm_emailAccounts from "../crm/emailAccounts.js";
import type * as crm_emails from "../crm/emails.js";
import type * as crm_emails_internal from "../crm/emails_internal.js";
import type * as crm_leads from "../crm/leads.js";
import type * as crm_lostReasons from "../crm/lostReasons.js";
import type * as crm_notes from "../crm/notes.js";
import type * as crm_pipelineStageActions from "../crm/pipelineStageActions.js";
import type * as crm_pipelines from "../crm/pipelines.js";
import type * as crm_products from "../crm/products.js";
import type * as crm_savedViews from "../crm/savedViews.js";
import type * as crm_seed from "../crm/seed.js";
import type * as crm_sources from "../crm/sources.js";
import type * as crons from "../crons.js";
import type * as customFields from "../customFields.js";
import type * as dev_emails from "../dev/emails.js";
import type * as dev_helpers from "../dev/helpers.js";
import type * as documentAnalysisJobs from "../documentAnalysisJobs.js";
import type * as documentDataSources from "../documentDataSources.js";
import type * as documentInstances from "../documentInstances.js";
import type * as documentTemplateFields from "../documentTemplateFields.js";
import type * as documentTemplates from "../documentTemplates.js";
import type * as documents__helpers_patientBindings from "../documents/_helpers/patientBindings.js";
import type * as documents_completeMissingData from "../documents/completeMissingData.js";
import type * as documents_components from "../documents/components.js";
import type * as documents_documents from "../documents/documents.js";
import type * as documents_generate from "../documents/generate.js";
import type * as documents_intakeSummary from "../documents/intakeSummary.js";
import type * as documents_resolveComponents from "../documents/resolveComponents.js";
import type * as documents_scopeResolver from "../documents/scopeResolver.js";
import type * as documents_scopeResolver_supabase from "../documents/scopeResolver_supabase.js";
import type * as documents_seed from "../documents/seed.js";
import type * as documents_signing from "../documents/signing.js";
import type * as documents_templates from "../documents/templates.js";
import type * as email_index from "../email/index.js";
import type * as email_providers from "../email/providers.js";
import type * as email_templates_invitationEmail from "../email/templates/invitationEmail.js";
import type * as email_templates_subscriptionEmail from "../email/templates/subscriptionEmail.js";
import type * as emailBrandConfig from "../emailBrandConfig.js";
import type * as emailEventBindings from "../emailEventBindings.js";
import type * as emailEventTrigger from "../emailEventTrigger.js";
import type * as emailEvents from "../emailEvents.js";
import type * as emailLayouts from "../emailLayouts.js";
import type * as emailSendLog from "../emailSendLog.js";
import type * as emailSending from "../emailSending.js";
import type * as emailSequences from "../emailSequences.js";
import type * as emailTemplateSeed from "../emailTemplateSeed.js";
import type * as emailTemplates from "../emailTemplates.js";
import type * as env from "../env.js";
import type * as errorLogs from "../errorLogs.js";
import type * as fiscal_fiscalBridge from "../fiscal/fiscalBridge.js";
import type * as gabinet__availability_supabase from "../gabinet/_availability_supabase.js";
import type * as gabinet__e2eTest from "../gabinet/_e2eTest.js";
import type * as gabinet__helpers_autoGenerateDocuments from "../gabinet/_helpers/autoGenerateDocuments.js";
import type * as gabinet__helpers_documentGate from "../gabinet/_helpers/documentGate.js";
import type * as gabinet__helpers_junctionTreatments from "../gabinet/_helpers/junctionTreatments.js";
import type * as gabinet__helpers_loyaltyTier from "../gabinet/_helpers/loyaltyTier.js";
import type * as gabinet__registry from "../gabinet/_registry.js";
import type * as gabinet_appointmentReminders from "../gabinet/appointmentReminders.js";
import type * as gabinet_appointmentSms from "../gabinet/appointmentSms.js";
import type * as gabinet_appointments from "../gabinet/appointments.js";
import type * as gabinet_csvImport from "../gabinet/csvImport.js";
import type * as gabinet_dayClose from "../gabinet/dayClose.js";
import type * as gabinet_documentDataSources from "../gabinet/documentDataSources.js";
import type * as gabinet_employees from "../gabinet/employees.js";
import type * as gabinet_equipment from "../gabinet/equipment.js";
import type * as gabinet_inventory from "../gabinet/inventory.js";
import type * as gabinet_leaveTypes from "../gabinet/leaveTypes.js";
import type * as gabinet_locations from "../gabinet/locations.js";
import type * as gabinet_loyaltyTiers from "../gabinet/loyaltyTiers.js";
import type * as gabinet_nudges from "../gabinet/nudges.js";
import type * as gabinet_onboarding from "../gabinet/onboarding.js";
import type * as gabinet_overtime from "../gabinet/overtime.js";
import type * as gabinet_packages from "../gabinet/packages.js";
import type * as gabinet_patientAuth from "../gabinet/patientAuth.js";
import type * as gabinet_patientPortal from "../gabinet/patientPortal.js";
import type * as gabinet_patients from "../gabinet/patients.js";
import type * as gabinet_receipts from "../gabinet/receipts.js";
import type * as gabinet_scheduling from "../gabinet/scheduling.js";
import type * as gabinet_seed from "../gabinet/seed.js";
import type * as gabinet_sidebarWidgets from "../gabinet/sidebarWidgets.js";
import type * as gabinet_treatments from "../gabinet/treatments.js";
import type * as gabinet_waitlist from "../gabinet/waitlist.js";
import type * as gabinetRoles from "../gabinetRoles.js";
import type * as google__helpers from "../google/_helpers.js";
import type * as google_calendar from "../google/calendar.js";
import type * as google_calendarSync from "../google/calendarSync.js";
import type * as google_calendarSyncHelpers_supabase from "../google/calendarSyncHelpers_supabase.js";
import type * as google_gmail from "../google/gmail.js";
import type * as google_oauth from "../google/oauth.js";
import type * as googleCalendarSyncConfigs from "../googleCalendarSyncConfigs.js";
import type * as http from "../http.js";
import type * as init from "../init.js";
import type * as inventory from "../inventory.js";
import type * as invitations from "../invitations.js";
import type * as mail_adapter from "../mail/adapter.js";
import type * as mail_adapters_google from "../mail/adapters/google.js";
import type * as mail_adapters_mailgun from "../mail/adapters/mailgun.js";
import type * as mail_adapters_microsoft from "../mail/adapters/microsoft.js";
import type * as mail_adapters_resend from "../mail/adapters/resend.js";
import type * as mail_emailShell from "../mail/emailShell.js";
import type * as mail_testConnectionNode from "../mail/testConnectionNode.js";
import type * as mailProviders from "../mailProviders.js";
import type * as microsoft_oauth from "../microsoft/oauth.js";
import type * as migrations_backfillEntitlements from "../migrations/backfillEntitlements.js";
import type * as migrations_backfillCreditEarned from "../migrations/backfillCreditEarned.js";
import type * as migrations_backfillMailProviders from "../migrations/backfillMailProviders.js";
import type * as migrations_backfillProductSubscriptions from "../migrations/backfillProductSubscriptions.js";
import type * as migrations_backfillTreatmentCategories from "../migrations/backfillTreatmentCategories.js";
import type * as migrations_emailTemplateMigrations from "../migrations/emailTemplateMigrations.js";
import type * as notifications from "../notifications.js";
import type * as nudges from "../nudges.js";
import type * as oauthConnections from "../oauthConnections.js";
import type * as orgSettings from "../orgSettings.js";
import type * as organizations from "../organizations.js";
import type * as otp_ResendOTP from "../otp/ResendOTP.js";
import type * as otp_VerificationCodeEmail from "../otp/VerificationCodeEmail.js";
import type * as payments from "../payments.js";
import type * as permissions from "../permissions.js";
import type * as platformAdmins from "../platformAdmins.js";
import type * as platformSettings from "../platformSettings.js";
import type * as productSubscriptions from "../productSubscriptions.js";
import type * as recentlyViewed from "../recentlyViewed.js";
import type * as relationships from "../relationships.js";
import type * as resourceInvites from "../resourceInvites.js";
import type * as scheduledActivities from "../scheduledActivities.js";
import type * as schema_automation from "../schema/automation.js";
import type * as schema_crm from "../schema/crm.js";
import type * as schema_documents from "../schema/documents.js";
import type * as schema_gabinet from "../schema/gabinet.js";
import type * as schema_platform from "../schema/platform.js";
import type * as seedDefaults from "../seedDefaults.js";
import type * as seedEmailEvents from "../seedEmailEvents.js";
import type * as seedTemplates from "../seedTemplates.js";
import type * as signatureRequests from "../signatureRequests.js";
import type * as signingEmails from "../signingEmails.js";
import type * as signingStubs from "../signingStubs.js";
import type * as sms from "../sms.js";
import type * as stripe from "../stripe.js";
import type * as supabase_auditLog from "../supabase/auditLog.js";
import type * as supabase_backfill from "../supabase/backfill.js";
import type * as supabase_client from "../supabase/client.js";
import type * as supabase_emails from "../supabase/emails.js";
import type * as supabase_formDocuments from "../supabase/formDocuments.js";
import type * as supabase_jwt from "../supabase/jwt.js";
import type * as supabase_organizations from "../supabase/organizations.js";
import type * as supabase_subscriptions from "../supabase/subscriptions.js";
import type * as supabase_syncAudit from "../supabase/syncAudit.js";
import type * as supabase_users from "../supabase/users.js";
import type * as supabase_usersHelpers from "../supabase/usersHelpers.js";
import type * as tagDefinitions from "../tagDefinitions.js";
import type * as warehouseDeliveries from "../warehouseDeliveries.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "_ai/documentAnalyzer": typeof _ai_documentAnalyzer;
  "_ai/invoiceMatching": typeof _ai_invoiceMatching;
  "_ai/kinds/formTemplate": typeof _ai_kinds_formTemplate;
  "_ai/kinds/invoice": typeof _ai_kinds_invoice;
  "_ai/providers/openaiDocumentAnalyzer": typeof _ai_providers_openaiDocumentAnalyzer;
  "_ai/registry": typeof _ai_registry;
  "_helpers/activities": typeof _helpers_activities;
  "_helpers/activityEnvelope": typeof _helpers_activityEnvelope;
  "_helpers/auth": typeof _helpers_auth;
  "_helpers/authAction": typeof _helpers_authAction;
  "_helpers/formatCurrency": typeof _helpers_formatCurrency;
  "_helpers/gabinetRolePermissions": typeof _helpers_gabinetRolePermissions;
  "_helpers/html": typeof _helpers_html;
  "_helpers/logged": typeof _helpers_logged;
  "_helpers/logger": typeof _helpers_logger;
  "_helpers/permissionTypes": typeof _helpers_permissionTypes;
  "_helpers/permissions": typeof _helpers_permissions;
  "_helpers/portalSession": typeof _helpers_portalSession;
  "_helpers/products": typeof _helpers_products;
  "_helpers/seatLimits": typeof _helpers_seatLimits;
  "_helpers/supabaseDb": typeof _helpers_supabaseDb;
  "_helpers/supabaseRows": typeof _helpers_supabaseRows;
  _test: typeof _test;
  _test_helpers: typeof _test_helpers;
  activities: typeof activities;
  activityTypes: typeof activityTypes;
  "admin/entitlements": typeof admin_entitlements;
  app: typeof app;
  auditLog: typeof auditLog;
  auth: typeof auth;
  automation: typeof automation;
  automationRegistry: typeof automationRegistry;
  categoryDefinitions: typeof categoryDefinitions;
  "crm/_registry": typeof crm__registry;
  "crm/calls": typeof crm_calls;
  "crm/companies": typeof crm_companies;
  "crm/contacts": typeof crm_contacts;
  "crm/csvExport": typeof crm_csvExport;
  "crm/csvImport": typeof crm_csvImport;
  "crm/documentDataSources": typeof crm_documentDataSources;
  "crm/documents": typeof crm_documents;
  "crm/emailAccounts": typeof crm_emailAccounts;
  "crm/emails": typeof crm_emails;
  "crm/emails_internal": typeof crm_emails_internal;
  "crm/leads": typeof crm_leads;
  "crm/lostReasons": typeof crm_lostReasons;
  "crm/notes": typeof crm_notes;
  "crm/pipelineStageActions": typeof crm_pipelineStageActions;
  "crm/pipelines": typeof crm_pipelines;
  "crm/products": typeof crm_products;
  "crm/savedViews": typeof crm_savedViews;
  "crm/seed": typeof crm_seed;
  "crm/sources": typeof crm_sources;
  crons: typeof crons;
  customFields: typeof customFields;
  "dev/emails": typeof dev_emails;
  "dev/helpers": typeof dev_helpers;
  documentAnalysisJobs: typeof documentAnalysisJobs;
  documentDataSources: typeof documentDataSources;
  documentInstances: typeof documentInstances;
  documentTemplateFields: typeof documentTemplateFields;
  documentTemplates: typeof documentTemplates;
  "documents/_helpers/patientBindings": typeof documents__helpers_patientBindings;
  "documents/completeMissingData": typeof documents_completeMissingData;
  "documents/components": typeof documents_components;
  "documents/documents": typeof documents_documents;
  "documents/generate": typeof documents_generate;
  "documents/intakeSummary": typeof documents_intakeSummary;
  "documents/resolveComponents": typeof documents_resolveComponents;
  "documents/scopeResolver": typeof documents_scopeResolver;
  "documents/scopeResolver_supabase": typeof documents_scopeResolver_supabase;
  "documents/seed": typeof documents_seed;
  "documents/signing": typeof documents_signing;
  "documents/templates": typeof documents_templates;
  "email/index": typeof email_index;
  "email/providers": typeof email_providers;
  "email/templates/invitationEmail": typeof email_templates_invitationEmail;
  "email/templates/subscriptionEmail": typeof email_templates_subscriptionEmail;
  emailBrandConfig: typeof emailBrandConfig;
  emailEventBindings: typeof emailEventBindings;
  emailEventTrigger: typeof emailEventTrigger;
  emailEvents: typeof emailEvents;
  emailLayouts: typeof emailLayouts;
  emailSendLog: typeof emailSendLog;
  emailSending: typeof emailSending;
  emailSequences: typeof emailSequences;
  emailTemplateSeed: typeof emailTemplateSeed;
  emailTemplates: typeof emailTemplates;
  env: typeof env;
  errorLogs: typeof errorLogs;
  "fiscal/fiscalBridge": typeof fiscal_fiscalBridge;
  "gabinet/_availability_supabase": typeof gabinet__availability_supabase;
  "gabinet/_e2eTest": typeof gabinet__e2eTest;
  "gabinet/_helpers/autoGenerateDocuments": typeof gabinet__helpers_autoGenerateDocuments;
  "gabinet/_helpers/documentGate": typeof gabinet__helpers_documentGate;
  "gabinet/_helpers/junctionTreatments": typeof gabinet__helpers_junctionTreatments;
  "gabinet/_helpers/loyaltyTier": typeof gabinet__helpers_loyaltyTier;
  "gabinet/_registry": typeof gabinet__registry;
  "gabinet/appointmentReminders": typeof gabinet_appointmentReminders;
  "gabinet/appointmentSms": typeof gabinet_appointmentSms;
  "gabinet/appointments": typeof gabinet_appointments;
  "gabinet/csvImport": typeof gabinet_csvImport;
  "gabinet/dayClose": typeof gabinet_dayClose;
  "gabinet/documentDataSources": typeof gabinet_documentDataSources;
  "gabinet/employees": typeof gabinet_employees;
  "gabinet/equipment": typeof gabinet_equipment;
  "gabinet/inventory": typeof gabinet_inventory;
  "gabinet/leaveTypes": typeof gabinet_leaveTypes;
  "gabinet/locations": typeof gabinet_locations;
  "gabinet/loyaltyTiers": typeof gabinet_loyaltyTiers;
  "gabinet/nudges": typeof gabinet_nudges;
  "gabinet/onboarding": typeof gabinet_onboarding;
  "gabinet/overtime": typeof gabinet_overtime;
  "gabinet/packages": typeof gabinet_packages;
  "gabinet/patientAuth": typeof gabinet_patientAuth;
  "gabinet/patientPortal": typeof gabinet_patientPortal;
  "gabinet/patients": typeof gabinet_patients;
  "gabinet/receipts": typeof gabinet_receipts;
  "gabinet/scheduling": typeof gabinet_scheduling;
  "gabinet/seed": typeof gabinet_seed;
  "gabinet/sidebarWidgets": typeof gabinet_sidebarWidgets;
  "gabinet/treatments": typeof gabinet_treatments;
  "gabinet/waitlist": typeof gabinet_waitlist;
  gabinetRoles: typeof gabinetRoles;
  "google/_helpers": typeof google__helpers;
  "google/calendar": typeof google_calendar;
  "google/calendarSync": typeof google_calendarSync;
  "google/calendarSyncHelpers_supabase": typeof google_calendarSyncHelpers_supabase;
  "google/gmail": typeof google_gmail;
  "google/oauth": typeof google_oauth;
  googleCalendarSyncConfigs: typeof googleCalendarSyncConfigs;
  http: typeof http;
  init: typeof init;
  inventory: typeof inventory;
  invitations: typeof invitations;
  "mail/adapter": typeof mail_adapter;
  "mail/adapters/google": typeof mail_adapters_google;
  "mail/adapters/mailgun": typeof mail_adapters_mailgun;
  "mail/adapters/microsoft": typeof mail_adapters_microsoft;
  "mail/adapters/resend": typeof mail_adapters_resend;
  "mail/emailShell": typeof mail_emailShell;
  "mail/testConnectionNode": typeof mail_testConnectionNode;
  mailProviders: typeof mailProviders;
  "microsoft/oauth": typeof microsoft_oauth;
  "migrations/backfillEntitlements": typeof migrations_backfillEntitlements;
  "migrations/backfillCreditEarned": typeof migrations_backfillCreditEarned;
  "migrations/backfillMailProviders": typeof migrations_backfillMailProviders;
  "migrations/backfillProductSubscriptions": typeof migrations_backfillProductSubscriptions;
  "migrations/backfillTreatmentCategories": typeof migrations_backfillTreatmentCategories;
  "migrations/emailTemplateMigrations": typeof migrations_emailTemplateMigrations;
  notifications: typeof notifications;
  nudges: typeof nudges;
  oauthConnections: typeof oauthConnections;
  orgSettings: typeof orgSettings;
  organizations: typeof organizations;
  "otp/ResendOTP": typeof otp_ResendOTP;
  "otp/VerificationCodeEmail": typeof otp_VerificationCodeEmail;
  payments: typeof payments;
  permissions: typeof permissions;
  platformAdmins: typeof platformAdmins;
  platformSettings: typeof platformSettings;
  productSubscriptions: typeof productSubscriptions;
  recentlyViewed: typeof recentlyViewed;
  relationships: typeof relationships;
  resourceInvites: typeof resourceInvites;
  scheduledActivities: typeof scheduledActivities;
  "schema/automation": typeof schema_automation;
  "schema/crm": typeof schema_crm;
  "schema/documents": typeof schema_documents;
  "schema/gabinet": typeof schema_gabinet;
  "schema/platform": typeof schema_platform;
  seedDefaults: typeof seedDefaults;
  seedEmailEvents: typeof seedEmailEvents;
  seedTemplates: typeof seedTemplates;
  signatureRequests: typeof signatureRequests;
  signingEmails: typeof signingEmails;
  signingStubs: typeof signingStubs;
  sms: typeof sms;
  stripe: typeof stripe;
  "supabase/auditLog": typeof supabase_auditLog;
  "supabase/backfill": typeof supabase_backfill;
  "supabase/client": typeof supabase_client;
  "supabase/emails": typeof supabase_emails;
  "supabase/formDocuments": typeof supabase_formDocuments;
  "supabase/jwt": typeof supabase_jwt;
  "supabase/organizations": typeof supabase_organizations;
  "supabase/subscriptions": typeof supabase_subscriptions;
  "supabase/syncAudit": typeof supabase_syncAudit;
  "supabase/users": typeof supabase_users;
  "supabase/usersHelpers": typeof supabase_usersHelpers;
  tagDefinitions: typeof tagDefinitions;
  warehouseDeliveries: typeof warehouseDeliveries;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
