/**
 * Form Documents Mapper — Supabase ↔ Frontend
 */

import type { Database } from "../database.types";
import { createEntityMapper } from "./generic";

export type FormDocumentRow = Database["public"]["Tables"]["form_documents"]["Row"];

export interface MappedFormDocument {
  _id: string;
  organizationId: string;
  templateId: string;
  title: string;
  responseData: string;
  entityType: string;
  entityId: string;
  scopeEntities?: string;
  status: string;
  signatureData?: string;
  signedAt?: number;
  signedByName?: string;
  signedByEmail?: string;
  signedByIp?: string;
  signatureVerificationMethod?: string;
  signingToken?: string;
  signingTokenExpiresAt?: number;
  signingEmailSentAt?: number;
  signingReminderCount?: number;
  timing?: string;
  autoGenerated?: boolean;
  pdfStorageId?: string;
  pdfGeneratedAt?: number;
  createdBy: string;
  createdAt: number;
  updatedAt: number;
  _source: "supabase";
}

const formDocumentMapper = createEntityMapper<FormDocumentRow, MappedFormDocument>({
  exclude: [],
});

export const mapFormDocumentFromSupabase = formDocumentMapper.mapFromSupabase;
export const mapFormDocumentToSupabase = formDocumentMapper.mapToSupabase;
