import { query, action, internalMutation, internalQuery, MutationCtx } from "../_generated/server";
import { internal } from "../_generated/api";
import { createSupabaseDb } from "../_helpers/supabaseDb";
import {
  checkConflictSupabase,
  checkEmployeeQualificationSupabase,
  getAvailableSlotsSupabase,
  resolveAppointmentLocationSupabase,
} from "./_availability_supabase";
import { v } from "convex/values";
import { paginationOptsValidator } from "convex/server";
import { verifyOrgAccess } from "../_helpers/auth";
import { checkPermission } from "../_helpers/permissions";
import { verifyProductAccess } from "../_helpers/products";
import { logActivity } from "../_helpers/activities";
import { GABINET_PRODUCT_ID } from "./_registry";
import { gabinetAppointmentStatusValidator } from "../schema";
import {
  checkConflict,
  getAvailableSlots,
  checkEmployeeQualification,
  resolveAppointmentLocation,
} from "./_availability";
import { Id, Doc } from "../_generated/dataModel";
import { logAudit } from "../auditLog";
import { createNotificationDirect } from "../notifications";
import { autoGenerateAppointmentDocuments } from "./_helpers/autoGenerateDocuments";
import { checkDocumentGate } from "./_helpers/documentGate";

// Dual-write refs removed — Supabase is now primary for appointment writes

const VALID_TRANSITIONS: Record<string, string[]> = {
  pending_confirmation: ["scheduled", "confirmed", "cancelled"],
  scheduled: ["confirmed", "cancelled", "no_show"],
  confirmed: ["in_progress", "cancelled", "no_show"],
  in_progress: ["completed", "cancelled"],
  completed: [],
  cancelled: [],
  no_show: [],
};

function getSmsTargetStatus(intent: "confirm" | "cancel") {
  return intent === "confirm" ? "confirmed" : "cancelled";
}

async function emitAutomationEvent(
  ctx: MutationCtx,
  args: {
    organizationId: Id<"organizations">;
    module: "gabinet" | "crm" | "platform";
    eventType: string;
    entityType?: string;
    entityId?: string;
    actorUserId?: Id<"users">;
    correlationKey?: string;
    eventIdempotencyKey: string;
    payload: Record<string, unknown>;
  },
) {
  await ctx.runMutation(internal.automation.emitEvent, {
    organizationId: args.organizationId,
    module: args.module,
    eventType: args.eventType,
    entityType: args.entityType,
    entityId: args.entityId,
    actorUserId: args.actorUserId,
    correlationKey: args.correlationKey,
    eventIdempotencyKey: args.eventIdempotencyKey,
    payload: JSON.stringify(args.payload),
    occurredAt: Date.now(),
  });
}

async function applyAppointmentStatusChange(
  ctx: MutationCtx,
  args: {
    appointment: Doc<"gabinetAppointments">;
    organizationId: Id<"organizations">;
    nextStatus: Doc<"gabinetAppointments">["status"];
    actorUserId: Id<"users">;
    auditAction: string;
    auditDetails: string;
    activityDescription: string;
    notificationTitle: string;
    notificationMessage: string;
    cancellationReason?: string;
    sendCancellationNotifications?: boolean;
  },
) {
  const now = Date.now();
  const patch: Record<string, unknown> = {
    status: args.nextStatus,
    updatedAt: now,
  };

  if (args.nextStatus === "cancelled") {
    patch.cancelledAt = now;
    patch.cancelledBy = args.actorUserId;
    patch.cancellationReason = args.cancellationReason;
  }

  // Patch Convex record if it exists (Supabase is primary, Convex may lag)
  try {
    const convexRecord = await ctx.db.get(args.appointment._id);
    if (convexRecord) {
      await ctx.db.patch(args.appointment._id, patch);
    }
  } catch {
    // Convex record may not exist during Supabase-primary migration
  }

  if (args.nextStatus === "cancelled" && args.sendCancellationNotifications !== false) {
    const patient = await ctx.db.get(args.appointment.patientId);
    const treatment = args.appointment.treatmentId ? await ctx.db.get(args.appointment.treatmentId) : null;
    if (patient?.email) {
      const employee = await ctx.db.get(args.appointment.employeeId);
      const patientName = patient
        ? `${patient.firstName}${patient.lastName ? " " + patient.lastName : ""}`
        : "Patient";
      const treatmentName = treatment?.name ?? "Treatment";
      const employeeName = employee?.name ?? "Specjalista";
      await ctx.runMutation(internal.emailEventTrigger.triggerEmailEvent, {
        organizationId: args.organizationId,
        eventType: "appointment.cancelled",
        recipientEmail: patient.email,
        recipientName: patientName,
        payload: JSON.stringify({
          patientName,
          appointmentDate: args.appointment.date,
          appointmentTime: args.appointment.startTime,
          treatmentName,
          employeeName,
        }),
        triggeredBy: args.actorUserId,
      });
    }
    if (patient?.phone) {
      const smsMessage = `Twoja wizyta dnia ${args.appointment.date} o ${args.appointment.startTime} została odwołana.`;
      await ctx.scheduler.runAfter(0, internal.sms.sendAppointmentSms, {
        organizationId: args.organizationId,
        phone: patient.phone,
        message: smsMessage,
      });
    }
  }

  // scheduledActivity patched in Supabase by the parent action (Supabase-primary).

  if (
    args.nextStatus === "cancelled" ||
    args.nextStatus === "completed" ||
    args.nextStatus === "no_show"
  ) {
    await ctx.scheduler.runAfter(
      0,
      internal.gabinet.appointmentReminders.cancelRemindersInternal,
      { appointmentId: args.appointment._id },
    );
  }

  if (args.nextStatus === "completed") {
    if (args.appointment.treatmentId) {
      await handleAppointmentCompletion(ctx, {
        organizationId: args.organizationId,
        appointmentId: args.appointment._id,
        patientId: args.appointment.patientId,
        treatmentId: args.appointment.treatmentId,
        packageUsageId: args.appointment.packageUsageId as
          | Id<"gabinetPackageUsage">
          | undefined,
        userId: args.actorUserId,
      });
    }
  }

  await logActivity(ctx, {
    organizationId: args.organizationId,
    entityType: "gabinetAppointment",
    entityId: args.appointment._id,
    action: "status_changed",
    description: args.activityDescription,
    metadata: {
      oldStatus: args.appointment.status,
      newStatus: args.nextStatus,
    },
    performedBy: args.actorUserId,
  });

  await logAudit(ctx, {
    organizationId: args.organizationId,
    userId: args.actorUserId,
    action: args.auditAction,
    entityType: "gabinetAppointment",
    entityId: args.appointment._id,
    details: args.auditDetails,
  });

  if (args.appointment.createdBy !== args.actorUserId) {
    await createNotificationDirect(ctx, {
      organizationId: args.organizationId,
      userId: args.appointment.createdBy,
      type: "appointment_status_changed",
      title: args.notificationTitle,
      message: args.notificationMessage,
    });
  }
  if (
    args.appointment.employeeId !== args.actorUserId &&
    args.appointment.employeeId !== args.appointment.createdBy
  ) {
    await createNotificationDirect(ctx, {
      organizationId: args.organizationId,
      userId: args.appointment.employeeId,
      type: "appointment_status_changed",
      title: args.notificationTitle,
      message: args.notificationMessage,
    });
  }

  await emitAutomationEvent(ctx, {
    organizationId: args.organizationId,
    module: "gabinet",
    eventType:
      args.nextStatus === "cancelled"
        ? "gabinet.appointment.cancelled"
        : args.nextStatus === "completed"
          ? "gabinet.appointment.completed"
          : args.nextStatus === "no_show"
            ? "gabinet.appointment.no_show"
            : args.nextStatus === "confirmed"
              ? "gabinet.appointment.confirmed"
              : "gabinet.appointment.status_changed",
    entityType: "gabinetAppointment",
    entityId: String(args.appointment._id),
    actorUserId: args.actorUserId,
    correlationKey: `appointment:${args.appointment._id}`,
    eventIdempotencyKey: [
      "automation-event",
      String(args.organizationId),
      String(args.appointment._id),
      String(args.nextStatus),
      String(now),
    ].join(":"),
    payload: {
      organizationId: String(args.organizationId),
      appointmentId: String(args.appointment._id),
      patientId: String(args.appointment.patientId),
      employeeId: String(args.appointment.employeeId),
      treatmentId: String(args.appointment.treatmentId),
      status: args.nextStatus,
      previousStatus: args.appointment.status,
      date: args.appointment.date,
      startTime: args.appointment.startTime,
      cancellationReason: args.cancellationReason,
      createdBy: String(args.appointment.createdBy),
    },
  });
}

function generateRecurringDates(
  startDate: string,
  rule: { frequency: string; count?: number; until?: string },
): string[] {
  const dates: string[] = [];
  const d = new Date(startDate + "T00:00:00");
  const max = rule.count ?? 52;
  const untilDate = rule.until ? new Date(rule.until + "T23:59:59") : null;

  for (let i = 1; i < max; i++) {
    switch (rule.frequency) {
      case "daily":
        d.setDate(d.getDate() + 1);
        break;
      case "weekly":
        d.setDate(d.getDate() + 7);
        break;
      case "biweekly":
        d.setDate(d.getDate() + 14);
        break;
      case "monthly":
        d.setMonth(d.getMonth() + 1);
        break;
      default:
        return dates;
    }
    if (untilDate && d > untilDate) break;
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    dates.push(`${yyyy}-${mm}-${dd}`);
  }
  return dates;
}

export const list = query({
  args: {
    organizationId: v.id("organizations"),
    paginationOpts: paginationOptsValidator,
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const result = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_org", (q) => q.eq("organizationId", args.organizationId))
      .order("desc")
      .paginate(args.paginationOpts);
    if (perm.scope === "own") {
      return {
        ...result,
        page: result.page.filter((r) => r.createdBy === user._id),
      };
    }
    return result;
  },
});

export const getById = action({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.string(),
  },
  handler: async (ctx, args) => {
    const authResult = await ctx.runQuery(
      internal._helpers.authAction.verifyOrgAccess,
      { organizationId: args.organizationId },
    );
    const perm = await ctx.runQuery(internal._helpers.authAction.checkPermission, {
      organizationId: args.organizationId,
      feature: "gabinet_appointments",
      action: "view",
    }) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();
    const appt = await db.get("gabinetAppointments", args.appointmentId);
    if (!appt || String(appt.organizationId) !== String(args.organizationId)) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && String(appt.createdBy) !== String(authResult.userId)) {
      throw new Error("Permission denied: you can only view your own records");
    }
    return appt;
  },
});

export const listByDate = query({
  args: {
    organizationId: v.id("organizations"),
    date: v.string(),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const results = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndDate", (q) =>
        q.eq("organizationId", args.organizationId).eq("date", args.date),
      )
      .collect();
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listByDateRange = query({
  args: {
    organizationId: v.id("organizations"),
    startDate: v.string(),
    endDate: v.string(),
    employeeId: v.optional(v.id("users")),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    let results;
    if (args.employeeId) {
      results = await ctx.db
        .query("gabinetAppointments")
        .withIndex("by_orgAndEmployeeAndDate", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("employeeId", args.employeeId!)
            .gte("date", args.startDate)
            .lte("date", args.endDate),
        )
        .collect();
    } else {
      results = await ctx.db
        .query("gabinetAppointments")
        .withIndex("by_orgAndDate", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .gte("date", args.startDate)
            .lte("date", args.endDate),
        )
        .collect();
    }
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listByPatient = query({
  args: {
    organizationId: v.id("organizations"),
    patientId: v.id("gabinetPatients"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const results = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndPatient", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("patientId", args.patientId),
      )
      .collect();
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listByEmployee = query({
  args: {
    organizationId: v.id("organizations"),
    employeeId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const results = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndEmployee", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("employeeId", args.employeeId),
      )
      .collect();
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listPatientsForEmployee = query({
  args: {
    organizationId: v.id("organizations"),
    employeeId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    let appointments = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndEmployee", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("employeeId", args.employeeId),
      )
      .collect();
    if (perm.scope === "own") {
      appointments = appointments.filter((r) => r.createdBy === user._id);
    }

    const uniquePatientIds = [...new Set(appointments.map((a) => a.patientId))];
    const patients = await Promise.all(
      uniquePatientIds.map((pid) => ctx.db.get(pid)),
    );
    return patients.filter(Boolean);
  },
});

/**
 * Returns patients for an employee enriched with visit summary data
 * (visit count, last visit date, treatments used, statuses).
 * Used by the employee detail "Klienci" tab for search & filtering.
 */
export const listPatientsWithStatsForEmployee = query({
  args: {
    organizationId: v.id("organizations"),
    employeeId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    let appointments = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndEmployee", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("employeeId", args.employeeId),
      )
      .collect();
    if (perm.scope === "own") {
      appointments = appointments.filter((r) => r.createdBy === user._id);
    }

    // Group appointments by patient
    const byPatient = new Map<Id<"gabinetPatients">, typeof appointments>();
    for (const apt of appointments) {
      const patientId = apt.patientId;
      if (!byPatient.has(patientId)) byPatient.set(patientId, []);
      byPatient.get(patientId)!.push(apt);
    }

    const results = await Promise.all(
      Array.from(byPatient.entries()).map(async ([patientId, patientApts]) => {
        const patient = await ctx.db.get(patientId);
        if (!patient) return null;

        const sortedAppointments = [...patientApts].sort((a, b) => b.date.localeCompare(a.date));
        const lastVisitDate = sortedAppointments[0]?.date ?? null;
        const firstVisitDate = sortedAppointments[sortedAppointments.length - 1]?.date ?? null;
        const treatmentIds = [...new Set(patientApts.map((a) => a.treatmentId))];
        const statuses = [...new Set(patientApts.map((a) => a.status))];

        return {
          ...patient,
          visitCount: patientApts.length,
          lastVisitDate,
          firstVisitDate,
          treatmentIds,
          statuses,
        };
      }),
    );

    return results.filter((result) => result !== null);
  },
});

export const getAvailableSlotsQuery = action({
  args: {
    organizationId: v.id("organizations"),
    userId: v.string(),
    date: v.string(),
    duration: v.number(),
    locationId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    await ctx.runQuery(internal._helpers.authAction.verifyOrgAccess, {
      organizationId: args.organizationId,
    });
    const perm = await ctx.runQuery(internal._helpers.authAction.checkPermission, {
      organizationId: args.organizationId,
      feature: "gabinet_appointments",
      action: "view",
    }) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();
    return await getAvailableSlotsSupabase(db, {
      organizationId: String(args.organizationId),
      userId: args.userId,
      date: args.date,
      duration: args.duration,
      locationId: args.locationId,
    });
  },
});

export const checkQualification = action({
  args: {
    organizationId: v.id("organizations"),
    userId: v.string(),
    treatmentId: v.string(),
  },
  handler: async (ctx, args) => {
    await ctx.runQuery(internal._helpers.authAction.verifyOrgAccess, {
      organizationId: args.organizationId,
    });
    const perm = await ctx.runQuery(internal._helpers.authAction.checkPermission, {
      organizationId: args.organizationId,
      feature: "gabinet_appointments",
      action: "view",
    }) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();
    return await checkEmployeeQualificationSupabase(db, {
      organizationId: String(args.organizationId),
      userId: args.userId,
      treatmentId: args.treatmentId,
    });
  },
});

// ---------------------------------------------------------------------------
// Internal helpers for the create action (actions can't access ctx.db)
// ---------------------------------------------------------------------------

export const _getOrgSettings = internalQuery({
  args: { organizationId: v.id("organizations") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("orgSettings")
      .withIndex("by_org", (q) => q.eq("organizationId", args.organizationId))
      .unique();
  },
});

export const _checkConflictQuery = internalQuery({
  args: {
    organizationId: v.id("organizations"),
    userId: v.string(),
    date: v.string(),
    startTime: v.string(),
    endTime: v.string(),
    roomId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return await checkConflict(ctx, {
      ...args,
      userId: args.userId as Id<"users">,
      roomId: args.roomId as Id<"gabinetRooms"> | undefined,
    });
  },
});

export const _checkConflictWithExcludeQuery = internalQuery({
  args: {
    organizationId: v.id("organizations"),
    userId: v.string(),
    date: v.string(),
    startTime: v.string(),
    endTime: v.string(),
    excludeAppointmentId: v.optional(v.string()),
    roomId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return await checkConflict(ctx, {
      ...args,
      userId: args.userId as Id<"users">,
      excludeAppointmentId: args.excludeAppointmentId as Id<"gabinetAppointments"> | undefined,
      roomId: args.roomId as Id<"gabinetRooms"> | undefined,
    });
  },
});

export const _checkQualificationQuery = internalQuery({
  args: {
    organizationId: v.id("organizations"),
    userId: v.string(),
    treatmentId: v.string(),
  },
  handler: async (ctx, args) => {
    return await checkEmployeeQualification(ctx, {
      ...args,
      userId: args.userId as Id<"users">,
      treatmentId: args.treatmentId as Id<"gabinetTreatments">,
    });
  },
});

export const _resolveLocationQuery = internalQuery({
  args: {
    organizationId: v.id("organizations"),
    userId: v.string(),
    date: v.string(),
  },
  handler: async (ctx, args) => {
    const locationId = await resolveAppointmentLocation(ctx, {
      ...args,
      userId: args.userId as Id<"users">,
    });
    return locationId ? String(locationId) : null;
  },
});

export const _getAvailableSlotsQuery = internalQuery({
  args: {
    organizationId: v.id("organizations"),
    userId: v.string(),
    date: v.string(),
    duration: v.number(),
    locationId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return await getAvailableSlots(ctx, {
      ...args,
      userId: args.userId as Id<"users">,
      locationId: args.locationId as Id<"gabinetLocations"> | undefined,
    });
  },
});

export const _checkDocumentGateQuery = internalQuery({
  args: {
    appointmentId: v.string(),
    timing: v.union(v.literal("before_start"), v.literal("after_completion")),
  },
  handler: async (ctx, args) => {
    return await checkDocumentGate(ctx, args.appointmentId as Id<"gabinetAppointments">, args.timing);
  },
});

export const _resolveAutoPackageUsageMutation = internalMutation({
  args: {
    organizationId: v.id("organizations"),
    patientId: v.string(),
    treatmentId: v.string(),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    const treatment = await ctx.db.get(args.treatmentId as Id<"gabinetTreatments">);
    if (!treatment) return null;
    const result = await resolveAutoPackageUsage(ctx, {
      organizationId: args.organizationId,
      patientId: args.patientId as Id<"gabinetPatients">,
      treatmentId: args.treatmentId as Id<"gabinetTreatments">,
      userId: args.userId as Id<"users">,
      treatment,
    });
    return result ? String(result) : null;
  },
});

/**
 * Internal mutation that handles all Convex-only side effects after the
 * appointment has been written to Supabase by the create action.
 */
export const _createSideEffects = internalMutation({
  args: {
    // Appointment data (already written to Supabase)
    appointmentId: v.string(),
    organizationId: v.id("organizations"),
    patientId: v.string(),
    treatmentId: v.string(),
    employeeId: v.string(),
    date: v.string(),
    startTime: v.string(),
    endTime: v.string(),
    notes: v.optional(v.string()),
    status: v.string(),
    isRecurring: v.boolean(),
    recurringGroupId: v.optional(v.string()),
    sendReminder: v.boolean(),
    createdBy: v.string(),
    createdAt: v.number(),
    // Resolved names for calendar title
    patientName: v.string(),
    treatmentName: v.string(),
    // Patient contact info for automation event
    patientEmail: v.optional(v.string()),
    patientPhone: v.optional(v.string()),
    // Recurring series: list of {appointmentId, date, recurringIndex} for each item
    recurringAppointments: v.optional(v.array(v.object({
      appointmentId: v.string(),
      date: v.string(),
      recurringIndex: v.number(),
    }))),
    // Package usage (already resolved by action)
    packageUsageId: v.optional(v.string()),
    // Pre-resolved Supabase UUIDs from the parent action (scheduledActivities
    // are now written by the action, not here).
    scheduledActivityId: v.string(),
    recurActivityIds: v.array(v.object({
      appointmentId: v.string(),
      activityId: v.string(),
    })),
  },
  handler: async (ctx, args) => {
    const now = args.createdAt;
    const createdByUserId = args.createdBy as Id<"users">;

    const scheduledActivityId = args.scheduledActivityId;

    // --- 2. Emit automation event ---
    await emitAutomationEvent(ctx, {
      organizationId: args.organizationId,
      module: "gabinet",
      eventType: "gabinet.appointment.created",
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
      actorUserId: createdByUserId,
      correlationKey: `appointment:${args.appointmentId}`,
      eventIdempotencyKey: `automation-event:${args.organizationId}:${args.appointmentId}:created`,
      payload: {
        organizationId: String(args.organizationId),
        appointmentId: args.appointmentId,
        patientId: args.patientId,
        treatmentId: args.treatmentId,
        employeeId: args.employeeId,
        date: args.date,
        startTime: args.startTime,
        endTime: args.endTime,
        status: "scheduled",
        patientEmail: args.patientEmail,
        patientPhone: args.patientPhone,
        patientName: args.patientName,
        treatmentName: args.treatmentName,
        employeeName: args.employeeId,
        createdBy: args.createdBy,
      },
    });

    // --- 3. Auto-generate appointment documents ---
    await autoGenerateAppointmentDocuments(ctx, {
      organizationId: args.organizationId,
      appointmentId: args.appointmentId as Id<"gabinetAppointments">,
      treatmentId: args.treatmentId as Id<"gabinetTreatments">,
      patientId: args.patientId as Id<"gabinetPatients">,
      createdBy: createdByUserId,
      timing: "before_start",
    });

    // --- 4. Calendar events for recurring appointments already written to Supabase by the action ---
    const recurringAppointments = args.recurringAppointments ?? [];
    const recurActivityIds = args.recurActivityIds;

    // --- 5. Log activity ---
    await logActivity(ctx, {
      organizationId: args.organizationId,
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
      action: "created",
      description: `Created appointment for ${args.date} at ${args.startTime}`,
      performedBy: createdByUserId,
    });

    // --- 6. Schedule reminders (inline — avoid DB read since appointment is in Supabase) ---
    if (args.sendReminder) {
      try {
        const orgSettings = await ctx.db
          .query("orgSettings")
          .withIndex("by_org", (q) => q.eq("organizationId", args.organizationId))
          .unique();
        const reminderHours = (orgSettings as any)?.reminderHoursBefore ?? 24;

        const scheduleReminderFor = async (apptId: string, apptDate: string) => {
          const appointmentMs = new Date(`${apptDate}T${args.startTime}:00`).getTime();
          const reminderMs = appointmentMs - reminderHours * 60 * 60 * 1000;
          if (reminderMs <= Date.now()) return;
          const reminderId = await ctx.db.insert("appointmentReminders", {
            organizationId: args.organizationId,
            appointmentId: apptId as any,
            type: "notification",
            scheduledFor: reminderMs,
            status: "pending",
            createdAt: now,
          });
          await ctx.scheduler.runAfter(
            reminderMs - Date.now(),
            internal.gabinet.appointmentReminders.sendReminder,
            { reminderId },
          );
        };

        await scheduleReminderFor(args.appointmentId, args.date);
        for (const recur of recurringAppointments) {
          await scheduleReminderFor(recur.appointmentId, recur.date);
        }
      } catch (e) {
        console.warn("Reminder scheduling failed (non-fatal):", e);
      }
    }

    return { scheduledActivityId, recurActivityIds };
  },
});

// ---------------------------------------------------------------------------
// PUBLIC create action — Supabase-primary write
// ---------------------------------------------------------------------------

export const create = action({
  args: {
    organizationId: v.id("organizations"),
    patientId: v.string(),
    treatmentId: v.string(),
    employeeId: v.string(),
    date: v.string(),
    startTime: v.string(),
    endTime: v.string(),
    notes: v.optional(v.string()),
    internalNotes: v.optional(v.string()),
    color: v.optional(v.string()),
    isRecurring: v.optional(v.boolean()),
    recurringRule: v.optional(
      v.object({
        frequency: v.string(),
        count: v.optional(v.number()),
        until: v.optional(v.string()),
      }),
    ),
    prepaymentRequired: v.optional(v.boolean()),
    prepaymentAmount: v.optional(v.number()),
    packageUsageId: v.optional(v.string()),
    sendReminder: v.optional(v.boolean()),
    locationId: v.optional(v.string()),
    roomId: v.optional(v.string()),
    tagIds: v.optional(v.array(v.string())),
    categoryId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // --- Auth + permissions (via internal queries) ---
    const authResult = await ctx.runQuery(
      internal._helpers.authAction.verifyOrgAccess,
      { organizationId: args.organizationId },
    );
    await ctx.runQuery(internal._helpers.authAction.checkPermission, {
      organizationId: args.organizationId,
      feature: "gabinet_appointments",
      action: "create",
    }).then((perm: { allowed: boolean; scope: string }) => {
      if (!perm.allowed) throw new Error("Permission denied");
    });

    const now = Date.now();
    const db = createSupabaseDb();

    // --- Org settings (reminder default) ---
    const orgSettings = await ctx.runQuery(
      internal.gabinet.appointments._getOrgSettings,
      { organizationId: args.organizationId },
    );
    const shouldSendReminder =
      args.sendReminder ?? (orgSettings as any)?.reminderEnabled ?? false;

    // --- Employee qualification check (Supabase-primary) ---
    const qualification = await checkEmployeeQualificationSupabase(db, {
      organizationId: String(args.organizationId),
      userId: args.employeeId,
      treatmentId: args.treatmentId,
    });
    if (!qualification.qualified) {
      throw new Error(qualification.reason ?? "Employee not qualified");
    }

    // --- Conflict check (Supabase-primary) ---
    const conflict = await checkConflictSupabase(db, {
      organizationId: String(args.organizationId),
      userId: args.employeeId,
      date: args.date,
      startTime: args.startTime,
      endTime: args.endTime,
      roomId: args.roomId ?? undefined,
    });
    if (conflict.hasConflict) {
      throw new Error(conflict.reason ?? "Time slot conflict");
    }

    // --- Resolve treatment + patient from Supabase ---
    const treatment = await db.get("gabinetTreatments", args.treatmentId);
    const patient = await db.get("gabinetPatients", args.patientId);

    const isRecurring = args.isRecurring ?? false;
    const recurringGroupId = isRecurring ? crypto.randomUUID() : undefined;

    // --- Auto-create package for multi-session treatments (Convex DB write) ---
    let resolvedPackageUsageId = args.packageUsageId ?? null;
    if (!resolvedPackageUsageId && treatment && ((treatment.treatmentCount as number) ?? 1) > 1) {
      resolvedPackageUsageId = await ctx.runMutation(
        internal.gabinet.appointments._resolveAutoPackageUsageMutation,
        {
          organizationId: args.organizationId,
          patientId: args.patientId as Id<"gabinetPatients">,
          treatmentId: args.treatmentId as Id<"gabinetTreatments">,
          userId: authResult.userId,
        },
      ) as string | null;
    }

    // --- Resolve location (Supabase-primary) ---
    let resolvedLocationId = args.locationId ?? null;
    if (!resolvedLocationId) {
      resolvedLocationId = await resolveAppointmentLocationSupabase(db, {
        organizationId: String(args.organizationId),
        userId: args.employeeId,
        date: args.date,
      });
    }

    const patientName = patient
      ? `${patient.firstName}${patient.lastName ? " " + (patient.lastName as string) : ""}`
      : "Patient";
    const treatmentName = (treatment?.name as string) ?? "Treatment";

    // --- INSERT first appointment directly to Supabase ---
    const baseRow: Record<string, unknown> = {
      organizationId: String(args.organizationId),
      patientId: args.patientId,
      treatmentId: args.treatmentId,
      employeeId: args.employeeId,
      startTime: args.startTime,
      endTime: args.endTime,
      status: "scheduled",
      notes: args.notes ?? null,
      internalNotes: args.internalNotes ?? null,
      color: args.color ?? null,
      isRecurring,
      recurringRule: args.recurringRule ?? null,
      recurringGroupId: recurringGroupId ?? null,
      prepaymentRequired: args.prepaymentRequired ?? null,
      prepaymentAmount: args.prepaymentAmount ?? null,
      prepaymentStatus: args.prepaymentRequired ? "pending" : null,
      packageUsageId: resolvedPackageUsageId ?? null,
      sendReminder: shouldSendReminder,
      locationId: resolvedLocationId ?? null,
      roomId: args.roomId ?? null,
      tagIds: args.tagIds ?? null,
      categoryId: args.categoryId ?? null,
      createdBy: String(authResult.userId),
      createdAt: now,
      updatedAt: now,
    };

    console.info("[create] inserting appointment to Supabase...");
    const firstId = await db.insert("gabinetAppointments", {
      ...baseRow,
      date: args.date,
      recurringIndex: isRecurring ? 0 : null,
    });
    console.info("[create] appointment inserted:", firstId);

    // --- INSERT recurring appointments to Supabase ---
    const recurringAppointments: Array<{ appointmentId: string; date: string; recurringIndex: number }> = [];
    if (isRecurring && args.recurringRule) {
      const dates = generateRecurringDates(args.date, args.recurringRule);
      for (let i = 0; i < dates.length; i++) {
        const recurId = await db.insert("gabinetAppointments", {
          ...baseRow,
          date: dates[i],
          recurringIndex: i + 1,
        });
        recurringAppointments.push({
          appointmentId: recurId,
          date: dates[i],
          recurringIndex: i + 1,
        });
      }
    }

    // --- Insert scheduledActivities directly to Supabase (primary) ---
    const dueDateMs = new Date(`${args.date}T${args.startTime}:00`).getTime();
    const endDateMs = new Date(`${args.date}T${args.endTime}:00`).getTime();
    const calendarTitle = `${treatmentName} — ${patientName}`;

    const scheduledActivityId = await db.insert("scheduledActivities", {
      organizationId: String(args.organizationId),
      title: calendarTitle,
      activityType: "gabinet:appointment",
      dueDate: dueDateMs,
      endDate: endDateMs,
      isCompleted: false,
      ownerId: String(authResult.userId),
      description: args.notes ?? null,
      linkedEntityType: "gabinetAppointment",
      linkedEntityId: firstId,
      moduleRef: {
        moduleId: "gabinet",
        entityType: "gabinetAppointment",
        entityId: firstId,
      },
      resourceId: args.employeeId,
      createdBy: String(authResult.userId),
      createdAt: now,
      updatedAt: now,
    });

    const recurActivityIds: Array<{ appointmentId: string; activityId: string }> = [];
    for (const recur of recurringAppointments) {
      const recurDueMs = new Date(`${recur.date}T${args.startTime}:00`).getTime();
      const recurEndMs = new Date(`${recur.date}T${args.endTime}:00`).getTime();
      const recurActivityId = await db.insert("scheduledActivities", {
        organizationId: String(args.organizationId),
        title: calendarTitle,
        activityType: "gabinet:appointment",
        dueDate: recurDueMs,
        endDate: recurEndMs,
        isCompleted: false,
        ownerId: String(authResult.userId),
        description: args.notes ?? null,
        linkedEntityType: "gabinetAppointment",
        linkedEntityId: recur.appointmentId,
        moduleRef: {
          moduleId: "gabinet",
          entityType: "gabinetAppointment",
          entityId: recur.appointmentId,
        },
        resourceId: args.employeeId,
        createdBy: String(authResult.userId),
        createdAt: now,
        updatedAt: now,
      });
      recurActivityIds.push({ appointmentId: recur.appointmentId, activityId: recurActivityId });
    }

    // --- Patch appointments with their scheduled_activity_id (UUIDs now satisfy Supabase FK) ---
    try {
      await db.patch("gabinetAppointments", firstId, { scheduledActivityId });
      for (const r of recurActivityIds) {
        await db.patch("gabinetAppointments", r.appointmentId, { scheduledActivityId: r.activityId });
      }
    } catch (e) {
      console.warn("[create] scheduled_activity_id patch failed (non-fatal):", e);
    }

    // --- Delegate Convex-only side effects (automation event, docs, reminders) ---
    try {
      await ctx.runMutation(
        internal.gabinet.appointments._createSideEffects,
        {
          appointmentId: firstId,
          organizationId: args.organizationId,
          patientId: args.patientId,
          treatmentId: args.treatmentId,
          employeeId: args.employeeId,
          date: args.date,
          startTime: args.startTime,
          endTime: args.endTime,
          notes: args.notes,
          status: "scheduled",
          isRecurring,
          recurringGroupId,
          sendReminder: shouldSendReminder,
          createdBy: String(authResult.userId),
          createdAt: now,
          patientName,
          treatmentName,
          patientEmail: (patient?.email as string) ?? undefined,
          patientPhone: (patient?.phone as string) ?? undefined,
          recurringAppointments: recurringAppointments.length > 0 ? recurringAppointments : undefined,
          packageUsageId: resolvedPackageUsageId ?? undefined,
          scheduledActivityId,
          recurActivityIds,
        },
      );
    } catch (e) {
      console.error("[create] Side effects FAILED for appointment", firstId, ":", e);
    }

    return firstId;
  },
});

export const update = action({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.string(),
    date: v.optional(v.string()),
    startTime: v.optional(v.string()),
    endTime: v.optional(v.string()),
    notes: v.optional(v.string()),
    internalNotes: v.optional(v.string()),
    color: v.optional(v.string()),
    employeeId: v.optional(v.string()),
    treatmentId: v.optional(v.string()),
    packageUsageId: v.optional(v.string()),
    status: v.optional(gabinetAppointmentStatusValidator),
    cancellationReason: v.optional(v.string()),
    bodyChartData: v.optional(v.string()),
    treatmentParameterValues: v.optional(v.string()),
    interviewNotes: v.optional(v.string()),
    clinicalRemarks: v.optional(v.string()),
    locationId: v.optional(v.string()),
    roomId: v.optional(v.string()),
    photos: v.optional(
      v.array(
        v.object({
          storageId: v.string(),
          type: v.union(v.literal("before"), v.literal("after")),
          caption: v.optional(v.string()),
          uploadedAt: v.number(),
        }),
      ),
    ),
    tagIds: v.optional(v.array(v.string())),
    categoryId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // --- Auth + permissions (via internal queries) ---
    const authResult = await ctx.runQuery(
      internal._helpers.authAction.verifyOrgAccess,
      { organizationId: args.organizationId },
    );
    const perm = await ctx.runQuery(
      internal._helpers.authAction.checkPermission,
      {
        organizationId: args.organizationId,
        feature: "gabinet_appointments",
        action: "edit",
      },
    ) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();

    // --- Read appointment from Supabase ---
    const appt = await db.get("gabinetAppointments", args.appointmentId);
    if (!appt || String(appt.organizationId) !== String(args.organizationId)) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && String(appt.createdBy) !== String(authResult.userId)) {
      throw new Error("Permission denied: you can only edit your own records");
    }

    // Check conflict if time changed
    const newDate = args.date ?? (appt.date as string);
    const newStart = args.startTime ?? (appt.startTime as string);
    const newEnd = args.endTime ?? (appt.endTime as string);
    const newEmployee = args.employeeId ?? (appt.employeeId as string);

    if (args.date || args.startTime || args.endTime || args.employeeId) {
      const conflict = await checkConflictSupabase(db, {
        organizationId: String(args.organizationId),
        userId: newEmployee,
        date: newDate,
        startTime: newStart,
        endTime: newEnd,
        excludeAppointmentId: args.appointmentId,
        roomId: args.roomId ?? (appt.roomId as string | undefined),
      });
      if (conflict.hasConflict) {
        throw new Error(conflict.reason ?? "Time slot conflict");
      }
    }

    const {
      organizationId,
      appointmentId,
      status,
      cancellationReason,
      ...updates
    } = args;

    const now = Date.now();
    const patch: Record<string, unknown> = {
      ...updates,
      updatedAt: now,
    };

    // Handle status change with cancellation support
    if (status) {
      const allowed = VALID_TRANSITIONS[appt.status as string];
      if (!allowed?.includes(status)) {
        throw new Error(`Cannot transition from ${appt.status} to ${status}`);
      }
      patch.status = status;

      if (status === "cancelled") {
        patch.cancelledAt = now;
        patch.cancelledBy = String(authResult.userId);
        if (cancellationReason) {
          patch.cancellationReason = cancellationReason;
        }
      }
    }

    // --- Write update directly to Supabase ---
    console.info("[update] patching appointment in Supabase:", appointmentId);
    await db.patch("gabinetAppointments", appointmentId, patch);

    // --- Sync scheduledActivity in Supabase (moved out of _updateSideEffects mutation) ---
    const scheduledActivityIdStr = (appt.scheduledActivityId as string) ?? undefined;
    const dateChanged = !!(args.date || args.startTime || args.endTime);
    const employeeChanged = !!args.employeeId;
    if (scheduledActivityIdStr) {
      try {
        const actPatch: Record<string, unknown> = { updatedAt: now };
        if (dateChanged) {
          actPatch.dueDate = new Date(`${newDate}T${newStart}:00`).getTime();
          actPatch.endDate = new Date(`${newDate}T${newEnd}:00`).getTime();
        }
        if (employeeChanged) {
          actPatch.resourceId = newEmployee;
        }
        if (Object.keys(actPatch).length > 1) {
          await db.patch("scheduledActivities", scheduledActivityIdStr, actPatch);
        }
      } catch (e) {
        console.warn("[update] scheduledActivity patch failed (non-fatal):", e);
      }
    }

    // --- Side effects (Convex-only: activity log, automation event) ---
    try {
      await ctx.runMutation(
        internal.gabinet.appointments._updateSideEffects,
        {
          appointmentId,
          organizationId,
          actorUserId: authResult.userId,
          // Previous values for diffing
          previousStatus: appt.status as string,
          previousDate: appt.date as string,
          previousStartTime: appt.startTime as string,
          previousEndTime: appt.endTime as string,
          previousEmployeeId: appt.employeeId as string,
          scheduledActivityId: (appt.scheduledActivityId as string) ?? undefined,
          patientId: appt.patientId as string,
          treatmentId: String(args.treatmentId ?? appt.treatmentId),
          createdBy: appt.createdBy as string,
          // New values
          newDate: newDate,
          newStartTime: newStart,
          newEndTime: newEnd,
          newEmployeeId: newEmployee,
          newStatus: status ?? (appt.status as string),
          dateChanged: !!(args.date || args.startTime || args.endTime),
          employeeChanged: !!args.employeeId,
          updatedFields: Object.keys(updates),
          updatedAt: now,
        },
      );
    } catch (e) {
      console.error("[update] Side effects FAILED for appointment", appointmentId, ":", e);
    }

    return appointmentId;
  },
});

export const _updateSideEffects = internalMutation({
  args: {
    appointmentId: v.string(),
    organizationId: v.id("organizations"),
    actorUserId: v.string(),
    previousStatus: v.string(),
    previousDate: v.string(),
    previousStartTime: v.string(),
    previousEndTime: v.string(),
    previousEmployeeId: v.string(),
    scheduledActivityId: v.optional(v.string()),
    patientId: v.string(),
    treatmentId: v.string(),
    createdBy: v.string(),
    newDate: v.string(),
    newStartTime: v.string(),
    newEndTime: v.string(),
    newEmployeeId: v.string(),
    newStatus: v.string(),
    dateChanged: v.boolean(),
    employeeChanged: v.boolean(),
    updatedFields: v.array(v.string()),
    updatedAt: v.number(),
  },
  handler: async (ctx, args) => {
    const actorUserId = args.actorUserId as Id<"users">;

    // scheduledActivity patches moved to the parent action (Supabase-primary).

    await logActivity(ctx, {
      organizationId: args.organizationId,
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
      action: "updated",
      description: `Updated appointment`,
      performedBy: actorUserId,
    });

    await emitAutomationEvent(ctx, {
      organizationId: args.organizationId,
      module: "gabinet",
      eventType: args.dateChanged
        ? "gabinet.appointment.rescheduled"
        : "gabinet.appointment.updated",
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
      actorUserId,
      correlationKey: `appointment:${args.appointmentId}`,
      eventIdempotencyKey: `automation-event:${args.organizationId}:${args.appointmentId}:${args.updatedAt}:${args.dateChanged ? "rescheduled" : "updated"}`,
      payload: {
        organizationId: String(args.organizationId),
        appointmentId: args.appointmentId,
        patientId: args.patientId,
        treatmentId: args.treatmentId,
        employeeId: args.newEmployeeId,
        date: args.newDate,
        startTime: args.newStartTime,
        endTime: args.newEndTime,
        previousStatus: args.previousStatus,
        status: args.newStatus,
        createdBy: args.createdBy,
        updatedFields: args.updatedFields,
      },
    });
  },
});

export const updateStatus = action({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.string(),
    status: gabinetAppointmentStatusValidator,
    forceSkipDocumentGate: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    // --- Auth + permissions (via internal queries) ---
    const authResult = await ctx.runQuery(
      internal._helpers.authAction.verifyOrgAccess,
      { organizationId: args.organizationId },
    );
    const perm = await ctx.runQuery(
      internal._helpers.authAction.checkPermission,
      {
        organizationId: args.organizationId,
        feature: "gabinet_appointments",
        action: "edit",
      },
    ) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();

    // --- Read appointment from Supabase ---
    const appt = await db.get("gabinetAppointments", args.appointmentId);
    if (!appt || String(appt.organizationId) !== String(args.organizationId)) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && String(appt.createdBy) !== String(authResult.userId)) {
      throw new Error("Permission denied: you can only edit your own records");
    }

    const allowed = VALID_TRANSITIONS[appt.status as string];
    if (!allowed?.includes(args.status)) {
      throw new Error(
        `Cannot transition from ${appt.status} to ${args.status}`,
      );
    }

    // Document gate: check required documents before status transitions
    if (!args.forceSkipDocumentGate) {
      if (args.status === "in_progress") {
        const gate = await ctx.runQuery(
          internal.gabinet.appointments._checkDocumentGateQuery,
          { appointmentId: args.appointmentId, timing: "before_start" },
        ) as { canProceed: boolean; missing: Array<{ title: string }> };
        if (!gate.canProceed) {
          const missingNames = gate.missing.map((d) => d.title).join(", ");
          throw new Error(
            `DOCUMENT_GATE:before_start:${JSON.stringify(gate)}|Nie można rozpocząć wizyty — brakuje wymaganych dokumentów: ${missingNames}`,
          );
        }
      }
    }

    // --- Write status change directly to Supabase ---
    const now = Date.now();
    const patch: Record<string, unknown> = {
      status: args.status,
      updatedAt: now,
    };
    if (args.status === "cancelled") {
      patch.cancelledAt = now;
      patch.cancelledBy = String(authResult.userId);
    }
    console.info("[updateStatus] patching status in Supabase:", args.appointmentId, "->", args.status);
    await db.patch("gabinetAppointments", args.appointmentId, patch);

    // --- Sync terminal status to linked scheduledActivity in Supabase ---
    const scheduledActivityIdStr = (appt.scheduledActivityId as string) ?? undefined;
    if (scheduledActivityIdStr) {
      try {
        const actPatch: Record<string, unknown> = { updatedAt: now };
        if (
          args.status === "completed" ||
          args.status === "cancelled" ||
          args.status === "no_show"
        ) {
          actPatch.isCompleted = true;
          actPatch.completedAt = now;
        }
        await db.patch("scheduledActivities", scheduledActivityIdStr, actPatch);
      } catch (e) {
        console.warn("[updateStatus] scheduledActivity patch failed (non-fatal):", e);
      }
    }

    // --- Side effects (Convex-only: status change cascade, auto-doc gen) ---
    try {
      await ctx.runMutation(
        internal.gabinet.appointments._updateStatusSideEffects,
        {
          appointmentId: args.appointmentId,
          organizationId: args.organizationId,
          actorUserId: authResult.userId,
          previousStatus: appt.status as string,
          nextStatus: args.status,
          scheduledActivityId: (appt.scheduledActivityId as string) ?? undefined,
          patientId: appt.patientId as string,
          treatmentId: (appt.treatmentId as string) ?? undefined,
          employeeId: appt.employeeId as string,
          createdBy: appt.createdBy as string,
          date: appt.date as string,
          startTime: appt.startTime as string,
          packageUsageId: (appt.packageUsageId as string) ?? undefined,
          patientEmail: (appt as any).patientEmail ?? undefined,
          patientPhone: (appt as any).patientPhone ?? undefined,
        },
      );
    } catch (e) {
      console.error("[updateStatus] Side effects FAILED for appointment", args.appointmentId, ":", e);
    }

    return args.appointmentId;
  },
});

export const _updateStatusSideEffects = internalMutation({
  args: {
    appointmentId: v.string(),
    organizationId: v.id("organizations"),
    actorUserId: v.string(),
    previousStatus: v.string(),
    nextStatus: v.string(),
    scheduledActivityId: v.optional(v.string()),
    patientId: v.string(),
    treatmentId: v.optional(v.string()),
    employeeId: v.string(),
    createdBy: v.string(),
    date: v.string(),
    startTime: v.string(),
    packageUsageId: v.optional(v.string()),
    patientEmail: v.optional(v.string()),
    patientPhone: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = args.actorUserId as Id<"users">;

    // Build a pseudo-appointment Doc for applyAppointmentStatusChange helper
    // We need to read the Convex appointment record for the side-effect helpers
    // that require a Doc<"gabinetAppointments"> shape. Since the canonical data
    // is now in Supabase, we construct a minimal proxy object.
    const appointmentProxy = {
      _id: args.appointmentId as Id<"gabinetAppointments">,
      _creationTime: 0,
      organizationId: args.organizationId,
      status: args.previousStatus,
      scheduledActivityId: args.scheduledActivityId
        ? (args.scheduledActivityId as Id<"scheduledActivities">)
        : undefined,
      patientId: args.patientId as Id<"gabinetPatients">,
      treatmentId: args.treatmentId
        ? (args.treatmentId as Id<"gabinetTreatments">)
        : undefined,
      employeeId: args.employeeId as Id<"users">,
      createdBy: args.createdBy as Id<"users">,
      date: args.date,
      startTime: args.startTime,
      packageUsageId: args.packageUsageId
        ? (args.packageUsageId as Id<"gabinetPackageUsage">)
        : undefined,
    } as unknown as Doc<"gabinetAppointments">;

    // The status patch was already written to Supabase by the action.
    // applyAppointmentStatusChange will try to ctx.db.patch the Convex record —
    // since we're doing Supabase-primary, that patch may be a no-op on
    // a missing Convex row. We still call it for the side effects (activity log,
    // audit, notification, automation event, calendar sync, completion handlers).
    await applyAppointmentStatusChange(ctx, {
      appointment: appointmentProxy,
      organizationId: args.organizationId,
      nextStatus: args.nextStatus as Doc<"gabinetAppointments">["status"],
      actorUserId,
      auditAction: "status_changed",
      auditDetails: JSON.stringify({
        oldStatus: args.previousStatus,
        newStatus: args.nextStatus,
      }),
      activityDescription: `Status changed from ${args.previousStatus} to ${args.nextStatus}`,
      notificationTitle: "Appointment status changed",
      notificationMessage: `Appointment status changed to "${args.nextStatus}"`,
    });

    // After completing: auto-generate "after_completion" documents
    if (args.nextStatus === "completed" && args.treatmentId) {
      await autoGenerateAppointmentDocuments(ctx, {
        organizationId: args.organizationId,
        appointmentId: args.appointmentId as Id<"gabinetAppointments">,
        treatmentId: args.treatmentId as Id<"gabinetTreatments">,
        patientId: args.patientId as Id<"gabinetPatients">,
        createdBy: actorUserId,
        timing: "after_completion",
        deferEmails: true,
      });
    }
  },
});

export const getDocumentGateStatus = query({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
    timing: v.union(v.literal("before_start"), v.literal("after_completion")),
  },
  handler: async (ctx, args) => {
    await verifyOrgAccess(ctx, args.organizationId);
    await verifyProductAccess(ctx, args.organizationId, GABINET_PRODUCT_ID);

    const appt = await ctx.db.get(args.appointmentId);
    if (!appt || appt.organizationId !== args.organizationId) {
      throw new Error("Appointment not found");
    }

    return await checkDocumentGate(ctx, args.appointmentId, args.timing);
  },
});

export const applySmsReplyTransition = internalMutation({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.string(),
    intent: v.union(v.literal("confirm"), v.literal("cancel")),
    smsEventId: v.string(),
  },
  handler: async (ctx, args) => {
    const db = createSupabaseDb();

    // --- Read appointment from Supabase (primary) ---
    const appointment = await db.get("gabinetAppointments", args.appointmentId);
    if (!appointment || String(appointment.organizationId) !== String(args.organizationId)) {
      return {
        processingStatus: "ignored" as const,
        reason: "Appointment not found",
      };
    }

    const targetStatus = getSmsTargetStatus(args.intent);
    const allowed = VALID_TRANSITIONS[appointment.status as string];
    if (!allowed?.includes(targetStatus)) {
      return {
        processingStatus: "ignored" as const,
        reason: `Cannot transition from ${appointment.status} to ${targetStatus}`,
      };
    }

    // --- Write status change directly to Supabase ---
    const now = Date.now();
    const supabasePatch: Record<string, unknown> = {
      status: targetStatus,
      updatedAt: now,
    };
    if (targetStatus === "cancelled") {
      supabasePatch.cancelledAt = now;
      supabasePatch.cancelledBy = String(appointment.employeeId);
      supabasePatch.cancellationReason = "Cancelled by patient SMS reply";
    }
    await db.patch("gabinetAppointments", args.appointmentId, supabasePatch);

    // --- Side effects (activity log, audit, notifications, automation) ---
    const appointmentProxy = {
      _id: args.appointmentId as Id<"gabinetAppointments">,
      _creationTime: 0,
      organizationId: args.organizationId,
      status: appointment.status as string,
      scheduledActivityId: appointment.scheduledActivityId
        ? (appointment.scheduledActivityId as Id<"scheduledActivities">)
        : undefined,
      patientId: appointment.patientId as Id<"gabinetPatients">,
      treatmentId: appointment.treatmentId
        ? (appointment.treatmentId as Id<"gabinetTreatments">)
        : undefined,
      employeeId: appointment.employeeId as Id<"users">,
      createdBy: appointment.createdBy as Id<"users">,
      date: appointment.date as string,
      startTime: appointment.startTime as string,
      packageUsageId: appointment.packageUsageId
        ? (appointment.packageUsageId as Id<"gabinetPackageUsage">)
        : undefined,
    } as unknown as Doc<"gabinetAppointments">;

    await applyAppointmentStatusChange(ctx, {
      appointment: appointmentProxy,
      organizationId: args.organizationId,
      nextStatus: targetStatus,
      actorUserId: appointment.employeeId as Id<"users">,
      auditAction: "status_changed_via_sms",
      auditDetails: JSON.stringify({
        oldStatus: appointment.status,
        newStatus: targetStatus,
        intent: args.intent,
        source: "sms_reply",
        smsEventId: args.smsEventId,
      }),
      activityDescription:
        args.intent === "confirm"
          ? "Appointment confirmed via SMS reply"
          : "Appointment cancelled via SMS reply",
      notificationTitle:
        args.intent === "confirm"
          ? "Appointment confirmed via SMS"
          : "Appointment cancelled via SMS",
      notificationMessage:
        args.intent === "confirm"
          ? 'Appointment status changed to "confirmed" from patient SMS reply'
          : 'Appointment status changed to "cancelled" from patient SMS reply',
      cancellationReason:
        args.intent === "cancel" ? "Cancelled by patient SMS reply" : undefined,
    });

    return {
      processingStatus: "processed" as const,
      reason: undefined,
    };
  },
});

export const cancel = action({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.string(),
    reason: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // --- Auth + permissions (via internal queries) ---
    const authResult = await ctx.runQuery(
      internal._helpers.authAction.verifyOrgAccess,
      { organizationId: args.organizationId },
    );
    const perm = await ctx.runQuery(
      internal._helpers.authAction.checkPermission,
      {
        organizationId: args.organizationId,
        feature: "gabinet_appointments",
        action: "delete",
      },
    ) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();

    // --- Read appointment from Supabase ---
    const appt = await db.get("gabinetAppointments", args.appointmentId);
    if (!appt || String(appt.organizationId) !== String(args.organizationId)) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && String(appt.createdBy) !== String(authResult.userId)) {
      throw new Error(
        "Permission denied: you can only delete your own records",
      );
    }

    if (appt.status === "cancelled" || appt.status === "completed") {
      throw new Error(`Cannot cancel a ${appt.status} appointment`);
    }

    // --- Write cancellation directly to Supabase ---
    const now = Date.now();
    console.info("[cancel] cancelling appointment in Supabase:", args.appointmentId);
    await db.patch("gabinetAppointments", args.appointmentId, {
      status: "cancelled",
      cancelledAt: now,
      cancelledBy: String(authResult.userId),
      cancellationReason: args.reason ?? null,
      updatedAt: now,
    });

    // --- Mark linked scheduledActivity complete in Supabase ---
    const scheduledActivityIdStr = (appt.scheduledActivityId as string) ?? undefined;
    if (scheduledActivityIdStr) {
      try {
        await db.patch("scheduledActivities", scheduledActivityIdStr, {
          isCompleted: true,
          completedAt: now,
          updatedAt: now,
        });
      } catch (e) {
        console.warn("[cancel] scheduledActivity patch failed (non-fatal):", e);
      }
    }

    // --- Side effects (Convex-only) ---
    try {
      await ctx.runMutation(
        internal.gabinet.appointments._cancelSideEffects,
        {
          appointmentId: args.appointmentId,
          organizationId: args.organizationId,
          actorUserId: authResult.userId,
          reason: args.reason,
          scheduledActivityId: (appt.scheduledActivityId as string) ?? undefined,
          createdBy: appt.createdBy as string,
          employeeId: appt.employeeId as string,
          patientId: appt.patientId as string,
          treatmentId: (appt.treatmentId as string) ?? undefined,
          date: appt.date as string,
          startTime: appt.startTime as string,
          previousStatus: appt.status as string,
          packageUsageId: (appt.packageUsageId as string) ?? undefined,
        },
      );
    } catch (e) {
      console.error("[cancel] Side effects FAILED for appointment", args.appointmentId, ":", e);
    }
  },
});

export const _cancelSideEffects = internalMutation({
  args: {
    appointmentId: v.string(),
    organizationId: v.id("organizations"),
    actorUserId: v.string(),
    reason: v.optional(v.string()),
    scheduledActivityId: v.optional(v.string()),
    createdBy: v.string(),
    employeeId: v.string(),
    patientId: v.string(),
    treatmentId: v.optional(v.string()),
    date: v.string(),
    startTime: v.string(),
    previousStatus: v.string(),
    packageUsageId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = args.actorUserId as Id<"users">;
    const appointmentId = args.appointmentId as Id<"gabinetAppointments">;

    // scheduledActivity patched in Supabase by the parent action.

    // Cancel pending reminders
    await ctx.scheduler.runAfter(
      0,
      internal.gabinet.appointmentReminders.cancelRemindersInternal,
      { appointmentId: appointmentId },
    );

    await logActivity(ctx, {
      organizationId: args.organizationId,
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
      action: "status_changed",
      description: `Cancelled appointment${args.reason ? `: ${args.reason}` : ""}`,
      performedBy: actorUserId,
    });

    await logAudit(ctx, {
      organizationId: args.organizationId,
      userId: actorUserId,
      action: "entity_cancelled",
      entityType: "gabinetAppointment",
      entityId: appointmentId,
    });

    // Notify appointment creator and employee about cancellation
    const createdBy = args.createdBy as Id<"users">;
    const employeeId = args.employeeId as Id<"users">;

    if (createdBy !== actorUserId) {
      await createNotificationDirect(ctx, {
        organizationId: args.organizationId,
        userId: createdBy,
        type: "appointment_status_changed",
        title: "Appointment cancelled",
        message: `An appointment has been cancelled${args.reason ? `: ${args.reason}` : ""}`,
      });
    }
    if (employeeId !== actorUserId && employeeId !== createdBy) {
      await createNotificationDirect(ctx, {
        organizationId: args.organizationId,
        userId: employeeId,
        type: "appointment_status_changed",
        title: "Appointment cancelled",
        message: `An appointment has been cancelled${args.reason ? `: ${args.reason}` : ""}`,
      });
    }

    // Emit automation event
    const now = Date.now();
    await emitAutomationEvent(ctx, {
      organizationId: args.organizationId,
      module: "gabinet",
      eventType: "gabinet.appointment.cancelled",
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
      actorUserId,
      correlationKey: `appointment:${args.appointmentId}`,
      eventIdempotencyKey: `automation-event:${args.organizationId}:${args.appointmentId}:cancelled:${now}`,
      payload: {
        organizationId: String(args.organizationId),
        appointmentId: args.appointmentId,
        patientId: args.patientId,
        employeeId: args.employeeId,
        treatmentId: args.treatmentId ?? "",
        status: "cancelled",
        previousStatus: args.previousStatus,
        date: args.date,
        startTime: args.startTime,
        cancellationReason: args.reason,
        createdBy: args.createdBy,
      },
    });
  },
});

/**
 * For treatments with treatmentCount > 1, auto-create a package template
 * and patient usage record on first booking.
 */
async function resolveAutoPackageUsage(
  ctx: MutationCtx,
  args: {
    organizationId: Id<"organizations">;
    patientId: Id<"gabinetPatients">;
    treatmentId: Id<"gabinetTreatments">;
    treatment: Doc<"gabinetTreatments">;
    userId: Id<"users">;
  },
): Promise<Id<"gabinetPackageUsage"> | undefined> {
  const treatmentCount = args.treatment.treatmentCount;
  if (!treatmentCount || treatmentCount <= 1) return undefined;

  const now = Date.now();

  // 1. Find or create auto-generated package template for this treatment
  let autoPackage = await ctx.db
    .query("gabinetTreatmentPackages")
    .withIndex("by_orgAndAutoTreatment", (q) =>
      q
        .eq("organizationId", args.organizationId)
        .eq("autoGeneratedForTreatmentId", args.treatmentId),
    )
    .first();

  if (!autoPackage) {
    const packageId = await ctx.db.insert("gabinetTreatmentPackages", {
      organizationId: args.organizationId,
      name: `${args.treatment.name} (${treatmentCount}x)`,
      treatments: [{ treatmentId: args.treatmentId, quantity: treatmentCount }],
      totalPrice: args.treatment.price * treatmentCount,
      currency: args.treatment.currency,
      isActive: true,
      autoGeneratedForTreatmentId: args.treatmentId,
      createdBy: args.userId,
      createdAt: now,
      updatedAt: now,
    });
    autoPackage = (await ctx.db.get(packageId))!;
  }

  // 2. Find existing active usage for this patient + package
  const existingUsage = await ctx.db
    .query("gabinetPackageUsage")
    .withIndex("by_orgPatientAndPackage", (q) =>
      q
        .eq("organizationId", args.organizationId)
        .eq("patientId", args.patientId)
        .eq("packageId", autoPackage!._id),
    )
    .filter((q) => q.eq(q.field("status"), "active"))
    .first();

  if (existingUsage) {
    return existingUsage._id;
  }

  // 3. Create new usage record
  const usageId = await ctx.db.insert("gabinetPackageUsage", {
    organizationId: args.organizationId,
    patientId: args.patientId,
    packageId: autoPackage._id,
    purchasedAt: now,
    status: "active",
    treatmentsUsed: [
      {
        treatmentId: args.treatmentId,
        usedCount: 0,
        totalCount: treatmentCount,
      },
    ],
    paidAmount: 0,
    createdBy: args.userId,
    createdAt: now,
    updatedAt: now,
  });

  return usageId;
}

/**
 * When an appointment is completed, award loyalty points based on
 * treatment price and deduct from linked package if applicable.
 */
async function handleAppointmentCompletion(
  ctx: any,
  args: {
    organizationId: Id<"organizations">;
    appointmentId: Id<"gabinetAppointments">;
    patientId: Id<"gabinetPatients">;
    treatmentId: Id<"gabinetTreatments">;
    packageUsageId?: Id<"gabinetPackageUsage">;
    userId: Id<"users">;
  },
) {
  const now = Date.now();
  const treatment = await ctx.db.get(args.treatmentId);

  // 1. Deduct from package if linked
  if (args.packageUsageId) {
    const usage = await ctx.db.get(args.packageUsageId);
    if (usage && usage.status === "active") {
      const entry = usage.treatmentsUsed.find(
        (t: any) => t.treatmentId === args.treatmentId,
      );
      if (entry && entry.usedCount < entry.totalCount) {
        const updatedTreatments = usage.treatmentsUsed.map((t: any) =>
          t.treatmentId === args.treatmentId
            ? { ...t, usedCount: t.usedCount + 1 }
            : t,
        );
        const allUsed = updatedTreatments.every(
          (t: any) => t.usedCount >= t.totalCount,
        );
        await ctx.db.patch(args.packageUsageId, {
          treatmentsUsed: updatedTreatments,
          status: allUsed ? "completed" : "active",
          updatedAt: now,
        });
      }
    }
  }

  // 2. Award loyalty points (1 point per PLN of treatment price)
  if (treatment && treatment.price > 0) {
    const points = Math.floor(treatment.price);
    if (points > 0) {
      const loyalty = await ctx.db
        .query("gabinetLoyaltyPoints")
        .withIndex("by_orgAndPatient", (q: any) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("patientId", args.patientId),
        )
        .first();

      const newBalance = (loyalty?.balance ?? 0) + points;
      const newLifetimeEarned = (loyalty?.lifetimeEarned ?? 0) + points;

      if (loyalty) {
        await ctx.db.patch(loyalty._id, {
          balance: newBalance,
          lifetimeEarned: newLifetimeEarned,
          updatedAt: now,
        });
      } else {
        await ctx.db.insert("gabinetLoyaltyPoints", {
          organizationId: args.organizationId,
          patientId: args.patientId,
          balance: newBalance,
          lifetimeEarned: newLifetimeEarned,
          lifetimeSpent: 0,
          createdAt: now,
          updatedAt: now,
        });
      }

      await ctx.db.insert("gabinetLoyaltyTransactions", {
        organizationId: args.organizationId,
        patientId: args.patientId,
        type: "earn",
        points,
        reason: `Appointment completed: ${treatment.name}`,
        referenceType: "appointment",
        referenceId: args.appointmentId,
        balanceAfter: newBalance,
        createdBy: args.userId,
        createdAt: now,
      });
    }
  }

  // 3. Create pending payment (if not covered by package)
  if (!args.packageUsageId && treatment && treatment.price > 0) {
    await ctx.db.insert("payments", {
      organizationId: args.organizationId,
      patientId: args.patientId,
      appointmentId: args.appointmentId,
      amount: treatment.price,
      currency: "PLN",
      paymentMethod: "cash",
      status: "pending",
      createdBy: args.userId,
      createdAt: now,
      updatedAt: now,
    });
  }
}

export const cancelRecurringSeries = action({
  args: {
    organizationId: v.id("organizations"),
    recurringGroupId: v.string(),
    fromDate: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // --- Auth + permissions (via internal queries) ---
    const authResult = await ctx.runQuery(
      internal._helpers.authAction.verifyOrgAccess,
      { organizationId: args.organizationId },
    );
    const perm = await ctx.runQuery(
      internal._helpers.authAction.checkPermission,
      {
        organizationId: args.organizationId,
        feature: "gabinet_appointments",
        action: "delete",
      },
    ) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();

    // --- Read all appointments in the recurring group from Supabase ---
    const appointments = await db.query("gabinetAppointments")
      .eq("organizationId", String(args.organizationId))
      .eq("recurringGroupId", args.recurringGroupId)
      .collect();

    const now = Date.now();
    let count = 0;
    for (const appt of appointments) {
      if (appt.status === "cancelled" || appt.status === "completed") continue;
      if (args.fromDate && (appt.date as string) < args.fromDate) continue;

      // Cancel directly in Supabase
      await db.patch("gabinetAppointments", appt._id as string, {
        status: "cancelled",
        cancelledAt: now,
        cancelledBy: String(authResult.userId),
        cancellationReason: "Series cancelled",
        updatedAt: now,
      });

      count++;
    }

    return { cancelled: count };
  },
});

export const getFullDetail = action({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.string(),
  },
  handler: async (ctx, args) => {
    const authResult = await ctx.runQuery(
      internal._helpers.authAction.verifyOrgAccess,
      { organizationId: args.organizationId },
    );
    const perm = await ctx.runQuery(internal._helpers.authAction.checkPermission, {
      organizationId: args.organizationId,
      feature: "gabinet_appointments",
      action: "view",
    }) as { allowed: boolean; scope: string };
    if (!perm.allowed) throw new Error("Permission denied");

    const db = createSupabaseDb();
    const orgIdStr = String(args.organizationId);

    const appointment = await db.get("gabinetAppointments", args.appointmentId);
    if (!appointment || String(appointment.organizationId) !== orgIdStr) {
      throw new Error("Appointment not found");
    }
    if (
      perm.scope === "own" &&
      String(appointment.createdBy) !== String(authResult.userId)
    ) {
      throw new Error("Permission denied: you can only view your own records");
    }

    const patientId = String(appointment.patientId);
    const treatmentId = appointment.treatmentId
      ? String(appointment.treatmentId)
      : null;
    const employeeId = String(appointment.employeeId);

    const [
      patient,
      treatment,
      employee,
      documents,
      payments,
      notes,
      patientPackageUsage,
      patientHistoryRaw,
      loyaltyBalanceRow,
      loyaltyTransactions,
      allPatientPayments,
      workflowHistory,
    ] = await Promise.all([
      db.get("gabinetPatients", patientId),
      treatmentId ? db.get("gabinetTreatments", treatmentId) : Promise.resolve(null),
      db.get("gabinetEmployees", employeeId),
      db.query("formDocuments")
        .eq("entityType", "gabinetAppointment")
        .eq("entityId", args.appointmentId)
        .collect(),
      db.query("payments")
        .eq("appointmentId", args.appointmentId)
        .collect(),
      db.query("notes")
        .eq("entityType", "gabinetAppointment")
        .eq("entityId", args.appointmentId)
        .order("createdAt", false)
        .take(50)
        .collect(),
      db.query("gabinetPackageUsage")
        .eq("organizationId", orgIdStr)
        .eq("patientId", patientId)
        .collect(),
      db.query("gabinetAppointments")
        .eq("organizationId", orgIdStr)
        .eq("patientId", patientId)
        .order("createdAt", false)
        .take(21)
        .collect(),
      db.query("gabinetLoyaltyPoints")
        .eq("organizationId", orgIdStr)
        .eq("patientId", patientId)
        .first(),
      db.query("gabinetLoyaltyTransactions")
        .eq("organizationId", orgIdStr)
        .eq("patientId", patientId)
        .order("createdAt", false)
        .take(10)
        .collect(),
      db.query("payments")
        .eq("organizationId", orgIdStr)
        .eq("patientId", patientId)
        .order("createdAt", false)
        .take(50)
        .collect(),
      db.query("appointmentWorkflowHistory")
        .eq("appointmentId", args.appointmentId)
        .order("createdAt", false)
        .collect(),
    ]);

    const patientHistory = patientHistoryRaw
      .filter((a) => String(a._id) !== args.appointmentId)
      .slice(0, 20);

    // Enrich history appointments with treatment name
    const historyTreatmentIds = Array.from(
      new Set(
        patientHistory
          .map((a) => (a.treatmentId ? String(a.treatmentId) : null))
          .filter((id): id is string => id !== null),
      ),
    );
    const historyTreatments = await Promise.all(
      historyTreatmentIds.map((id) => db.get("gabinetTreatments", id)),
    );
    const treatmentMap = new Map(
      historyTreatments
        .filter((t): t is Record<string, unknown> => t !== null)
        .map((t) => [String(t._id), t]),
    );

    // Enrich package usage
    const pkgUsagePkgIds = Array.from(
      new Set(
        patientPackageUsage
          .map((u) => (u.packageId ? String(u.packageId) : null))
          .filter((id): id is string => id !== null),
      ),
    );
    const pkgUsageTreatmentIds = Array.from(
      new Set(
        patientPackageUsage.flatMap((u) =>
          ((u.treatmentsUsed as Array<{ treatmentId: string }>) ?? []).map((t) =>
            String(t.treatmentId),
          ),
        ),
      ),
    );
    const [pkgDefs, pkgTreatmentDefs] = await Promise.all([
      Promise.all(pkgUsagePkgIds.map((id) => db.get("gabinetTreatmentPackages", id))),
      Promise.all(pkgUsageTreatmentIds.map((id) => db.get("gabinetTreatments", id))),
    ]);
    const pkgDefMap = new Map(
      pkgDefs
        .filter((p): p is Record<string, unknown> => p !== null)
        .map((p) => [String(p._id), p]),
    );
    const pkgTreatmentMap = new Map(
      pkgTreatmentDefs
        .filter((t): t is Record<string, unknown> => t !== null)
        .map((t) => [String(t._id), t]),
    );

    const enrichedPatientPackageUsage = patientPackageUsage.map((u) => {
      const pkgDef = pkgDefMap.get(String(u.packageId));
      const treatmentsUsedArr =
        (u.treatmentsUsed as Array<{
          treatmentId: string;
          usedCount: number;
          totalCount: number;
        }>) ?? [];
      const enrichedTreatments = treatmentsUsedArr.map((t) => ({
        ...t,
        treatmentName:
          (pkgTreatmentMap.get(String(t.treatmentId))?.name as string | null) ?? null,
      }));
      const totalUsed = enrichedTreatments.reduce((s, t) => s + (t.usedCount ?? 0), 0);
      const totalCount = enrichedTreatments.reduce((s, t) => s + (t.totalCount ?? 0), 0);
      return {
        ...u,
        packageName: (pkgDef?.name as string | null) ?? null,
        treatmentsUsed: enrichedTreatments,
        totalUsed,
        totalCount,
        progressPercent: totalCount > 0 ? Math.round((totalUsed / totalCount) * 100) : 0,
      };
    });

    // Enrich notes with author names
    const noteAuthorIds = Array.from(
      new Set(
        notes
          .map((n) => (n.createdBy ? String(n.createdBy) : null))
          .filter((id): id is string => id !== null),
      ),
    );
    const noteAuthors = await Promise.all(
      noteAuthorIds.map((id) => db.get("users", id).catch(() => null)),
    );
    const noteAuthorMap = new Map(
      noteAuthors
        .filter((u): u is Record<string, unknown> => u !== null)
        .map((u) => [String(u._id), (u.name as string | null) ?? (u.email as string | null)]),
    );
    const enrichedNotes = notes.map((n) => ({
      ...n,
      authorName: noteAuthorMap.get(String(n.createdBy)) ?? null,
    }));

    return {
      appointment,
      patient,
      treatment,
      employee,
      documents,
      payments,
      notes: enrichedNotes,
      patientPackageUsage: enrichedPatientPackageUsage,
      patientHistory: patientHistory.map((a) => ({
        ...a,
        treatment: a.treatmentId ? treatmentMap.get(String(a.treatmentId)) : undefined,
      })),
      loyaltyBalance: (loyaltyBalanceRow?.balance as number | null) ?? 0,
      loyaltyTier: (loyaltyBalanceRow?.tier as string | null) ?? null,
      loyaltyTransactions,
      allPatientPayments,
      workflowHistory,
    };
  },
});

export const getPhotoUrls = query({
  args: {
    organizationId: v.id("organizations"),
    storageIds: v.array(v.id("_storage")),
  },
  handler: async (ctx, args) => {
    await verifyOrgAccess(ctx, args.organizationId);
    return Promise.all(
      args.storageIds.map((id) => ctx.storage.getUrl(id)),
    );
  },
});
