import { query, mutation, internalMutation, MutationCtx } from "../_generated/server";
import { internal } from "../_generated/api";
import { v } from "convex/values";
import { paginationOptsValidator } from "convex/server";
import { verifyOrgAccess } from "../_helpers/auth";
import { checkPermission } from "../_helpers/permissions";
import { verifyProductAccess } from "../_helpers/products";
import { logActivity } from "../_helpers/activities";
import { GABINET_PRODUCT_ID } from "./_registry";
import { gabinetAppointmentStatusValidator } from "../schema";
import {
  checkConflict,
  getAvailableSlots,
  checkEmployeeQualification,
  resolveAppointmentLocation,
} from "./_availability";
import { Id, Doc } from "../_generated/dataModel";
import { logAudit } from "../auditLog";
import { createNotificationDirect } from "../notifications";
import { autoGenerateAppointmentDocuments } from "./_helpers/autoGenerateDocuments";
import { checkDocumentGate } from "./_helpers/documentGate";

const VALID_TRANSITIONS: Record<string, string[]> = {
  pending_confirmation: ["scheduled", "confirmed", "cancelled"],
  scheduled: ["confirmed", "cancelled", "no_show"],
  confirmed: ["in_progress", "cancelled", "no_show"],
  in_progress: ["completed", "cancelled"],
  completed: [],
  cancelled: [],
  no_show: [],
};

function getSmsTargetStatus(intent: "confirm" | "cancel") {
  return intent === "confirm" ? "confirmed" : "cancelled";
}

async function emitAutomationEvent(
  ctx: MutationCtx,
  args: {
    organizationId: Id<"organizations">;
    module: "gabinet" | "crm" | "platform";
    eventType: string;
    entityType?: string;
    entityId?: string;
    actorUserId?: Id<"users">;
    correlationKey?: string;
    eventIdempotencyKey: string;
    payload: Record<string, unknown>;
  },
) {
  await ctx.runMutation(internal.automation.emitEvent, {
    organizationId: args.organizationId,
    module: args.module,
    eventType: args.eventType,
    entityType: args.entityType,
    entityId: args.entityId,
    actorUserId: args.actorUserId,
    correlationKey: args.correlationKey,
    eventIdempotencyKey: args.eventIdempotencyKey,
    payload: JSON.stringify(args.payload),
    occurredAt: Date.now(),
  });
}

async function applyAppointmentStatusChange(
  ctx: MutationCtx,
  args: {
    appointment: Doc<"gabinetAppointments">;
    organizationId: Id<"organizations">;
    nextStatus: Doc<"gabinetAppointments">["status"];
    actorUserId: Id<"users">;
    auditAction: string;
    auditDetails: string;
    activityDescription: string;
    notificationTitle: string;
    notificationMessage: string;
    cancellationReason?: string;
    sendCancellationNotifications?: boolean;
  },
) {
  const now = Date.now();
  const patch: Record<string, unknown> = {
    status: args.nextStatus,
    updatedAt: now,
  };

  if (args.nextStatus === "cancelled") {
    patch.cancelledAt = now;
    patch.cancelledBy = args.actorUserId;
    patch.cancellationReason = args.cancellationReason;
  }

  await ctx.db.patch(args.appointment._id, patch);

  if (args.nextStatus === "cancelled" && args.sendCancellationNotifications !== false) {
    const patient = await ctx.db.get(args.appointment.patientId);
    const treatment = await ctx.db.get(args.appointment.treatmentId);
    if (patient?.email) {
      const employee = await ctx.db.get(args.appointment.employeeId);
      const patientName = patient
        ? `${patient.firstName}${patient.lastName ? " " + patient.lastName : ""}`
        : "Patient";
      const treatmentName = treatment?.name ?? "Treatment";
      const employeeName = employee?.name ?? "Specjalista";
      await ctx.runMutation(internal.emailEventTrigger.triggerEmailEvent, {
        organizationId: args.organizationId,
        eventType: "appointment.cancelled",
        recipientEmail: patient.email,
        recipientName: patientName,
        payload: JSON.stringify({
          patientName,
          appointmentDate: args.appointment.date,
          appointmentTime: args.appointment.startTime,
          treatmentName,
          employeeName,
        }),
        triggeredBy: args.actorUserId,
      });
    }
    if (patient?.phone) {
      const smsMessage = `Twoja wizyta dnia ${args.appointment.date} o ${args.appointment.startTime} została odwołana.`;
      await ctx.scheduler.runAfter(0, internal.sms.sendAppointmentSms, {
        organizationId: args.organizationId,
        phone: patient.phone,
        message: smsMessage,
      });
    }
  }

  if (args.appointment.scheduledActivityId) {
    const activityPatch: Record<string, unknown> = { updatedAt: Date.now() };
    if (
      args.nextStatus === "completed" ||
      args.nextStatus === "cancelled" ||
      args.nextStatus === "no_show"
    ) {
      activityPatch.isCompleted = true;
      activityPatch.completedAt = Date.now();
    }
    await ctx.db.patch(args.appointment.scheduledActivityId, activityPatch);
  }

  if (
    args.nextStatus === "cancelled" ||
    args.nextStatus === "completed" ||
    args.nextStatus === "no_show"
  ) {
    await ctx.scheduler.runAfter(
      0,
      internal.gabinet.appointmentReminders.cancelRemindersInternal,
      { appointmentId: args.appointment._id },
    );
  }

  if (args.nextStatus === "completed") {
    await handleAppointmentCompletion(ctx, {
      organizationId: args.organizationId,
      appointmentId: args.appointment._id,
      patientId: args.appointment.patientId,
      treatmentId: args.appointment.treatmentId,
      packageUsageId: args.appointment.packageUsageId as
        | Id<"gabinetPackageUsage">
        | undefined,
      userId: args.actorUserId,
    });
  }

  await logActivity(ctx, {
    organizationId: args.organizationId,
    entityType: "gabinetAppointment",
    entityId: args.appointment._id,
    action: "status_changed",
    description: args.activityDescription,
    metadata: {
      oldStatus: args.appointment.status,
      newStatus: args.nextStatus,
    },
    performedBy: args.actorUserId,
  });

  await logAudit(ctx, {
    organizationId: args.organizationId,
    userId: args.actorUserId,
    action: args.auditAction,
    entityType: "gabinetAppointment",
    entityId: args.appointment._id,
    details: args.auditDetails,
  });

  if (args.appointment.createdBy !== args.actorUserId) {
    await createNotificationDirect(ctx, {
      organizationId: args.organizationId,
      userId: args.appointment.createdBy,
      type: "appointment_status_changed",
      title: args.notificationTitle,
      message: args.notificationMessage,
    });
  }
  if (
    args.appointment.employeeId !== args.actorUserId &&
    args.appointment.employeeId !== args.appointment.createdBy
  ) {
    await createNotificationDirect(ctx, {
      organizationId: args.organizationId,
      userId: args.appointment.employeeId,
      type: "appointment_status_changed",
      title: args.notificationTitle,
      message: args.notificationMessage,
    });
  }

  await emitAutomationEvent(ctx, {
    organizationId: args.organizationId,
    module: "gabinet",
    eventType:
      args.nextStatus === "cancelled"
        ? "gabinet.appointment.cancelled"
        : args.nextStatus === "completed"
          ? "gabinet.appointment.completed"
          : args.nextStatus === "no_show"
            ? "gabinet.appointment.no_show"
            : args.nextStatus === "confirmed"
              ? "gabinet.appointment.confirmed"
              : "gabinet.appointment.status_changed",
    entityType: "gabinetAppointment",
    entityId: String(args.appointment._id),
    actorUserId: args.actorUserId,
    correlationKey: `appointment:${args.appointment._id}`,
    eventIdempotencyKey: [
      "automation-event",
      String(args.organizationId),
      String(args.appointment._id),
      String(args.nextStatus),
      String(now),
    ].join(":"),
    payload: {
      organizationId: String(args.organizationId),
      appointmentId: String(args.appointment._id),
      patientId: String(args.appointment.patientId),
      employeeId: String(args.appointment.employeeId),
      treatmentId: String(args.appointment.treatmentId),
      status: args.nextStatus,
      previousStatus: args.appointment.status,
      date: args.appointment.date,
      startTime: args.appointment.startTime,
      cancellationReason: args.cancellationReason,
      createdBy: String(args.appointment.createdBy),
    },
  });
}

function generateRecurringDates(
  startDate: string,
  rule: { frequency: string; count?: number; until?: string },
): string[] {
  const dates: string[] = [];
  const d = new Date(startDate + "T00:00:00");
  const max = rule.count ?? 52;
  const untilDate = rule.until ? new Date(rule.until + "T23:59:59") : null;

  for (let i = 1; i < max; i++) {
    switch (rule.frequency) {
      case "daily":
        d.setDate(d.getDate() + 1);
        break;
      case "weekly":
        d.setDate(d.getDate() + 7);
        break;
      case "biweekly":
        d.setDate(d.getDate() + 14);
        break;
      case "monthly":
        d.setMonth(d.getMonth() + 1);
        break;
      default:
        return dates;
    }
    if (untilDate && d > untilDate) break;
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    dates.push(`${yyyy}-${mm}-${dd}`);
  }
  return dates;
}

export const list = query({
  args: {
    organizationId: v.id("organizations"),
    paginationOpts: paginationOptsValidator,
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const result = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_org", (q) => q.eq("organizationId", args.organizationId))
      .order("desc")
      .paginate(args.paginationOpts);
    if (perm.scope === "own") {
      return {
        ...result,
        page: result.page.filter((r) => r.createdBy === user._id),
      };
    }
    return result;
  },
});

export const getById = query({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const appt = await ctx.db.get(args.appointmentId);
    if (!appt || appt.organizationId !== args.organizationId) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && appt.createdBy !== user._id) {
      throw new Error("Permission denied: you can only view your own records");
    }
    return appt;
  },
});

export const listByDate = query({
  args: {
    organizationId: v.id("organizations"),
    date: v.string(),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const results = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndDate", (q) =>
        q.eq("organizationId", args.organizationId).eq("date", args.date),
      )
      .collect();
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listByDateRange = query({
  args: {
    organizationId: v.id("organizations"),
    startDate: v.string(),
    endDate: v.string(),
    employeeId: v.optional(v.id("users")),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    let results;
    if (args.employeeId) {
      results = await ctx.db
        .query("gabinetAppointments")
        .withIndex("by_orgAndEmployeeAndDate", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("employeeId", args.employeeId!)
            .gte("date", args.startDate)
            .lte("date", args.endDate),
        )
        .collect();
    } else {
      results = await ctx.db
        .query("gabinetAppointments")
        .withIndex("by_orgAndDate", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .gte("date", args.startDate)
            .lte("date", args.endDate),
        )
        .collect();
    }
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listByPatient = query({
  args: {
    organizationId: v.id("organizations"),
    patientId: v.id("gabinetPatients"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const results = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndPatient", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("patientId", args.patientId),
      )
      .collect();
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listByEmployee = query({
  args: {
    organizationId: v.id("organizations"),
    employeeId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const results = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndEmployee", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("employeeId", args.employeeId),
      )
      .collect();
    if (perm.scope === "own") {
      return results.filter((r) => r.createdBy === user._id);
    }
    return results;
  },
});

export const listPatientsForEmployee = query({
  args: {
    organizationId: v.id("organizations"),
    employeeId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    let appointments = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndEmployee", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("employeeId", args.employeeId),
      )
      .collect();
    if (perm.scope === "own") {
      appointments = appointments.filter((r) => r.createdBy === user._id);
    }

    const uniquePatientIds = [...new Set(appointments.map((a) => a.patientId))];
    const patients = await Promise.all(
      uniquePatientIds.map((pid) => ctx.db.get(pid)),
    );
    return patients.filter(Boolean);
  },
});

/**
 * Returns patients for an employee enriched with visit summary data
 * (visit count, last visit date, treatments used, statuses).
 * Used by the employee detail "Klienci" tab for search & filtering.
 */
export const listPatientsWithStatsForEmployee = query({
  args: {
    organizationId: v.id("organizations"),
    employeeId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    let appointments = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndEmployee", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("employeeId", args.employeeId),
      )
      .collect();
    if (perm.scope === "own") {
      appointments = appointments.filter((r) => r.createdBy === user._id);
    }

    // Group appointments by patient
    const byPatient = new Map<Id<"gabinetPatients">, typeof appointments>();
    for (const apt of appointments) {
      const patientId = apt.patientId;
      if (!byPatient.has(patientId)) byPatient.set(patientId, []);
      byPatient.get(patientId)!.push(apt);
    }

    const results = await Promise.all(
      Array.from(byPatient.entries()).map(async ([patientId, patientApts]) => {
        const patient = await ctx.db.get(patientId);
        if (!patient) return null;

        const sortedAppointments = [...patientApts].sort((a, b) => b.date.localeCompare(a.date));
        const lastVisitDate = sortedAppointments[0]?.date ?? null;
        const firstVisitDate = sortedAppointments[sortedAppointments.length - 1]?.date ?? null;
        const treatmentIds = [...new Set(patientApts.map((a) => a.treatmentId))];
        const statuses = [...new Set(patientApts.map((a) => a.status))];

        return {
          ...patient,
          visitCount: patientApts.length,
          lastVisitDate,
          firstVisitDate,
          treatmentIds,
          statuses,
        };
      }),
    );

    return results.filter((result) => result !== null);
  },
});

export const getAvailableSlotsQuery = query({
  args: {
    organizationId: v.id("organizations"),
    userId: v.id("users"),
    date: v.string(),
    duration: v.number(),
    locationId: v.optional(v.id("gabinetLocations")),
  },
  handler: async (ctx, args) => {
    await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    return await getAvailableSlots(ctx, args);
  },
});

export const checkQualification = query({
  args: {
    organizationId: v.id("organizations"),
    userId: v.id("users"),
    treatmentId: v.id("gabinetTreatments"),
  },
  handler: async (ctx, args) => {
    await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    return await checkEmployeeQualification(ctx, args);
  },
});

export const create = mutation({
  args: {
    organizationId: v.id("organizations"),
    patientId: v.id("gabinetPatients"),
    treatmentId: v.id("gabinetTreatments"),
    employeeId: v.id("users"),
    date: v.string(),
    startTime: v.string(),
    endTime: v.string(),
    notes: v.optional(v.string()),
    internalNotes: v.optional(v.string()),
    color: v.optional(v.string()),
    isRecurring: v.optional(v.boolean()),
    recurringRule: v.optional(
      v.object({
        frequency: v.string(),
        count: v.optional(v.number()),
        until: v.optional(v.string()),
      }),
    ),
    prepaymentRequired: v.optional(v.boolean()),
    prepaymentAmount: v.optional(v.number()),
    packageUsageId: v.optional(v.id("gabinetPackageUsage")),
    sendReminder: v.optional(v.boolean()),
    locationId: v.optional(v.id("gabinetLocations")),
    roomId: v.optional(v.id("gabinetRooms")),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    await verifyProductAccess(ctx, args.organizationId, GABINET_PRODUCT_ID);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "create",
    );
    if (!perm.allowed) throw new Error("Permission denied");
    const now = Date.now();

    // Determine whether to send reminder: explicit arg or org default
    const orgSettings = await ctx.db
      .query("orgSettings")
      .withIndex("by_org", (q) => q.eq("organizationId", args.organizationId))
      .unique();
    const shouldSendReminder =
      args.sendReminder ?? orgSettings?.reminderEnabled ?? false;

    // Check employee qualification for treatment
    const qualification = await checkEmployeeQualification(ctx, {
      organizationId: args.organizationId,
      userId: args.employeeId,
      treatmentId: args.treatmentId,
    });
    if (!qualification.qualified) {
      throw new Error(qualification.reason ?? "Employee not qualified");
    }

    // Check conflict
    const conflict = await checkConflict(ctx, {
      organizationId: args.organizationId,
      userId: args.employeeId,
      date: args.date,
      startTime: args.startTime,
      endTime: args.endTime,
      roomId: args.roomId,
    });
    if (conflict.hasConflict) {
      throw new Error(conflict.reason ?? "Time slot conflict");
    }

    const isRecurring = args.isRecurring ?? false;
    const recurringGroupId = isRecurring ? crypto.randomUUID() : undefined;

    // Resolve treatment + patient for calendar event title and auto-package
    const treatment = await ctx.db.get(args.treatmentId);
    const patient = await ctx.db.get(args.patientId);

    // Auto-create package for multi-session treatments
    let resolvedPackageUsageId = args.packageUsageId;
    if (!resolvedPackageUsageId && treatment && (treatment.treatmentCount ?? 1) > 1) {
      resolvedPackageUsageId = await resolveAutoPackageUsage(ctx, {
        organizationId: args.organizationId,
        patientId: args.patientId,
        treatmentId: args.treatmentId,
        treatment,
        userId: user._id,
      });
    }

    // Resolve location from employee schedule (or use explicit)
    let resolvedLocationId = args.locationId ?? null;
    if (!resolvedLocationId) {
      resolvedLocationId = await resolveAppointmentLocation(ctx, {
        organizationId: args.organizationId,
        userId: args.employeeId,
        date: args.date,
      });
    }

    const baseData = {
      organizationId: args.organizationId,
      patientId: args.patientId,
      treatmentId: args.treatmentId,
      employeeId: args.employeeId,
      startTime: args.startTime,
      endTime: args.endTime,
      status: "scheduled" as const,
      notes: args.notes,
      internalNotes: args.internalNotes,
      color: args.color,
      isRecurring,
      recurringRule: args.recurringRule,
      recurringGroupId,
      prepaymentRequired: args.prepaymentRequired,
      prepaymentAmount: args.prepaymentAmount,
      prepaymentStatus: args.prepaymentRequired ? "pending" : undefined,
      packageUsageId: resolvedPackageUsageId,
      sendReminder: shouldSendReminder,
      locationId: resolvedLocationId ?? undefined,
      roomId: args.roomId,
      createdBy: user._id,
      createdAt: now,
      updatedAt: now,
    };
    const patientName = patient
      ? `${patient.firstName}${patient.lastName ? " " + patient.lastName : ""}`
      : "Patient";
    const treatmentName = treatment?.name ?? "Treatment";

    // Create first appointment
    const firstId = await ctx.db.insert("gabinetAppointments", {
      ...baseData,
      date: args.date,
      recurringIndex: isRecurring ? 0 : undefined,
    });

    await emitAutomationEvent(ctx, {
      organizationId: args.organizationId,
      module: "gabinet",
      eventType: "gabinet.appointment.created",
      entityType: "gabinetAppointment",
      entityId: String(firstId),
      actorUserId: user._id,
      correlationKey: `appointment:${firstId}`,
      eventIdempotencyKey: `automation-event:${args.organizationId}:${firstId}:created`,
      payload: {
        organizationId: String(args.organizationId),
        appointmentId: String(firstId),
        patientId: String(args.patientId),
        treatmentId: String(args.treatmentId),
        employeeId: String(args.employeeId),
        date: args.date,
        startTime: args.startTime,
        endTime: args.endTime,
        status: "scheduled",
        patientEmail: patient?.email,
        patientPhone: patient?.phone,
        patientName,
        treatmentName,
        employeeName: args.employeeId,
        createdBy: String(user._id),
      },
    });

    // Dual write: create shared calendar event
    const dueDateMs = new Date(`${args.date}T${args.startTime}:00`).getTime();
    const endDateMs = new Date(`${args.date}T${args.endTime}:00`).getTime();

    const scheduledActivityId = await ctx.db.insert("scheduledActivities", {
      organizationId: args.organizationId,
      title: `${treatmentName} — ${patientName}`,
      activityType: "gabinet:appointment",
      dueDate: dueDateMs,
      endDate: endDateMs,
      isCompleted: false,
      ownerId: user._id,
      description: args.notes,
      linkedEntityType: "gabinetAppointment",
      linkedEntityId: firstId,
      moduleRef: {
        moduleId: "gabinet",
        entityType: "gabinetAppointment",
        entityId: firstId,
      },
      resourceId: args.employeeId,
      createdBy: user._id,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.patch(firstId, { scheduledActivityId });

    // Auto-generate required documents from treatment's form templates
    await autoGenerateAppointmentDocuments(ctx, {
      organizationId: args.organizationId,
      appointmentId: firstId,
      treatmentId: args.treatmentId,
      patientId: args.patientId,
      createdBy: user._id,
    });

    // Generate recurring series
    if (isRecurring && args.recurringRule) {
      const dates = generateRecurringDates(args.date, args.recurringRule);
      for (let i = 0; i < dates.length; i++) {
        const recurId = await ctx.db.insert("gabinetAppointments", {
          ...baseData,
          date: dates[i],
          recurringIndex: i + 1,
        });

        const recurDueMs = new Date(
          `${dates[i]}T${args.startTime}:00`,
        ).getTime();
        const recurEndMs = new Date(`${dates[i]}T${args.endTime}:00`).getTime();

        const recurActivityId = await ctx.db.insert("scheduledActivities", {
          organizationId: args.organizationId,
          title: `${treatmentName} — ${patientName}`,
          activityType: "gabinet:appointment",
          dueDate: recurDueMs,
          endDate: recurEndMs,
          isCompleted: false,
          ownerId: user._id,
          description: args.notes,
          linkedEntityType: "gabinetAppointment",
          linkedEntityId: recurId,
          moduleRef: {
            moduleId: "gabinet",
            entityType: "gabinetAppointment",
            entityId: recurId,
          },
          resourceId: args.employeeId,
          createdBy: user._id,
          createdAt: now,
          updatedAt: now,
        });

        await ctx.db.patch(recurId, { scheduledActivityId: recurActivityId });
      }
    }

    await logActivity(ctx, {
      organizationId: args.organizationId,
      entityType: "gabinetAppointment",
      entityId: firstId,
      action: "created",
      description: `Created appointment for ${args.date} at ${args.startTime}`,
      performedBy: user._id,
    });

    // Schedule reminder if enabled
    if (shouldSendReminder) {
      await ctx.scheduler.runAfter(
        0,
        internal.gabinet.appointmentReminders.scheduleReminderInternal,
        {
          organizationId: args.organizationId,
          appointmentId: firstId,
        },
      );

      // Also schedule reminders for recurring appointments
      if (isRecurring && args.recurringRule) {
        const recurringAppts = await ctx.db
          .query("gabinetAppointments")
          .withIndex("by_orgAndRecurringGroup", (q) =>
            q
              .eq("organizationId", args.organizationId)
              .eq("recurringGroupId", recurringGroupId!),
          )
          .collect();
        for (const recurAppt of recurringAppts) {
          if (recurAppt._id !== firstId) {
            await ctx.scheduler.runAfter(
              0,
              internal.gabinet.appointmentReminders.scheduleReminderInternal,
              {
                organizationId: args.organizationId,
                appointmentId: recurAppt._id,
              },
            );
          }
        }
      }
    }

    return firstId;
  },
});

export const update = mutation({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
    date: v.optional(v.string()),
    startTime: v.optional(v.string()),
    endTime: v.optional(v.string()),
    notes: v.optional(v.string()),
    internalNotes: v.optional(v.string()),
    color: v.optional(v.string()),
    employeeId: v.optional(v.id("users")),
    treatmentId: v.optional(v.id("gabinetTreatments")),
    packageUsageId: v.optional(v.id("gabinetPackageUsage")),
    status: v.optional(gabinetAppointmentStatusValidator),
    cancellationReason: v.optional(v.string()),
    bodyChartData: v.optional(v.string()),
    treatmentParameterValues: v.optional(v.string()),
    interviewNotes: v.optional(v.string()),
    clinicalRemarks: v.optional(v.string()),
    locationId: v.optional(v.id("gabinetLocations")),
    roomId: v.optional(v.id("gabinetRooms")),
    photos: v.optional(
      v.array(
        v.object({
          storageId: v.id("_storage"),
          type: v.union(v.literal("before"), v.literal("after")),
          caption: v.optional(v.string()),
          uploadedAt: v.number(),
        }),
      ),
    ),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    await verifyProductAccess(ctx, args.organizationId, GABINET_PRODUCT_ID);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "edit",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const appt = await ctx.db.get(args.appointmentId);
    if (!appt || appt.organizationId !== args.organizationId) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && appt.createdBy !== user._id) {
      throw new Error("Permission denied: you can only edit your own records");
    }

    // Check conflict if time changed
    const newDate = args.date ?? appt.date;
    const newStart = args.startTime ?? appt.startTime;
    const newEnd = args.endTime ?? appt.endTime;
    const newEmployee = args.employeeId ?? appt.employeeId;

    if (args.date || args.startTime || args.endTime || args.employeeId) {
      const conflict = await checkConflict(ctx, {
        organizationId: args.organizationId,
        userId: newEmployee,
        date: newDate,
        startTime: newStart,
        endTime: newEnd,
        excludeAppointmentId: args.appointmentId,
        roomId: args.roomId ?? appt.roomId,
      });
      if (conflict.hasConflict) {
        throw new Error(conflict.reason ?? "Time slot conflict");
      }
    }

    const {
      organizationId,
      appointmentId,
      status,
      cancellationReason,
      ...updates
    } = args;

    const patch: Record<string, unknown> = {
      ...updates,
      updatedAt: Date.now(),
    };

    // Handle status change with cancellation support
    if (status) {
      const allowed = VALID_TRANSITIONS[appt.status];
      if (!allowed?.includes(status)) {
        throw new Error(`Cannot transition from ${appt.status} to ${status}`);
      }
      patch.status = status;

      if (status === "cancelled") {
        patch.cancelledAt = Date.now();
        patch.cancelledBy = user._id;
        if (cancellationReason) {
          patch.cancellationReason = cancellationReason;
        }
      }
    }

    await ctx.db.patch(appointmentId, patch);

    // Sync time/date changes to scheduledActivity
    if (
      appt.scheduledActivityId &&
      (args.date || args.startTime || args.endTime)
    ) {
      const syncDate = args.date ?? appt.date;
      const syncStart = args.startTime ?? appt.startTime;
      const syncEnd = args.endTime ?? appt.endTime;
      await ctx.db.patch(appt.scheduledActivityId, {
        dueDate: new Date(`${syncDate}T${syncStart}:00`).getTime(),
        endDate: new Date(`${syncDate}T${syncEnd}:00`).getTime(),
        updatedAt: Date.now(),
      });
    }

    // Sync resource change to scheduledActivity
    if (appt.scheduledActivityId && args.employeeId) {
      await ctx.db.patch(appt.scheduledActivityId, {
        resourceId: args.employeeId,
        updatedAt: Date.now(),
      });
    }

    await logActivity(ctx, {
      organizationId,
      entityType: "gabinetAppointment",
      entityId: appointmentId,
      action: "updated",
      description: `Updated appointment`,
      performedBy: user._id,
    });

    const payload = {
      organizationId: String(organizationId),
      appointmentId: String(appointmentId),
      patientId: String(appt.patientId),
      treatmentId: String(args.treatmentId ?? appt.treatmentId),
      employeeId: String(newEmployee),
      date: newDate,
      startTime: newStart,
      endTime: newEnd,
      previousStatus: appt.status,
      status: status ?? appt.status,
      createdBy: String(appt.createdBy),
      updatedFields: Object.keys(updates),
    };

    await emitAutomationEvent(ctx, {
      organizationId,
      module: "gabinet",
      eventType:
        args.date || args.startTime || args.endTime
          ? "gabinet.appointment.rescheduled"
          : "gabinet.appointment.updated",
      entityType: "gabinetAppointment",
      entityId: String(appointmentId),
      actorUserId: user._id,
      correlationKey: `appointment:${appointmentId}`,
      eventIdempotencyKey: `automation-event:${organizationId}:${appointmentId}:${patch.updatedAt}:${args.date || args.startTime || args.endTime ? "rescheduled" : "updated"}`,
      payload,
    });

    return appointmentId;
  },
});

export const updateStatus = mutation({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
    status: gabinetAppointmentStatusValidator,
    forceSkipDocumentGate: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    await verifyProductAccess(ctx, args.organizationId, GABINET_PRODUCT_ID);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "edit",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const appt = await ctx.db.get(args.appointmentId);
    if (!appt || appt.organizationId !== args.organizationId) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && appt.createdBy !== user._id) {
      throw new Error("Permission denied: you can only edit your own records");
    }

    const allowed = VALID_TRANSITIONS[appt.status];
    if (!allowed?.includes(args.status)) {
      throw new Error(
        `Cannot transition from ${appt.status} to ${args.status}`,
      );
    }

    // Document gate: check required documents before status transitions
    if (!args.forceSkipDocumentGate) {
      if (args.status === "in_progress") {
        const gate = await checkDocumentGate(ctx, args.appointmentId, "before_start");
        if (!gate.canProceed) {
          const missingNames = gate.missing.map((d) => d.title).join(", ");
          throw new Error(
            `DOCUMENT_GATE:before_start:${JSON.stringify(gate)}|Nie można rozpocząć wizyty — brakuje wymaganych dokumentów: ${missingNames}`,
          );
        }
      }
      if (args.status === "completed") {
        const gate = await checkDocumentGate(ctx, args.appointmentId, "after_completion");
        if (!gate.canProceed) {
          const missingNames = gate.missing.map((d) => d.title).join(", ");
          throw new Error(
            `DOCUMENT_GATE:after_completion:${JSON.stringify(gate)}|Nie można zakończyć wizyty — brakuje wymaganych dokumentów: ${missingNames}`,
          );
        }
      }
    }

    await applyAppointmentStatusChange(ctx, {
      appointment: appt,
      organizationId: args.organizationId,
      nextStatus: args.status,
      actorUserId: user._id,
      auditAction: "status_changed",
      auditDetails: JSON.stringify({
        oldStatus: appt.status,
        newStatus: args.status,
      }),
      activityDescription: `Status changed from ${appt.status} to ${args.status}`,
      notificationTitle: "Appointment status changed",
      notificationMessage: `Appointment status changed to "${args.status}"`,
    });

    return args.appointmentId;
  },
});

export const getDocumentGateStatus = query({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
    timing: v.union(v.literal("before_start"), v.literal("after_completion")),
  },
  handler: async (ctx, args) => {
    await verifyOrgAccess(ctx, args.organizationId);
    await verifyProductAccess(ctx, args.organizationId, GABINET_PRODUCT_ID);

    const appt = await ctx.db.get(args.appointmentId);
    if (!appt || appt.organizationId !== args.organizationId) {
      throw new Error("Appointment not found");
    }

    return await checkDocumentGate(ctx, args.appointmentId, args.timing);
  },
});

export const applySmsReplyTransition = internalMutation({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
    intent: v.union(v.literal("confirm"), v.literal("cancel")),
    smsEventId: v.id("appointmentSmsEvents"),
  },
  handler: async (ctx, args) => {
    const appointment = await ctx.db.get(args.appointmentId);
    if (!appointment || appointment.organizationId !== args.organizationId) {
      return {
        processingStatus: "ignored" as const,
        reason: "Appointment not found",
      };
    }

    const targetStatus = getSmsTargetStatus(args.intent);
    const allowed = VALID_TRANSITIONS[appointment.status];
    if (!allowed?.includes(targetStatus)) {
      return {
        processingStatus: "ignored" as const,
        reason: `Cannot transition from ${appointment.status} to ${targetStatus}`,
      };
    }

    await applyAppointmentStatusChange(ctx, {
      appointment,
      organizationId: args.organizationId,
      nextStatus: targetStatus,
      actorUserId: appointment.employeeId,
      auditAction: "status_changed_via_sms",
      auditDetails: JSON.stringify({
        oldStatus: appointment.status,
        newStatus: targetStatus,
        intent: args.intent,
        source: "sms_reply",
        smsEventId: args.smsEventId,
      }),
      activityDescription:
        args.intent === "confirm"
          ? "Appointment confirmed via SMS reply"
          : "Appointment cancelled via SMS reply",
      notificationTitle:
        args.intent === "confirm"
          ? "Appointment confirmed via SMS"
          : "Appointment cancelled via SMS",
      notificationMessage:
        args.intent === "confirm"
          ? 'Appointment status changed to "confirmed" from patient SMS reply'
          : 'Appointment status changed to "cancelled" from patient SMS reply',
      cancellationReason:
        args.intent === "cancel" ? "Cancelled by patient SMS reply" : undefined,
    });

    return {
      processingStatus: "processed" as const,
      reason: undefined,
    };
  },
});

export const cancel = mutation({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
    reason: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    await verifyProductAccess(ctx, args.organizationId, GABINET_PRODUCT_ID);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "delete",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const appt = await ctx.db.get(args.appointmentId);
    if (!appt || appt.organizationId !== args.organizationId) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && appt.createdBy !== user._id) {
      throw new Error(
        "Permission denied: you can only delete your own records",
      );
    }

    if (appt.status === "cancelled" || appt.status === "completed") {
      throw new Error(`Cannot cancel a ${appt.status} appointment`);
    }

    await ctx.db.patch(args.appointmentId, {
      status: "cancelled",
      cancelledAt: Date.now(),
      cancelledBy: user._id,
      cancellationReason: args.reason,
      updatedAt: Date.now(),
    });

    // Sync cancellation to scheduledActivity
    if (appt.scheduledActivityId) {
      await ctx.db.patch(appt.scheduledActivityId, {
        isCompleted: true,
        completedAt: Date.now(),
        updatedAt: Date.now(),
      });
    }

    // Cancel pending reminders
    await ctx.scheduler.runAfter(
      0,
      internal.gabinet.appointmentReminders.cancelRemindersInternal,
      { appointmentId: args.appointmentId },
    );

    await logActivity(ctx, {
      organizationId: args.organizationId,
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
      action: "status_changed",
      description: `Cancelled appointment${args.reason ? `: ${args.reason}` : ""}`,
      performedBy: user._id,
    });

    await logAudit(ctx, {
      organizationId: args.organizationId,
      userId: user._id,
      action: "entity_cancelled",
      entityType: "gabinetAppointment",
      entityId: args.appointmentId,
    });

    // Notify appointment creator and employee about cancellation
    if (appt.createdBy !== user._id) {
      await createNotificationDirect(ctx, {
        organizationId: args.organizationId,
        userId: appt.createdBy,
        type: "appointment_status_changed",
        title: "Appointment cancelled",
        message: `An appointment has been cancelled${args.reason ? `: ${args.reason}` : ""}`,
      });
    }
    if (appt.employeeId !== user._id && appt.employeeId !== appt.createdBy) {
      await createNotificationDirect(ctx, {
        organizationId: args.organizationId,
        userId: appt.employeeId,
        type: "appointment_status_changed",
        title: "Appointment cancelled",
        message: `An appointment has been cancelled${args.reason ? `: ${args.reason}` : ""}`,
      });
    }
  },
});

/**
 * For treatments with treatmentCount > 1, auto-create a package template
 * and patient usage record on first booking.
 */
async function resolveAutoPackageUsage(
  ctx: MutationCtx,
  args: {
    organizationId: Id<"organizations">;
    patientId: Id<"gabinetPatients">;
    treatmentId: Id<"gabinetTreatments">;
    treatment: Doc<"gabinetTreatments">;
    userId: Id<"users">;
  },
): Promise<Id<"gabinetPackageUsage"> | undefined> {
  const treatmentCount = args.treatment.treatmentCount;
  if (!treatmentCount || treatmentCount <= 1) return undefined;

  const now = Date.now();

  // 1. Find or create auto-generated package template for this treatment
  let autoPackage = await ctx.db
    .query("gabinetTreatmentPackages")
    .withIndex("by_orgAndAutoTreatment", (q) =>
      q
        .eq("organizationId", args.organizationId)
        .eq("autoGeneratedForTreatmentId", args.treatmentId),
    )
    .first();

  if (!autoPackage) {
    const packageId = await ctx.db.insert("gabinetTreatmentPackages", {
      organizationId: args.organizationId,
      name: `${args.treatment.name} (${treatmentCount}x)`,
      treatments: [{ treatmentId: args.treatmentId, quantity: treatmentCount }],
      totalPrice: args.treatment.price * treatmentCount,
      currency: args.treatment.currency,
      isActive: true,
      autoGeneratedForTreatmentId: args.treatmentId,
      createdBy: args.userId,
      createdAt: now,
      updatedAt: now,
    });
    autoPackage = (await ctx.db.get(packageId))!;
  }

  // 2. Find existing active usage for this patient + package
  const existingUsage = await ctx.db
    .query("gabinetPackageUsage")
    .withIndex("by_orgPatientAndPackage", (q) =>
      q
        .eq("organizationId", args.organizationId)
        .eq("patientId", args.patientId)
        .eq("packageId", autoPackage!._id),
    )
    .filter((q) => q.eq(q.field("status"), "active"))
    .first();

  if (existingUsage) {
    return existingUsage._id;
  }

  // 3. Create new usage record
  const usageId = await ctx.db.insert("gabinetPackageUsage", {
    organizationId: args.organizationId,
    patientId: args.patientId,
    packageId: autoPackage._id,
    purchasedAt: now,
    status: "active",
    treatmentsUsed: [
      {
        treatmentId: args.treatmentId,
        usedCount: 0,
        totalCount: treatmentCount,
      },
    ],
    paidAmount: 0,
    createdBy: args.userId,
    createdAt: now,
    updatedAt: now,
  });

  return usageId;
}

/**
 * When an appointment is completed, award loyalty points based on
 * treatment price and deduct from linked package if applicable.
 */
async function handleAppointmentCompletion(
  ctx: any,
  args: {
    organizationId: Id<"organizations">;
    appointmentId: Id<"gabinetAppointments">;
    patientId: Id<"gabinetPatients">;
    treatmentId: Id<"gabinetTreatments">;
    packageUsageId?: Id<"gabinetPackageUsage">;
    userId: Id<"users">;
  },
) {
  const now = Date.now();
  const treatment = await ctx.db.get(args.treatmentId);

  // 1. Deduct from package if linked
  if (args.packageUsageId) {
    const usage = await ctx.db.get(args.packageUsageId);
    if (usage && usage.status === "active") {
      const entry = usage.treatmentsUsed.find(
        (t: any) => t.treatmentId === args.treatmentId,
      );
      if (entry && entry.usedCount < entry.totalCount) {
        const updatedTreatments = usage.treatmentsUsed.map((t: any) =>
          t.treatmentId === args.treatmentId
            ? { ...t, usedCount: t.usedCount + 1 }
            : t,
        );
        const allUsed = updatedTreatments.every(
          (t: any) => t.usedCount >= t.totalCount,
        );
        await ctx.db.patch(args.packageUsageId, {
          treatmentsUsed: updatedTreatments,
          status: allUsed ? "completed" : "active",
          updatedAt: now,
        });
      }
    }
  }

  // 2. Award loyalty points (1 point per PLN of treatment price)
  if (treatment && treatment.price > 0) {
    const points = Math.floor(treatment.price);
    if (points > 0) {
      const loyalty = await ctx.db
        .query("gabinetLoyaltyPoints")
        .withIndex("by_orgAndPatient", (q: any) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("patientId", args.patientId),
        )
        .first();

      const newBalance = (loyalty?.balance ?? 0) + points;
      const newLifetimeEarned = (loyalty?.lifetimeEarned ?? 0) + points;

      if (loyalty) {
        await ctx.db.patch(loyalty._id, {
          balance: newBalance,
          lifetimeEarned: newLifetimeEarned,
          updatedAt: now,
        });
      } else {
        await ctx.db.insert("gabinetLoyaltyPoints", {
          organizationId: args.organizationId,
          patientId: args.patientId,
          balance: newBalance,
          lifetimeEarned: newLifetimeEarned,
          lifetimeSpent: 0,
          createdAt: now,
          updatedAt: now,
        });
      }

      await ctx.db.insert("gabinetLoyaltyTransactions", {
        organizationId: args.organizationId,
        patientId: args.patientId,
        type: "earn",
        points,
        reason: `Appointment completed: ${treatment.name}`,
        referenceType: "appointment",
        referenceId: args.appointmentId,
        balanceAfter: newBalance,
        createdBy: args.userId,
        createdAt: now,
      });
    }
  }

  // 3. Create pending payment (if not covered by package)
  if (!args.packageUsageId && treatment && treatment.price > 0) {
    await ctx.db.insert("payments", {
      organizationId: args.organizationId,
      patientId: args.patientId,
      appointmentId: args.appointmentId,
      amount: treatment.price,
      currency: "PLN",
      paymentMethod: "cash",
      status: "pending",
      createdBy: args.userId,
      createdAt: now,
      updatedAt: now,
    });
  }
}

export const cancelRecurringSeries = mutation({
  args: {
    organizationId: v.id("organizations"),
    recurringGroupId: v.string(),
    fromDate: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    await verifyProductAccess(ctx, args.organizationId, GABINET_PRODUCT_ID);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "delete",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    const appointments = await ctx.db
      .query("gabinetAppointments")
      .withIndex("by_orgAndRecurringGroup", (q) =>
        q
          .eq("organizationId", args.organizationId)
          .eq("recurringGroupId", args.recurringGroupId),
      )
      .collect();

    const now = Date.now();
    let count = 0;
    for (const appt of appointments) {
      if (appt.status === "cancelled" || appt.status === "completed") continue;
      if (args.fromDate && appt.date < args.fromDate) continue;

      await ctx.db.patch(appt._id, {
        status: "cancelled",
        cancelledAt: now,
        cancelledBy: user._id,
        cancellationReason: "Series cancelled",
        updatedAt: now,
      });
      count++;
    }

    return { cancelled: count };
  },
});

export const getFullDetail = query({
  args: {
    organizationId: v.id("organizations"),
    appointmentId: v.id("gabinetAppointments"),
  },
  handler: async (ctx, args) => {
    const { user } = await verifyOrgAccess(ctx, args.organizationId);
    const perm = await checkPermission(
      ctx,
      args.organizationId,
      "gabinet_appointments",
      "view",
    );
    if (!perm.allowed) throw new Error("Permission denied");

    // Get the appointment
    const appointment = await ctx.db.get(args.appointmentId);
    if (!appointment || appointment.organizationId !== args.organizationId) {
      throw new Error("Appointment not found");
    }
    if (perm.scope === "own" && appointment.createdBy !== user._id) {
      throw new Error("Permission denied: you can only view your own records");
    }

    // Fetch all related data in parallel
    const [
      patient,
      treatment,
      employee,
      documents,
      payments,
      notes,
      patientPackageUsage,
      patientHistory,
      loyaltyBalance,
      loyaltyTransactions,
      allPatientPayments,
      workflowHistory,
    ] = await Promise.all([
      // Patient
      ctx.db.get(appointment.patientId),
      // Treatment
      ctx.db.get(appointment.treatmentId),
      // Employee + User
      ctx.db.get(appointment.employeeId),
      // Documents
      ctx.db
        .query("gabinetDocuments")
        .withIndex("by_appointment", (q) =>
          q.eq("appointmentId", args.appointmentId),
        )
        .collect(),
      // Payments
      ctx.db
        .query("payments")
        .withIndex("by_appointment", (q) =>
          q.eq("appointmentId", args.appointmentId),
        )
        .collect(),
      // Notes
      ctx.db
        .query("notes")
        .withIndex("by_entity", (q) =>
          q
            .eq("entityType", "gabinetAppointment")
            .eq("entityId", args.appointmentId),
        )
        .order("desc")
        .take(50),
      // Patient package usage
      ctx.db
        .query("gabinetPackageUsage")
        .withIndex("by_orgAndPatient", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("patientId", appointment.patientId),
        )
        .collect(),
      // Patient history (last 20 appointments, excluding current)
      ctx.db
        .query("gabinetAppointments")
        .withIndex("by_orgAndPatient", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("patientId", appointment.patientId),
        )
        .filter((q) => q.neq(q.field("_id"), args.appointmentId))
        .order("desc")
        .take(20),
      // Loyalty points balance
      ctx.db
        .query("gabinetLoyaltyPoints")
        .withIndex("by_orgAndPatient", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("patientId", appointment.patientId),
        )
        .first(),
      // Loyalty transactions (last 10)
      ctx.db
        .query("gabinetLoyaltyTransactions")
        .withIndex("by_orgAndPatient", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("patientId", appointment.patientId),
        )
        .order("desc")
        .take(10),
      // All patient payments (for payment history)
      ctx.db
        .query("payments")
        .withIndex("by_orgAndPatient", (q) =>
          q
            .eq("organizationId", args.organizationId)
            .eq("patientId", appointment.patientId),
        )
        .order("desc")
        .take(50),
      // Appointment workflow history
      ctx.db
        .query("appointmentWorkflowHistory")
        .withIndex("by_appointment", (q) => q.eq("appointmentId", args.appointmentId))
        .order("desc")
        .collect(),
    ]);

    // Get treatment details for history appointments
    const historyTreatmentIds = patientHistory
      .map((a) => a.treatmentId)
      .filter(Boolean);
    const historyTreatments = await Promise.all(
      [...new Set(historyTreatmentIds)].map((id) => ctx.db.get(id)),
    );
    const treatmentMap = new Map(
      historyTreatments.filter(Boolean).map((t) => [t!._id, t]),
    );

    // Enrich package usage with package names and treatment names
    const pkgUsagePkgIds = [...new Set(patientPackageUsage.map((u) => u.packageId))];
    const pkgUsageTreatmentIds = [
      ...new Set(patientPackageUsage.flatMap((u) => u.treatmentsUsed.map((t) => t.treatmentId))),
    ];
    const [pkgDefs, pkgTreatmentDefs] = await Promise.all([
      Promise.all(pkgUsagePkgIds.map((id) => ctx.db.get(id))),
      Promise.all(pkgUsageTreatmentIds.map((id) => ctx.db.get(id))),
    ]);
    const pkgDefMap = new Map(pkgDefs.filter(Boolean).map((p) => [p!._id, p!]));
    const pkgTreatmentMap = new Map(pkgTreatmentDefs.filter(Boolean).map((t) => [t!._id, t!]));

    const enrichedPatientPackageUsage = patientPackageUsage.map((u) => {
      const pkgDef = pkgDefMap.get(u.packageId);
      const enrichedTreatments = u.treatmentsUsed.map((t) => ({
        ...t,
        treatmentName: pkgTreatmentMap.get(t.treatmentId)?.name ?? null,
      }));
      const totalUsed = enrichedTreatments.reduce((s, t) => s + t.usedCount, 0);
      const totalCount = enrichedTreatments.reduce((s, t) => s + t.totalCount, 0);
      return {
        ...u,
        packageName: pkgDef?.name ?? null,
        treatmentsUsed: enrichedTreatments,
        totalUsed,
        totalCount,
        progressPercent: totalCount > 0 ? Math.round((totalUsed / totalCount) * 100) : 0,
      };
    });

    // Enrich notes with author names
    const noteAuthorIds = [...new Set(notes.map((n) => n.createdBy))];
    const noteAuthors = await Promise.all(noteAuthorIds.map((id) => ctx.db.get(id)));
    const noteAuthorMap = new Map(
      noteAuthors.filter(Boolean).map((u) => [u!._id, u!.name ?? u!.email ?? null]),
    );
    const enrichedNotes = notes.map((n) => ({
      ...n,
      authorName: noteAuthorMap.get(n.createdBy) ?? null,
    }));

    return {
      appointment,
      patient,
      treatment,
      employee,
      documents,
      payments,
      notes: enrichedNotes,
      patientPackageUsage: enrichedPatientPackageUsage,
      patientHistory: patientHistory.map((a) => ({
        ...a,
        treatment: treatmentMap.get(a.treatmentId),
      })),
      loyaltyBalance: loyaltyBalance?.balance ?? 0,
      loyaltyTier: loyaltyBalance?.tier ?? null,
      loyaltyTransactions,
      allPatientPayments,
      workflowHistory,
    };
  },
});

export const getPhotoUrls = query({
  args: {
    organizationId: v.id("organizations"),
    storageIds: v.array(v.id("_storage")),
  },
  handler: async (ctx, args) => {
    await verifyOrgAccess(ctx, args.organizationId);
    return Promise.all(
      args.storageIds.map((id) => ctx.storage.getUrl(id)),
    );
  },
});
