// Barrel file: named icon components that mirror lucide-react's export API.
// Usage: import { Users, Building2, TrendingUp } from "@/lib/ez-icons";
import { createElement } from "react";
import { EzIcon } from "@/components/ui/ez-icon";
import { ICON_MAP } from "./icon-map";
import type { EzIconType } from "./types";

export type { EzIconType };

// Re-export EzIconType as LucideIcon for backward compatibility
export type LucideIcon = EzIconType;

function createIcon(lucideName: string): EzIconType {
  const ezName = ICON_MAP[lucideName];
  if (!ezName) {
    console.warn(`[ez-icons] No mapping for "${lucideName}"`);
  }
  const Icon: EzIconType = ({ className, size }: { className?: string; size?: number }) =>
    createElement(EzIcon, { name: ezName ?? lucideName, size, className });
  Icon.displayName = lucideName;
  return Icon;
}

// --- Named exports (alphabetical) ---
export const ActivityIcon = createIcon("ActivityIcon");
export const AlertCircle = createIcon("AlertCircle");
export const AlertTriangle = createIcon("AlertTriangle");
export const ArrowDown = createIcon("ArrowDown");
export const ArrowDownRight = createIcon("ArrowDownRight");
export const ArrowRight = createIcon("ArrowRight");
export const ArrowUp = createIcon("ArrowUp");
export const ArrowUpRight = createIcon("ArrowUpRight");
export const BadgeCheck = createIcon("BadgeCheck");
export const BarChart3 = createIcon("BarChart3");
export const Bell = createIcon("Bell");
export const Briefcase = createIcon("Briefcase");
export const Building2 = createIcon("Building2");
export const Calendar = createIcon("Calendar");
export const CalendarCheck = createIcon("CalendarCheck");
export const CalendarIcon = createIcon("Calendar");
export const Check = createIcon("Check");
export const CheckCircle = createIcon("CheckCircle");
export const CheckCircle2 = createIcon("CheckCircle2");
export const ChevronDown = createIcon("ChevronDown");
export const ChevronDownIcon = createIcon("ChevronDownIcon");
export const ChevronLeft = createIcon("ChevronLeft");
export const ChevronLeftIcon = createIcon("ChevronLeftIcon");
export const ChevronRight = createIcon("ChevronRight");
export const ChevronRightIcon = createIcon("ChevronRightIcon");
export const ChevronUp = createIcon("ChevronUp");
export const ChevronsLeft = createIcon("ChevronsLeft");
export const ChevronsRight = createIcon("ChevronsRight");
export const ChevronsUpDown = createIcon("ChevronsUpDown");
export const Circle = createIcon("Circle");
export const CircleCheck = createIcon("CircleCheck");
export const ClipboardList = createIcon("ClipboardList");
export const Clock = createIcon("Clock");
export const Coffee = createIcon("Coffee");
export const Contact = createIcon("Contact");
export const DollarSign = createIcon("DollarSign");
export const Download = createIcon("Download");
export const Edit2 = createIcon("Edit2");
export const ExternalLink = createIcon("ExternalLink");
export const Eye = createIcon("Eye");
export const FileCheck = createIcon("FileCheck");
export const FileSignature = createIcon("FileSignature");
export const FileText = createIcon("FileText");
export const Filter = createIcon("Filter");
export const Flag = createIcon("Flag");
export const Gift = createIcon("Gift");
export const GripVertical = createIcon("GripVertical");
export const Handshake = createIcon("Handshake");
export const Heart = createIcon("Heart");
export const HeartPulse = createIcon("HeartPulse");
export const Inbox = createIcon("Inbox");
export const Info = createIcon("Info");
export const Kanban = createIcon("Kanban");
export const KanbanIcon = createIcon("KanbanIcon");
export const Languages = createIcon("Languages");
export const LanguagesIcon = createIcon("LanguagesIcon");
export const LayoutDashboard = createIcon("LayoutDashboard");
export const Link = createIcon("Link");
export const Link2 = createIcon("Link2");
export const Loader2 = createIcon("Loader2");
export const LoaderCircle = createIcon("LoaderCircle");
export const LogIn = createIcon("LogIn");
export const LogOut = createIcon("LogOut");
export const Mail = createIcon("Mail");
export const MailOpen = createIcon("MailOpen");
export const MapPin = createIcon("MapPin");
export const MapPinIcon = createIcon("MapPinIcon");
export const MessageCircle = createIcon("MessageCircle");
export const MessageSquare = createIcon("MessageSquare");
export const Minus = createIcon("Minus");
export const Monitor = createIcon("Monitor");
export const Moon = createIcon("Moon");
export const MoreHorizontal = createIcon("MoreHorizontal");
export const OctagonX = createIcon("OctagonX");
export const Package = createIcon("Package");
export const PanelLeft = createIcon("PanelLeft");
export const Pencil = createIcon("Pencil");
export const PenTool = createIcon("PenTool");
export const Phone = createIcon("Phone");
export const PhoneCall = createIcon("PhoneCall");
export const PhoneIncoming = createIcon("PhoneIncoming");
export const PhoneMissed = createIcon("PhoneMissed");
export const PhoneOutgoing = createIcon("PhoneOutgoing");
export const PieChart = createIcon("PieChart");
export const Pin = createIcon("Pin");
export const PlayCircle = createIcon("PlayCircle");
export const Plus = createIcon("Plus");
export const PlusCircle = createIcon("PlusCircle");
export const Power = createIcon("Power");
export const RefreshCw = createIcon("RefreshCw");
export const Reply = createIcon("Reply");
export const RotateCcw = createIcon("RotateCcw");
export const Search = createIcon("Search");
export const SearchIcon = createIcon("SearchIcon");
export const Send = createIcon("Send");
export const Share2 = createIcon("Share2");
export const Settings = createIcon("Settings");
export const Settings2 = createIcon("Settings2");
export const Slash = createIcon("Slash");
export const Star = createIcon("Star");
export const Stethoscope = createIcon("Stethoscope");
export const StickyNote = createIcon("StickyNote");
export const Sun = createIcon("Sun");
export const TableIcon = createIcon("TableIcon");
export const Tag = createIcon("Tag");
export const Target = createIcon("Target");
export const Trash2 = createIcon("Trash2");
export const TreePalm = createIcon("TreePalm");
export const TrendingUp = createIcon("TrendingUp");
export const TriangleAlert = createIcon("TriangleAlert");
export const Trophy = createIcon("Trophy");
export const Unlink = createIcon("Unlink");
export const Unplug = createIcon("Unplug");
export const Upload = createIcon("Upload");
export const User = createIcon("User");
export const UserCheck = createIcon("UserCheck");
export const UserCog = createIcon("UserCog");
export const UserPlus = createIcon("UserPlus");
export const Users = createIcon("Users");
export const Video = createIcon("Video");
export const X = createIcon("X");
export const XCircle = createIcon("XCircle");

// Aliases with Icon suffix (used by shadcn-studio blocks)
export const AlertCircleIcon = createIcon("AlertCircleIcon");
export const AlertTriangleIcon = createIcon("AlertTriangleIcon");
export const ArrowDownIcon = createIcon("ArrowDownIcon");
export const ArrowDownLeftIcon = createIcon("ArrowDownLeftIcon");
export const ArrowRightIcon = createIcon("ArrowRightIcon");
export const ArrowUpIcon = createIcon("ArrowUpIcon");
export const ArrowUpRightIcon = createIcon("ArrowUpRightIcon");
export const BookOpenIcon = createIcon("BookOpenIcon");
export const BuildingIcon = createIcon("BuildingIcon");
export const CalendarClockIcon = createIcon("CalendarClockIcon");
export const CalendarDaysIcon = createIcon("CalendarDaysIcon");
export const ChartColumnBigIcon = createIcon("ChartColumnBigIcon");
export const CheckIcon = createIcon("CheckIcon");
export const ChevronUpIcon = createIcon("ChevronUpIcon");
export const CircleCheckIcon = createIcon("CircleCheckIcon");
export const CircleDollarSignIcon = createIcon("CircleDollarSignIcon");
export const CircleHelpIcon = createIcon("CircleHelpIcon");
export const CircleIcon = createIcon("CircleIcon");
export const CirclePlusIcon = createIcon("CirclePlusIcon");
export const CodeXmlIcon = createIcon("CodeXmlIcon");
export const CopyIcon = createIcon("CopyIcon");
export const CreditCard = createIcon("CreditCard");
export const CreditCardIcon = createIcon("CreditCardIcon");
export const DollarSignIcon = createIcon("DollarSignIcon");
export const EllipsisIcon = createIcon("EllipsisIcon");
export const EllipsisVerticalIcon = createIcon("EllipsisVerticalIcon");
export const ExternalLinkIcon = createIcon("ExternalLinkIcon");
export const FileTextIcon = createIcon("FileTextIcon");
export const GiftIcon = createIcon("GiftIcon");
export const GlobeIcon = createIcon("GlobeIcon");
export const HeartHandshakeIcon = createIcon("HeartHandshakeIcon");
export const HouseIcon = createIcon("HouseIcon");
export const ImageIcon = createIcon("ImageIcon");
export const LaptopIcon = createIcon("LaptopIcon");
export const LaptopMinimalIcon = createIcon("LaptopMinimalIcon");
export const LinkIcon = createIcon("LinkIcon");
export const LogOutIcon = createIcon("LogOutIcon");
export const MessageSquareIcon = createIcon("MessageSquareIcon");
export const MessageSquareTextIcon = createIcon("MessageSquareTextIcon");
export const MonitorSmartphone = createIcon("MonitorSmartphone");
export const MonitorSmartphoneIcon = createIcon("MonitorSmartphoneIcon");
export const MoreVertical = createIcon("MoreVertical");
export const MoreVerticalIcon = createIcon("MoreVerticalIcon");
export const PackageIcon = createIcon("PackageIcon");
export const PackageOpenIcon = createIcon("PackageOpenIcon");
export const PencilRulerIcon = createIcon("PencilRulerIcon");
export const PlusIcon = createIcon("PlusIcon");
export const SendIcon = createIcon("SendIcon");
export const SettingsIcon = createIcon("SettingsIcon");
export const ShirtIcon = createIcon("ShirtIcon");
export const ShoppingCart = createIcon("ShoppingCart");
export const ShoppingCartIcon = createIcon("ShoppingCartIcon");
export const SmartphoneIcon = createIcon("SmartphoneIcon");
export const SparklesIcon = createIcon("SparklesIcon");
export const SquarePen = createIcon("SquarePen");
export const SquarePenIcon = createIcon("SquarePenIcon");
export const StoreIcon = createIcon("StoreIcon");
export const ThumbsUpIcon = createIcon("ThumbsUpIcon");
export const TrendingUpIcon = createIcon("TrendingUpIcon");
export const TruckIcon = createIcon("TruckIcon");
export const Undo2 = createIcon("Undo2");
export const Undo2Icon = createIcon("Undo2Icon");
export const UploadIcon = createIcon("UploadIcon");
export const UserCheckIcon = createIcon("UserCheckIcon");
export const UserIcon = createIcon("UserIcon");
export const UserRoundIcon = createIcon("UserRoundIcon");
export const UsersIcon = createIcon("UsersIcon");
export const UsersRoundIcon = createIcon("UsersRoundIcon");
export const VideoIcon = createIcon("VideoIcon");
export const WalletIcon = createIcon("WalletIcon");
export const XIcon = createIcon("XIcon");
