import {
  BarChart3,
  Building2,
  Calendar,
  CalendarCheck,
  ClipboardList,
  Clock,
  Download,
  Eye,
  FilePlus,
  FileText,
  Filter,
  Kanban,
  LinkIcon,
  Mail,
  MailOpen,
  Package,
  Phone,
  PlusCircle,
  RefreshCw,
  SearchIcon,
  Send,
  Settings,
  Star,
  TableIcon,
  Tag,
  TrendingUp,
  Upload,
  UserPlus,
  Users,
} from "@/lib/ez-icons";
import { ActivitiesWidgets } from "@/components/sidebar-widgets/crm/activities-widgets";
import { CalendarWidgets } from "@/components/sidebar-widgets/crm/calendar-widgets";
import { CallsWidgets } from "@/components/sidebar-widgets/crm/calls-widgets";
import { CompaniesWidgets } from "@/components/sidebar-widgets/crm/companies-widgets";
import { ContactsWidgets } from "@/components/sidebar-widgets/crm/contacts-widgets";
import { DealsWidgets } from "@/components/sidebar-widgets/crm/deals-widgets";
import { DocumentsWidgets } from "@/components/sidebar-widgets/crm/documents-widgets";
import { EmailTemplatesWidgets } from "@/components/sidebar-widgets/crm/email-templates-widgets";
import { InboxWidgets } from "@/components/sidebar-widgets/crm/inbox-widgets";
import { InsightsWidgets } from "@/components/sidebar-widgets/crm/insights-widgets";
import { ProductsWidgets } from "@/components/sidebar-widgets/crm/products-widgets";
import type { ModuleManifest } from "@/modules/types";

export const crmManifest: ModuleManifest = {
  id: "crm",
  productKey: "crm",
  workspaceRoot: "/dashboard",
  settingsRoots: ["/dashboard/settings"],
  workspace: {
    id: "crm",
    icon: TrendingUp,
    nameKey: "nav.workspace.crm",
    descKey: "nav.workspace.crmDesc",
    href: "/dashboard",
  },
  primaryNav: [
    { labelKey: "nav.insights", href: "/dashboard", icon: BarChart3, activeMatch: "exact" },
    { labelKey: "nav.deals", href: "/dashboard/leads", icon: TrendingUp },
    { labelKey: "nav.activities", href: "/dashboard/activities", icon: CalendarCheck },
    { labelKey: "nav.calendar", href: "/dashboard/calendar", icon: Calendar },
    { labelKey: "nav.inbox", href: "/dashboard/inbox", icon: Mail },
    { labelKey: "nav.emailTemplates", href: "/dashboard/email-templates", icon: MailOpen },
    { labelKey: "nav.contacts", href: "/dashboard/contacts", icon: Users },
    { labelKey: "nav.companies", href: "/dashboard/companies", icon: Building2 },
    { labelKey: "nav.products", href: "/dashboard/products", icon: Package },
    { labelKey: "nav.documents", href: "/dashboard/documents", icon: FileText },
    { labelKey: "nav.documentTemplates", href: "/dashboard/settings/form-templates", icon: FilePlus },
    { labelKey: "nav.calls", href: "/dashboard/calls", icon: Phone },
    { labelKey: "nav.settings", href: "/dashboard/settings", icon: Settings },
  ],
  settingsNav: [
    { labelKey: "settingsNav.general", to: "/dashboard/settings" },
    { labelKey: "settingsNav.profile", to: "/dashboard/settings/profile" },
    { labelKey: "settingsNav.billing", to: "/dashboard/settings/billing", adminOnly: true },
    { labelKey: "settingsNav.pipelines", to: "/dashboard/settings/pipelines", adminOnly: true },
    { labelKey: "settingsNav.customFields", to: "/dashboard/settings/custom-fields", adminOnly: true },
    { labelKey: "settingsNav.activityTypes", to: "/dashboard/settings/activity-types", adminOnly: true },
    { labelKey: "settingsNav.lostReasons", to: "/dashboard/settings/lost-reasons", adminOnly: true },
    { labelKey: "settingsNav.sources", to: "/dashboard/settings/sources", adminOnly: true },
    { labelKey: "settingsNav.team", to: "/dashboard/settings/team" },
    { labelKey: "settingsNav.permissions", to: "/dashboard/settings/permissions", adminOnly: true },
    { labelKey: "settingsNav.auditLog", to: "/dashboard/settings/audit-log", adminOnly: true },
    { labelKey: "settingsNav.mail", to: "/dashboard/settings/mail", adminOnly: true },
    { labelKey: "settingsNav.automations", to: "/dashboard/settings/automations", adminOnly: true },
    { labelKey: "settingsNav.emailTemplates", to: "/dashboard/settings/email-templates" },
    { labelKey: "settingsNav.emailEvents", to: "/dashboard/settings/email-events", adminOnly: true },
    { labelKey: "settingsNav.integrations", to: "/dashboard/settings/integrations", adminOnly: true },
    { labelKey: "settingsNav.googleCalendar", to: "/dashboard/settings/google-calendar" },
    { labelKey: "settingsNav.organization", to: "/dashboard/settings/organization", adminOnly: true },
    { labelKey: "settingsNav.documentTemplates", to: "/dashboard/settings/form-templates", adminOnly: true },
    { labelKey: "settingsNav.documentComponents", to: "/dashboard/settings/document-components", adminOnly: true },
  ],
  pageContexts: [
    {
      key: "dashboard",
      titleKey: "nav.insights",
      widgets: InsightsWidgets,
      matches: [{ to: "/dashboard" }],
      actions: [
        { labelKey: "nav.actions.viewPipeline", icon: Eye, href: "/dashboard/leads" },
        {
          labelKey: "nav.actions.addDeal",
          icon: TrendingUp,
          quickCreate: "lead",
          permissionFeature: "leads",
        },
        { labelKey: "nav.actions.todaysActivities", icon: Clock, href: "/dashboard/activities" },
        { labelKey: "nav.actions.exportReport", icon: Download, href: "/dashboard" },
      ],
    },
    {
      key: "contacts",
      titleKey: "nav.contacts",
      widgets: ContactsWidgets,
      matches: [{ to: "/dashboard/contacts", fuzzy: true }],
      actions: [
        {
          labelKey: "nav.actions.addContact",
          icon: UserPlus,
          quickCreate: "contact",
          permissionFeature: "contacts",
        },
        { labelKey: "nav.actions.importCsv", icon: Upload, dispatch: "importCsv" },
        { labelKey: "nav.actions.exportCsv", icon: Download, dispatch: "exportCsv" },
        { labelKey: "nav.actions.savedViews", icon: Star, dispatch: "savedViews" },
      ],
    },
    {
      key: "companies",
      titleKey: "nav.companies",
      widgets: CompaniesWidgets,
      matches: [{ to: "/dashboard/companies", fuzzy: true }],
      actions: [
        {
          labelKey: "nav.actions.addCompany",
          icon: PlusCircle,
          quickCreate: "company",
          permissionFeature: "companies",
        },
        { labelKey: "nav.actions.importCsv", icon: Upload, dispatch: "importCsv" },
        { labelKey: "nav.actions.exportCsv", icon: Download, dispatch: "exportCsv" },
        { labelKey: "nav.actions.viewRelationships", icon: LinkIcon, dispatch: "viewRelationships" },
      ],
    },
    {
      key: "leads",
      titleKey: "nav.deals",
      widgets: DealsWidgets,
      matches: [{ to: "/dashboard/leads", fuzzy: true }],
      actions: [
        {
          labelKey: "nav.actions.addDeal",
          icon: PlusCircle,
          quickCreate: "lead",
          permissionFeature: "leads",
        },
        { labelKey: "nav.actions.viewKanban", icon: Kanban, href: "/dashboard/pipelines" },
        { labelKey: "nav.actions.viewTable", icon: TableIcon, href: "/dashboard/leads" },
        { labelKey: "nav.actions.pipelineSettings", icon: Settings, href: "/dashboard/settings/pipelines" },
        { labelKey: "nav.actions.importCsv", icon: Upload, dispatch: "importCsv" },
        { labelKey: "nav.actions.exportCsv", icon: Download, dispatch: "exportCsv" },
      ],
    },
    {
      key: "activities",
      titleKey: "nav.activities",
      widgets: ActivitiesWidgets,
      matches: [{ to: "/dashboard/activities", fuzzy: true }],
      actions: [
        {
          labelKey: "nav.actions.addActivity",
          icon: PlusCircle,
          quickCreate: "activity",
          permissionFeature: "activities",
        },
        { labelKey: "nav.actions.filterByType", icon: Filter, dispatch: "openFilter" },
        { labelKey: "nav.actions.calendarView", icon: Calendar, href: "/dashboard/calendar" },
        { labelKey: "nav.actions.upcomingOnly", icon: Clock, dispatch: "upcomingOnly" },
      ],
    },
    {
      key: "calendar",
      titleKey: "nav.calendar",
      widgets: CalendarWidgets,
      matches: [{ to: "/dashboard/calendar", fuzzy: true }],
      actions: [
        {
          labelKey: "nav.actions.addActivity",
          icon: PlusCircle,
          quickCreate: "activity",
          permissionFeature: "activities",
        },
        { labelKey: "nav.actions.goToToday", icon: CalendarCheck, dispatch: "goToToday" },
        { labelKey: "nav.actions.filterByType", icon: Filter, dispatch: "openFilter" },
        { labelKey: "nav.actions.viewActivities", icon: ClipboardList, href: "/dashboard/activities" },
      ],
    },
    {
      key: "documents",
      titleKey: "nav.documents",
      widgets: DocumentsWidgets,
      matches: [{ to: "/dashboard/documents", fuzzy: true }],
      actions: [
        { labelKey: "nav.actions.createFromTemplate", icon: FileText, href: "/dashboard/settings/form-templates" },
        { labelKey: "nav.actions.filterByType", icon: Filter, dispatch: "openFilter" },
      ],
    },
    {
      key: "products",
      titleKey: "nav.products",
      widgets: ProductsWidgets,
      matches: [{ to: "/dashboard/products", fuzzy: true }],
      actions: [
        {
          labelKey: "nav.actions.addProduct",
          icon: PlusCircle,
          quickCreate: "product",
          permissionFeature: "products",
        },
        { labelKey: "nav.actions.importCsv", icon: Upload, dispatch: "importCsv" },
        { labelKey: "nav.actions.exportCsv", icon: Download, dispatch: "exportCsv" },
        { labelKey: "nav.actions.categoryFilter", icon: Tag, dispatch: "openFilter" },
      ],
    },
    {
      key: "calls",
      titleKey: "nav.calls",
      widgets: CallsWidgets,
      matches: [{ to: "/dashboard/calls", fuzzy: true }],
      actions: [
        {
          labelKey: "nav.actions.logCall",
          icon: Phone,
          quickCreate: "call",
          permissionFeature: "calls",
        },
        {
          labelKey: "nav.actions.addContact",
          icon: UserPlus,
          quickCreate: "contact",
          permissionFeature: "contacts",
        },
        {
          labelKey: "nav.actions.addActivity",
          icon: CalendarCheck,
          quickCreate: "activity",
          permissionFeature: "activities",
        },
      ],
    },
    {
      key: "inbox",
      titleKey: "nav.inbox",
      widgets: InboxWidgets,
      matches: [{ to: "/dashboard/inbox", fuzzy: true }],
      actions: [
        { labelKey: "nav.actions.composeEmail", icon: Send, dispatch: "composeEmail" },
        { labelKey: "nav.actions.viewUnread", icon: Mail, dispatch: "viewUnread" },
        { labelKey: "nav.actions.syncGmail", icon: RefreshCw, href: "/dashboard/settings/email" },
        {
          labelKey: "nav.actions.addContact",
          icon: UserPlus,
          quickCreate: "contact",
          permissionFeature: "contacts",
        },
      ],
    },
    {
      key: "email-templates",
      titleKey: "nav.emailTemplates",
      widgets: EmailTemplatesWidgets,
      matches: [{ to: "/dashboard/email-templates", fuzzy: true }],
      actions: [
        { labelKey: "nav.actions.addTemplate", icon: PlusCircle, quickCreate: "emailTemplate" },
        { labelKey: "nav.actions.searchTemplates", icon: SearchIcon, dispatch: "openSearch" },
        { labelKey: "nav.actions.composeEmail", icon: Send, dispatch: "composeEmail" },
      ],
    },
  ],
};
