/**
 * Unit tests for autoGenerateAppointmentDocuments frequency paths.
 *
 * The four frequency branches under test:
 *   - once            — generate at most once per patient per template
 *   - first_visit_only — generate only when the patient has no prior
 *                        completed appointment for the same treatment
 *   - every_n_days    — generate unless the patient has a non-expired signed
 *                        copy (fallback expiry via signedAt + validityDays)
 *   - on_expiry       — same skip logic, but uses the explicit expiresAt
 *                        field written by migration 00142
 *
 * Closes #5449.
 */

import { afterEach, describe, expect, test } from "vitest";
import type { Id } from "../../convex/_generated/dataModel";
import { createTestCtx, seedTestUser } from "../../convex/_test_helpers";
import { createSupabaseDb } from "../../convex/_helpers/supabaseDb";
import { autoGenerateAppointmentDocuments } from "../../convex/gabinet/_helpers/autoGenerateDocuments";

afterEach(async () => {
  // Drain any pending setTimeout(0) side-effect callbacks before the next test.
  await new Promise((resolve) => setTimeout(resolve, 0));
});

// ---------------------------------------------------------------------------
// Seed helpers
// ---------------------------------------------------------------------------

async function seedTemplate(orgStr: string, userStr: string, templateId: string) {
  const db = createSupabaseDb();
  const now = Date.now();
  await db.insert("formTemplates", {
    _id: templateId,
    organizationId: orgStr,
    name: "Test Consent Form",
    category: "intake",
    formJson: "{}",
    modules: ["gabinet"],
    entityTypes: ["appointment"],
    requiresSignature: false,
    version: 1,
    isActive: true,
    createdBy: userStr,
    createdAt: now,
    updatedAt: now,
  });
}

async function seedTreatment(
  orgStr: string,
  userStr: string,
  treatmentId: string,
  templateId: string,
  frequency: "once" | "first_visit_only" | "every_n_days" | "on_expiry",
  validityDays?: number,
) {
  const db = createSupabaseDb();
  const now = Date.now();
  await db.insert("gabinetTreatments", {
    _id: treatmentId,
    organizationId: orgStr,
    name: "Test Treatment",
    duration: 30,
    price: 100,
    isActive: true,
    requiredFormTemplates: [
      {
        templateId,
        timing: "before_start",
        frequency,
        validityDays: validityDays ?? null,
        isRequired: true,
      },
    ],
    createdBy: userStr,
    createdAt: now,
    updatedAt: now,
  });
}

async function seedPatient(orgStr: string, userStr: string, patientId: string) {
  const db = createSupabaseDb();
  const now = Date.now();
  await db.insert("gabinetPatients", {
    _id: patientId,
    organizationId: orgStr,
    firstName: "Anna",
    lastName: "Nowak",
    isActive: true,
    createdBy: userStr,
    createdAt: now,
    updatedAt: now,
  });
}

async function seedAppointment(
  orgStr: string,
  userStr: string,
  appointmentId: string,
  patientId: string,
  treatmentId: string,
  status: string,
) {
  const db = createSupabaseDb();
  const now = Date.now();
  await db.insert("gabinetAppointments", {
    _id: appointmentId,
    organizationId: orgStr,
    patientId,
    treatmentId,
    employeeId: userStr,
    date: "2026-08-20",
    startTime: "10:00",
    endTime: "10:30",
    status,
    isRecurring: false,
    createdBy: userStr,
    createdAt: now,
    updatedAt: now,
  });
}

async function seedSignedDoc(
  orgStr: string,
  templateId: string,
  appointmentId: string,
  opts: { signedAt?: number; expiresAt?: number } = {},
) {
  const db = createSupabaseDb();
  const now = Date.now();
  await db.insert("formDocuments", {
    organizationId: orgStr,
    templateId,
    entityType: "appointment",
    entityId: appointmentId,
    status: "signed",
    signedAt: opts.signedAt ?? now,
    expiresAt: opts.expiresAt ?? null,
    autoGenerated: true,
    isRequired: true,
    createdAt: now,
    updatedAt: now,
  });
}

async function countDocumentsForAppointment(
  orgStr: string,
  templateId: string,
  appointmentId: string,
): Promise<number> {
  const db = createSupabaseDb();
  const rows = await db
    .query("formDocuments")
    .eq("organizationId", orgStr)
    .eq("templateId", templateId)
    .eq("entityId", appointmentId)
    .collect();
  return rows.length;
}

async function runGenerate(
  t: ReturnType<typeof createTestCtx>,
  organizationId: Id<"organizations">,
  appointmentId: string,
  treatmentId: string,
  patientId: string,
  userStr: string,
) {
  await t.run(async (ctx) => {
    await autoGenerateAppointmentDocuments(ctx, {
      organizationId,
      appointmentId: appointmentId as unknown as Id<"gabinetAppointments">,
      treatmentId: treatmentId as unknown as Id<"gabinetTreatments">,
      patientId: patientId as unknown as Id<"gabinetPatients">,
      createdBy: userStr,
      timing: "before_start",
    });
  });
}

// ---------------------------------------------------------------------------
// frequency: once
// ---------------------------------------------------------------------------

describe("frequency: once", () => {
  test("generates document when patient has no prior signed document", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-once-a";
    const treatmentId = "treat-once-a";
    const patientId = "patient-once-a";
    const appointmentId = "appt-once-a";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "once");
    await seedPatient(orgStr, userStr, patientId);
    await seedAppointment(orgStr, userStr, appointmentId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, appointmentId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, appointmentId)).toBe(1);
  });

  test("skips document when patient already has a signed document for the template", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-once-b";
    const treatmentId = "treat-once-b";
    const patientId = "patient-once-b";
    const priorApptId = "appt-once-b-prior";
    const currentApptId = "appt-once-b-current";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "once");
    await seedPatient(orgStr, userStr, patientId);

    // A prior appointment with an already-signed document
    await seedAppointment(orgStr, userStr, priorApptId, patientId, treatmentId, "completed");
    await seedSignedDoc(orgStr, templateId, priorApptId, { signedAt: Date.now() - 10_000 });

    // The new appointment being created
    await seedAppointment(orgStr, userStr, currentApptId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, currentApptId, treatmentId, patientId, userStr);

    // No new document should have been created for the current appointment
    expect(await countDocumentsForAppointment(orgStr, templateId, currentApptId)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// frequency: first_visit_only
// ---------------------------------------------------------------------------

describe("frequency: first_visit_only", () => {
  test("generates document on the patient's first visit for the treatment", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-fvo-a";
    const treatmentId = "treat-fvo-a";
    const patientId = "patient-fvo-a";
    const appointmentId = "appt-fvo-a";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "first_visit_only");
    await seedPatient(orgStr, userStr, patientId);
    await seedAppointment(orgStr, userStr, appointmentId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, appointmentId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, appointmentId)).toBe(1);
  });

  test("skips document when patient already has a prior completed appointment for the same treatment", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-fvo-b";
    const treatmentId = "treat-fvo-b";
    const patientId = "patient-fvo-b";
    const priorApptId = "appt-fvo-b-prior";
    const currentApptId = "appt-fvo-b-current";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "first_visit_only");
    await seedPatient(orgStr, userStr, patientId);

    // A prior completed appointment for the same treatment
    await seedAppointment(orgStr, userStr, priorApptId, patientId, treatmentId, "completed");

    // The new (second) appointment
    await seedAppointment(orgStr, userStr, currentApptId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, currentApptId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, currentApptId)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// frequency: every_n_days
// (skip logic: skip when a signed copy exists with signedAt + validityMs > now)
// ---------------------------------------------------------------------------

describe("frequency: every_n_days", () => {
  test("generates document when patient has no prior signed document", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-end-a";
    const treatmentId = "treat-end-a";
    const patientId = "patient-end-a";
    const appointmentId = "appt-end-a";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "every_n_days", 30);
    await seedPatient(orgStr, userStr, patientId);
    await seedAppointment(orgStr, userStr, appointmentId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, appointmentId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, appointmentId)).toBe(1);
  });

  test("skips document when patient has a signed copy still within the validity window", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-end-b";
    const treatmentId = "treat-end-b";
    const patientId = "patient-end-b";
    const priorApptId = "appt-end-b-prior";
    const currentApptId = "appt-end-b-current";
    const validityDays = 30;

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "every_n_days", validityDays);
    await seedPatient(orgStr, userStr, patientId);

    // Prior appointment with a signed doc signed 1 day ago (well within 30-day window)
    await seedAppointment(orgStr, userStr, priorApptId, patientId, treatmentId, "completed");
    await seedSignedDoc(orgStr, templateId, priorApptId, {
      signedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    });

    await seedAppointment(orgStr, userStr, currentApptId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, currentApptId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, currentApptId)).toBe(0);
  });

  test("generates document when the prior signed copy has expired beyond validityDays", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-end-c";
    const treatmentId = "treat-end-c";
    const patientId = "patient-end-c";
    const priorApptId = "appt-end-c-prior";
    const currentApptId = "appt-end-c-current";
    const validityDays = 30;

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "every_n_days", validityDays);
    await seedPatient(orgStr, userStr, patientId);

    // Prior appointment with a signed doc signed 31 days ago (expired)
    await seedAppointment(orgStr, userStr, priorApptId, patientId, treatmentId, "completed");
    await seedSignedDoc(orgStr, templateId, priorApptId, {
      signedAt: Date.now() - (validityDays + 1) * 24 * 60 * 60 * 1000,
    });

    await seedAppointment(orgStr, userStr, currentApptId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, currentApptId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, currentApptId)).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// frequency: on_expiry
// (same skip logic as every_n_days; tests focus on the explicit expiresAt field
// written by migration 00142 rather than the signedAt-based fallback)
// ---------------------------------------------------------------------------

describe("frequency: on_expiry", () => {
  test("generates document when patient has no prior signed document", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-oe-a";
    const treatmentId = "treat-oe-a";
    const patientId = "patient-oe-a";
    const appointmentId = "appt-oe-a";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "on_expiry", 90);
    await seedPatient(orgStr, userStr, patientId);
    await seedAppointment(orgStr, userStr, appointmentId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, appointmentId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, appointmentId)).toBe(1);
  });

  test("skips document when patient has a signed copy with an explicit expiresAt in the future", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-oe-b";
    const treatmentId = "treat-oe-b";
    const patientId = "patient-oe-b";
    const priorApptId = "appt-oe-b-prior";
    const currentApptId = "appt-oe-b-current";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "on_expiry", 90);
    await seedPatient(orgStr, userStr, patientId);

    await seedAppointment(orgStr, userStr, priorApptId, patientId, treatmentId, "completed");
    // expiresAt explicitly set 60 days in the future
    await seedSignedDoc(orgStr, templateId, priorApptId, {
      signedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
      expiresAt: Date.now() + 60 * 24 * 60 * 60 * 1000,
    });

    await seedAppointment(orgStr, userStr, currentApptId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, currentApptId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, currentApptId)).toBe(0);
  });

  test("generates document when expiresAt has already passed", async () => {
    const t = createTestCtx();
    const { organizationId, userId } = await seedTestUser(t);
    const orgStr = String(organizationId);
    const userStr = String(userId);

    const templateId = "tmpl-oe-c";
    const treatmentId = "treat-oe-c";
    const patientId = "patient-oe-c";
    const priorApptId = "appt-oe-c-prior";
    const currentApptId = "appt-oe-c-current";

    await seedTemplate(orgStr, userStr, templateId);
    await seedTreatment(orgStr, userStr, treatmentId, templateId, "on_expiry", 90);
    await seedPatient(orgStr, userStr, patientId);

    await seedAppointment(orgStr, userStr, priorApptId, patientId, treatmentId, "completed");
    // expiresAt explicitly set 1 day in the past
    await seedSignedDoc(orgStr, templateId, priorApptId, {
      signedAt: Date.now() - 91 * 24 * 60 * 60 * 1000,
      expiresAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    });

    await seedAppointment(orgStr, userStr, currentApptId, patientId, treatmentId, "scheduled");

    await runGenerate(t, organizationId, currentApptId, treatmentId, patientId, userStr);

    expect(await countDocumentsForAppointment(orgStr, templateId, currentApptId)).toBe(1);
  });
});
