/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutRouteImport } from './routes/_app/login/_layout'
import { Route as AppLoginLayoutIndexRouteImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthOnboardingLayoutRouteImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardLayoutRouteImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameRouteImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutSettingsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutCheckoutRouteImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthDashboardLayoutSettingsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthDashboardLayoutPipelinesIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.pipelines.index'
import { Route as AppAuthDashboardLayoutLeadsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.leads.index'
import { Route as AppAuthDashboardLayoutDocumentsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.documents.index'
import { Route as AppAuthDashboardLayoutContactsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.contacts.index'
import { Route as AppAuthDashboardLayoutCompaniesIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.companies.index'
import { Route as AppAuthDashboardLayoutSettingsTeamRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.team'
import { Route as AppAuthDashboardLayoutSettingsPipelinesRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.pipelines'
import { Route as AppAuthDashboardLayoutSettingsCustomFieldsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.custom-fields'
import { Route as AppAuthDashboardLayoutSettingsBillingRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'
import { Route as AppAuthDashboardLayoutLeadsNewRouteImport } from './routes/_app/_auth/dashboard/_layout.leads.new'
import { Route as AppAuthDashboardLayoutLeadsLeadIdRouteImport } from './routes/_app/_auth/dashboard/_layout.leads.$leadId'
import { Route as AppAuthDashboardLayoutDocumentsNewRouteImport } from './routes/_app/_auth/dashboard/_layout.documents.new'
import { Route as AppAuthDashboardLayoutDocumentsDocumentIdRouteImport } from './routes/_app/_auth/dashboard/_layout.documents.$documentId'
import { Route as AppAuthDashboardLayoutContactsNewRouteImport } from './routes/_app/_auth/dashboard/_layout.contacts.new'
import { Route as AppAuthDashboardLayoutContactsContactIdRouteImport } from './routes/_app/_auth/dashboard/_layout.contacts.$contactId'
import { Route as AppAuthDashboardLayoutCompaniesNewRouteImport } from './routes/_app/_auth/dashboard/_layout.companies.new'
import { Route as AppAuthDashboardLayoutCompaniesCompanyIdRouteImport } from './routes/_app/_auth/dashboard/_layout.companies.$companyId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutRoute = AppLoginLayoutRouteImport.update({
  id: '/login/_layout',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutIndexRoute = AppLoginLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)
const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutPipelinesIndexRoute =
  AppAuthDashboardLayoutPipelinesIndexRouteImport.update({
    id: '/pipelines/',
    path: '/pipelines/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutLeadsIndexRoute =
  AppAuthDashboardLayoutLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutDocumentsIndexRoute =
  AppAuthDashboardLayoutDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutContactsIndexRoute =
  AppAuthDashboardLayoutContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCompaniesIndexRoute =
  AppAuthDashboardLayoutCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsTeamRoute =
  AppAuthDashboardLayoutSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutSettingsPipelinesRoute =
  AppAuthDashboardLayoutSettingsPipelinesRouteImport.update({
    id: '/pipelines',
    path: '/pipelines',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutSettingsCustomFieldsRoute =
  AppAuthDashboardLayoutSettingsCustomFieldsRouteImport.update({
    id: '/custom-fields',
    path: '/custom-fields',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutLeadsNewRoute =
  AppAuthDashboardLayoutLeadsNewRouteImport.update({
    id: '/leads/new',
    path: '/leads/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutLeadsLeadIdRoute =
  AppAuthDashboardLayoutLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutDocumentsNewRoute =
  AppAuthDashboardLayoutDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutDocumentsDocumentIdRoute =
  AppAuthDashboardLayoutDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutContactsNewRoute =
  AppAuthDashboardLayoutContactsNewRouteImport.update({
    id: '/contacts/new',
    path: '/contacts/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutContactsContactIdRoute =
  AppAuthDashboardLayoutContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCompaniesNewRoute =
  AppAuthDashboardLayoutCompaniesNewRouteImport.update({
    id: '/companies/new',
    path: '/companies/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCompaniesCompanyIdRoute =
  AppAuthDashboardLayoutCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/companies/$companyId': typeof AppAuthDashboardLayoutCompaniesCompanyIdRoute
  '/dashboard/companies/new': typeof AppAuthDashboardLayoutCompaniesNewRoute
  '/dashboard/contacts/$contactId': typeof AppAuthDashboardLayoutContactsContactIdRoute
  '/dashboard/contacts/new': typeof AppAuthDashboardLayoutContactsNewRoute
  '/dashboard/documents/$documentId': typeof AppAuthDashboardLayoutDocumentsDocumentIdRoute
  '/dashboard/documents/new': typeof AppAuthDashboardLayoutDocumentsNewRoute
  '/dashboard/leads/$leadId': typeof AppAuthDashboardLayoutLeadsLeadIdRoute
  '/dashboard/leads/new': typeof AppAuthDashboardLayoutLeadsNewRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/custom-fields': typeof AppAuthDashboardLayoutSettingsCustomFieldsRoute
  '/dashboard/settings/pipelines': typeof AppAuthDashboardLayoutSettingsPipelinesRoute
  '/dashboard/settings/team': typeof AppAuthDashboardLayoutSettingsTeamRoute
  '/dashboard/companies/': typeof AppAuthDashboardLayoutCompaniesIndexRoute
  '/dashboard/contacts/': typeof AppAuthDashboardLayoutContactsIndexRoute
  '/dashboard/documents/': typeof AppAuthDashboardLayoutDocumentsIndexRoute
  '/dashboard/leads/': typeof AppAuthDashboardLayoutLeadsIndexRoute
  '/dashboard/pipelines/': typeof AppAuthDashboardLayoutPipelinesIndexRoute
  '/dashboard/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/companies/$companyId': typeof AppAuthDashboardLayoutCompaniesCompanyIdRoute
  '/dashboard/companies/new': typeof AppAuthDashboardLayoutCompaniesNewRoute
  '/dashboard/contacts/$contactId': typeof AppAuthDashboardLayoutContactsContactIdRoute
  '/dashboard/contacts/new': typeof AppAuthDashboardLayoutContactsNewRoute
  '/dashboard/documents/$documentId': typeof AppAuthDashboardLayoutDocumentsDocumentIdRoute
  '/dashboard/documents/new': typeof AppAuthDashboardLayoutDocumentsNewRoute
  '/dashboard/leads/$leadId': typeof AppAuthDashboardLayoutLeadsLeadIdRoute
  '/dashboard/leads/new': typeof AppAuthDashboardLayoutLeadsNewRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/custom-fields': typeof AppAuthDashboardLayoutSettingsCustomFieldsRoute
  '/dashboard/settings/pipelines': typeof AppAuthDashboardLayoutSettingsPipelinesRoute
  '/dashboard/settings/team': typeof AppAuthDashboardLayoutSettingsTeamRoute
  '/dashboard/companies': typeof AppAuthDashboardLayoutCompaniesIndexRoute
  '/dashboard/contacts': typeof AppAuthDashboardLayoutContactsIndexRoute
  '/dashboard/documents': typeof AppAuthDashboardLayoutDocumentsIndexRoute
  '/dashboard/leads': typeof AppAuthDashboardLayoutLeadsIndexRoute
  '/dashboard/pipelines': typeof AppAuthDashboardLayoutPipelinesIndexRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/onboarding/_layout/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/companies/$companyId': typeof AppAuthDashboardLayoutCompaniesCompanyIdRoute
  '/_app/_auth/dashboard/_layout/companies/new': typeof AppAuthDashboardLayoutCompaniesNewRoute
  '/_app/_auth/dashboard/_layout/contacts/$contactId': typeof AppAuthDashboardLayoutContactsContactIdRoute
  '/_app/_auth/dashboard/_layout/contacts/new': typeof AppAuthDashboardLayoutContactsNewRoute
  '/_app/_auth/dashboard/_layout/documents/$documentId': typeof AppAuthDashboardLayoutDocumentsDocumentIdRoute
  '/_app/_auth/dashboard/_layout/documents/new': typeof AppAuthDashboardLayoutDocumentsNewRoute
  '/_app/_auth/dashboard/_layout/leads/$leadId': typeof AppAuthDashboardLayoutLeadsLeadIdRoute
  '/_app/_auth/dashboard/_layout/leads/new': typeof AppAuthDashboardLayoutLeadsNewRoute
  '/_app/_auth/dashboard/_layout/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/_app/_auth/dashboard/_layout/settings/custom-fields': typeof AppAuthDashboardLayoutSettingsCustomFieldsRoute
  '/_app/_auth/dashboard/_layout/settings/pipelines': typeof AppAuthDashboardLayoutSettingsPipelinesRoute
  '/_app/_auth/dashboard/_layout/settings/team': typeof AppAuthDashboardLayoutSettingsTeamRoute
  '/_app/_auth/dashboard/_layout/companies/': typeof AppAuthDashboardLayoutCompaniesIndexRoute
  '/_app/_auth/dashboard/_layout/contacts/': typeof AppAuthDashboardLayoutContactsIndexRoute
  '/_app/_auth/dashboard/_layout/documents/': typeof AppAuthDashboardLayoutDocumentsIndexRoute
  '/_app/_auth/dashboard/_layout/leads/': typeof AppAuthDashboardLayoutLeadsIndexRoute
  '/_app/_auth/dashboard/_layout/pipelines/': typeof AppAuthDashboardLayoutPipelinesIndexRoute
  '/_app/_auth/dashboard/_layout/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/login/'
    | '/dashboard/checkout'
    | '/dashboard/settings'
    | '/onboarding/username'
    | '/dashboard/'
    | '/dashboard/companies/$companyId'
    | '/dashboard/companies/new'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts/new'
    | '/dashboard/documents/$documentId'
    | '/dashboard/documents/new'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/new'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/custom-fields'
    | '/dashboard/settings/pipelines'
    | '/dashboard/settings/team'
    | '/dashboard/companies/'
    | '/dashboard/contacts/'
    | '/dashboard/documents/'
    | '/dashboard/leads/'
    | '/dashboard/pipelines/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/dashboard/checkout'
    | '/onboarding/username'
    | '/dashboard'
    | '/dashboard/companies/$companyId'
    | '/dashboard/companies/new'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts/new'
    | '/dashboard/documents/$documentId'
    | '/dashboard/documents/new'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/new'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/custom-fields'
    | '/dashboard/settings/pipelines'
    | '/dashboard/settings/team'
    | '/dashboard/companies'
    | '/dashboard/contacts'
    | '/dashboard/documents'
    | '/dashboard/leads'
    | '/dashboard/pipelines'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/login/_layout'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/checkout'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/onboarding/_layout/username'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/dashboard/_layout/companies/$companyId'
    | '/_app/_auth/dashboard/_layout/companies/new'
    | '/_app/_auth/dashboard/_layout/contacts/$contactId'
    | '/_app/_auth/dashboard/_layout/contacts/new'
    | '/_app/_auth/dashboard/_layout/documents/$documentId'
    | '/_app/_auth/dashboard/_layout/documents/new'
    | '/_app/_auth/dashboard/_layout/leads/$leadId'
    | '/_app/_auth/dashboard/_layout/leads/new'
    | '/_app/_auth/dashboard/_layout/settings/billing'
    | '/_app/_auth/dashboard/_layout/settings/custom-fields'
    | '/_app/_auth/dashboard/_layout/settings/pipelines'
    | '/_app/_auth/dashboard/_layout/settings/team'
    | '/_app/_auth/dashboard/_layout/companies/'
    | '/_app/_auth/dashboard/_layout/contacts/'
    | '/_app/_auth/dashboard/_layout/documents/'
    | '/_app/_auth/dashboard/_layout/leads/'
    | '/_app/_auth/dashboard/_layout/pipelines/'
    | '/_app/_auth/dashboard/_layout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexRouteImport
      parentRoute: typeof AppLoginLayoutRoute
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameRouteImport
      parentRoute: typeof AppAuthOnboardingLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/pipelines/': {
      id: '/_app/_auth/dashboard/_layout/pipelines/'
      path: '/pipelines'
      fullPath: '/dashboard/pipelines/'
      preLoaderRoute: typeof AppAuthDashboardLayoutPipelinesIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/leads/': {
      id: '/_app/_auth/dashboard/_layout/leads/'
      path: '/leads'
      fullPath: '/dashboard/leads/'
      preLoaderRoute: typeof AppAuthDashboardLayoutLeadsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/documents/': {
      id: '/_app/_auth/dashboard/_layout/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents/'
      preLoaderRoute: typeof AppAuthDashboardLayoutDocumentsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/contacts/': {
      id: '/_app/_auth/dashboard/_layout/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts/'
      preLoaderRoute: typeof AppAuthDashboardLayoutContactsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/companies/': {
      id: '/_app/_auth/dashboard/_layout/companies/'
      path: '/companies'
      fullPath: '/dashboard/companies/'
      preLoaderRoute: typeof AppAuthDashboardLayoutCompaniesIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings/team': {
      id: '/_app/_auth/dashboard/_layout/settings/team'
      path: '/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsTeamRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/settings/pipelines': {
      id: '/_app/_auth/dashboard/_layout/settings/pipelines'
      path: '/pipelines'
      fullPath: '/dashboard/settings/pipelines'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsPipelinesRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/settings/custom-fields': {
      id: '/_app/_auth/dashboard/_layout/settings/custom-fields'
      path: '/custom-fields'
      fullPath: '/dashboard/settings/custom-fields'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsCustomFieldsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/leads/new': {
      id: '/_app/_auth/dashboard/_layout/leads/new'
      path: '/leads/new'
      fullPath: '/dashboard/leads/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutLeadsNewRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/leads/$leadId': {
      id: '/_app/_auth/dashboard/_layout/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/dashboard/leads/$leadId'
      preLoaderRoute: typeof AppAuthDashboardLayoutLeadsLeadIdRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/documents/new': {
      id: '/_app/_auth/dashboard/_layout/documents/new'
      path: '/documents/new'
      fullPath: '/dashboard/documents/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutDocumentsNewRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/documents/$documentId': {
      id: '/_app/_auth/dashboard/_layout/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/dashboard/documents/$documentId'
      preLoaderRoute: typeof AppAuthDashboardLayoutDocumentsDocumentIdRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/contacts/new': {
      id: '/_app/_auth/dashboard/_layout/contacts/new'
      path: '/contacts/new'
      fullPath: '/dashboard/contacts/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutContactsNewRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/contacts/$contactId': {
      id: '/_app/_auth/dashboard/_layout/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/dashboard/contacts/$contactId'
      preLoaderRoute: typeof AppAuthDashboardLayoutContactsContactIdRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/companies/new': {
      id: '/_app/_auth/dashboard/_layout/companies/new'
      path: '/companies/new'
      fullPath: '/dashboard/companies/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutCompaniesNewRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/companies/$companyId': {
      id: '/_app/_auth/dashboard/_layout/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/dashboard/companies/$companyId'
      preLoaderRoute: typeof AppAuthDashboardLayoutCompaniesCompanyIdRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
  }
}

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsBillingRoute: typeof AppAuthDashboardLayoutSettingsBillingRoute
  AppAuthDashboardLayoutSettingsCustomFieldsRoute: typeof AppAuthDashboardLayoutSettingsCustomFieldsRoute
  AppAuthDashboardLayoutSettingsPipelinesRoute: typeof AppAuthDashboardLayoutSettingsPipelinesRoute
  AppAuthDashboardLayoutSettingsTeamRoute: typeof AppAuthDashboardLayoutSettingsTeamRoute
  AppAuthDashboardLayoutSettingsIndexRoute: typeof AppAuthDashboardLayoutSettingsIndexRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsBillingRoute:
      AppAuthDashboardLayoutSettingsBillingRoute,
    AppAuthDashboardLayoutSettingsCustomFieldsRoute:
      AppAuthDashboardLayoutSettingsCustomFieldsRoute,
    AppAuthDashboardLayoutSettingsPipelinesRoute:
      AppAuthDashboardLayoutSettingsPipelinesRoute,
    AppAuthDashboardLayoutSettingsTeamRoute:
      AppAuthDashboardLayoutSettingsTeamRoute,
    AppAuthDashboardLayoutSettingsIndexRoute:
      AppAuthDashboardLayoutSettingsIndexRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutCheckoutRoute: typeof AppAuthDashboardLayoutCheckoutRoute
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
  AppAuthDashboardLayoutCompaniesCompanyIdRoute: typeof AppAuthDashboardLayoutCompaniesCompanyIdRoute
  AppAuthDashboardLayoutCompaniesNewRoute: typeof AppAuthDashboardLayoutCompaniesNewRoute
  AppAuthDashboardLayoutContactsContactIdRoute: typeof AppAuthDashboardLayoutContactsContactIdRoute
  AppAuthDashboardLayoutContactsNewRoute: typeof AppAuthDashboardLayoutContactsNewRoute
  AppAuthDashboardLayoutDocumentsDocumentIdRoute: typeof AppAuthDashboardLayoutDocumentsDocumentIdRoute
  AppAuthDashboardLayoutDocumentsNewRoute: typeof AppAuthDashboardLayoutDocumentsNewRoute
  AppAuthDashboardLayoutLeadsLeadIdRoute: typeof AppAuthDashboardLayoutLeadsLeadIdRoute
  AppAuthDashboardLayoutLeadsNewRoute: typeof AppAuthDashboardLayoutLeadsNewRoute
  AppAuthDashboardLayoutCompaniesIndexRoute: typeof AppAuthDashboardLayoutCompaniesIndexRoute
  AppAuthDashboardLayoutContactsIndexRoute: typeof AppAuthDashboardLayoutContactsIndexRoute
  AppAuthDashboardLayoutDocumentsIndexRoute: typeof AppAuthDashboardLayoutDocumentsIndexRoute
  AppAuthDashboardLayoutLeadsIndexRoute: typeof AppAuthDashboardLayoutLeadsIndexRoute
  AppAuthDashboardLayoutPipelinesIndexRoute: typeof AppAuthDashboardLayoutPipelinesIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutCheckoutRoute: AppAuthDashboardLayoutCheckoutRoute,
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
    AppAuthDashboardLayoutCompaniesCompanyIdRoute:
      AppAuthDashboardLayoutCompaniesCompanyIdRoute,
    AppAuthDashboardLayoutCompaniesNewRoute:
      AppAuthDashboardLayoutCompaniesNewRoute,
    AppAuthDashboardLayoutContactsContactIdRoute:
      AppAuthDashboardLayoutContactsContactIdRoute,
    AppAuthDashboardLayoutContactsNewRoute:
      AppAuthDashboardLayoutContactsNewRoute,
    AppAuthDashboardLayoutDocumentsDocumentIdRoute:
      AppAuthDashboardLayoutDocumentsDocumentIdRoute,
    AppAuthDashboardLayoutDocumentsNewRoute:
      AppAuthDashboardLayoutDocumentsNewRoute,
    AppAuthDashboardLayoutLeadsLeadIdRoute:
      AppAuthDashboardLayoutLeadsLeadIdRoute,
    AppAuthDashboardLayoutLeadsNewRoute: AppAuthDashboardLayoutLeadsNewRoute,
    AppAuthDashboardLayoutCompaniesIndexRoute:
      AppAuthDashboardLayoutCompaniesIndexRoute,
    AppAuthDashboardLayoutContactsIndexRoute:
      AppAuthDashboardLayoutContactsIndexRoute,
    AppAuthDashboardLayoutDocumentsIndexRoute:
      AppAuthDashboardLayoutDocumentsIndexRoute,
    AppAuthDashboardLayoutLeadsIndexRoute:
      AppAuthDashboardLayoutLeadsIndexRoute,
    AppAuthDashboardLayoutPipelinesIndexRoute:
      AppAuthDashboardLayoutPipelinesIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutUsernameRoute: typeof AppAuthOnboardingLayoutUsernameRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutUsernameRoute: AppAuthOnboardingLayoutUsernameRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
