/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppAuthImport } from './routes/_app/_auth'
import { Route as AppPatientLoginImport } from './routes/_app/patient/login'
import { Route as AppPatientLayoutImport } from './routes/_app/patient/_layout'
import { Route as AppLoginLayoutImport } from './routes/_app/login/_layout'
import { Route as AppInviteTokenImport } from './routes/_app/invite.$token'
import { Route as AppPatientLayoutIndexImport } from './routes/_app/patient/_layout.index'
import { Route as AppLoginLayoutIndexImport } from './routes/_app/login/_layout.index'
import { Route as AppPatientLayoutProfileImport } from './routes/_app/patient/_layout.profile'
import { Route as AppPatientLayoutDocumentsImport } from './routes/_app/patient/_layout.documents'
import { Route as AppPatientLayoutAppointmentsImport } from './routes/_app/patient/_layout.appointments'
import { Route as AppAuthOnboardingLayoutImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardLayoutImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutSettingsImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutCheckoutImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthDashboardLayoutSettingsIndexImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthDashboardLayoutProductsIndexImport } from './routes/_app/_auth/dashboard/_layout.products.index'
import { Route as AppAuthDashboardLayoutPipelinesIndexImport } from './routes/_app/_auth/dashboard/_layout.pipelines.index'
import { Route as AppAuthDashboardLayoutLeadsIndexImport } from './routes/_app/_auth/dashboard/_layout.leads.index'
import { Route as AppAuthDashboardLayoutInboxIndexImport } from './routes/_app/_auth/dashboard/_layout.inbox.index'
import { Route as AppAuthDashboardLayoutGabinetIndexImport } from './routes/_app/_auth/dashboard/_layout.gabinet.index'
import { Route as AppAuthDashboardLayoutDocumentsIndexImport } from './routes/_app/_auth/dashboard/_layout.documents.index'
import { Route as AppAuthDashboardLayoutContactsIndexImport } from './routes/_app/_auth/dashboard/_layout.contacts.index'
import { Route as AppAuthDashboardLayoutCompaniesIndexImport } from './routes/_app/_auth/dashboard/_layout.companies.index'
import { Route as AppAuthDashboardLayoutCallsIndexImport } from './routes/_app/_auth/dashboard/_layout.calls.index'
import { Route as AppAuthDashboardLayoutActivitiesIndexImport } from './routes/_app/_auth/dashboard/_layout.activities.index'
import { Route as AppAuthDashboardLayoutSettingsTeamImport } from './routes/_app/_auth/dashboard/_layout.settings.team'
import { Route as AppAuthDashboardLayoutSettingsSourcesImport } from './routes/_app/_auth/dashboard/_layout.settings.sources'
import { Route as AppAuthDashboardLayoutSettingsPipelinesImport } from './routes/_app/_auth/dashboard/_layout.settings.pipelines'
import { Route as AppAuthDashboardLayoutSettingsPermissionsImport } from './routes/_app/_auth/dashboard/_layout.settings.permissions'
import { Route as AppAuthDashboardLayoutSettingsOrganizationImport } from './routes/_app/_auth/dashboard/_layout.settings.organization'
import { Route as AppAuthDashboardLayoutSettingsLostReasonsImport } from './routes/_app/_auth/dashboard/_layout.settings.lost-reasons'
import { Route as AppAuthDashboardLayoutSettingsIntegrationsImport } from './routes/_app/_auth/dashboard/_layout.settings.integrations'
import { Route as AppAuthDashboardLayoutSettingsEmailImport } from './routes/_app/_auth/dashboard/_layout.settings.email'
import { Route as AppAuthDashboardLayoutSettingsCustomFieldsImport } from './routes/_app/_auth/dashboard/_layout.settings.custom-fields'
import { Route as AppAuthDashboardLayoutSettingsBillingImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'
import { Route as AppAuthDashboardLayoutSettingsActivityTypesImport } from './routes/_app/_auth/dashboard/_layout.settings.activity-types'
import { Route as AppAuthDashboardLayoutLeadsNewImport } from './routes/_app/_auth/dashboard/_layout.leads.new'
import { Route as AppAuthDashboardLayoutLeadsLeadIdImport } from './routes/_app/_auth/dashboard/_layout.leads.$leadId'
import { Route as AppAuthDashboardLayoutGabinetReportsImport } from './routes/_app/_auth/dashboard/_layout.gabinet.reports'
import { Route as AppAuthDashboardLayoutDocumentsNewImport } from './routes/_app/_auth/dashboard/_layout.documents.new'
import { Route as AppAuthDashboardLayoutDocumentsDocumentIdImport } from './routes/_app/_auth/dashboard/_layout.documents.$documentId'
import { Route as AppAuthDashboardLayoutContactsNewImport } from './routes/_app/_auth/dashboard/_layout.contacts.new'
import { Route as AppAuthDashboardLayoutContactsContactIdImport } from './routes/_app/_auth/dashboard/_layout.contacts.$contactId'
import { Route as AppAuthDashboardLayoutCompaniesNewImport } from './routes/_app/_auth/dashboard/_layout.companies.new'
import { Route as AppAuthDashboardLayoutCompaniesCompanyIdImport } from './routes/_app/_auth/dashboard/_layout.companies.$companyId'
import { Route as AppAuthDashboardLayoutGabinetTreatmentsIndexImport } from './routes/_app/_auth/dashboard/_layout.gabinet.treatments.index'
import { Route as AppAuthDashboardLayoutGabinetPatientsIndexImport } from './routes/_app/_auth/dashboard/_layout.gabinet.patients.index'
import { Route as AppAuthDashboardLayoutGabinetPackagesIndexImport } from './routes/_app/_auth/dashboard/_layout.gabinet.packages.index'
import { Route as AppAuthDashboardLayoutGabinetEmployeesIndexImport } from './routes/_app/_auth/dashboard/_layout.gabinet.employees.index'
import { Route as AppAuthDashboardLayoutGabinetDocumentsIndexImport } from './routes/_app/_auth/dashboard/_layout.gabinet.documents.index'
import { Route as AppAuthDashboardLayoutGabinetCalendarIndexImport } from './routes/_app/_auth/dashboard/_layout.gabinet.calendar.index'
import { Route as AppAuthDashboardLayoutGabinetSettingsSchedulingImport } from './routes/_app/_auth/dashboard/_layout.gabinet.settings.scheduling'
import { Route as AppAuthDashboardLayoutGabinetSettingsLeavesImport } from './routes/_app/_auth/dashboard/_layout.gabinet.settings.leaves'
import { Route as AppAuthDashboardLayoutGabinetSettingsLeaveTypesImport } from './routes/_app/_auth/dashboard/_layout.gabinet.settings.leave-types'
import { Route as AppAuthDashboardLayoutGabinetSettingsLeaveBalancesImport } from './routes/_app/_auth/dashboard/_layout.gabinet.settings.leave-balances'
import { Route as AppAuthDashboardLayoutGabinetSettingsDocumentTemplatesImport } from './routes/_app/_auth/dashboard/_layout.gabinet.settings.document-templates'
import { Route as AppAuthDashboardLayoutGabinetPatientsPatientIdImport } from './routes/_app/_auth/dashboard/_layout.gabinet.patients.$patientId'
import { Route as AppAuthDashboardLayoutGabinetEmployeesEmployeeIdImport } from './routes/_app/_auth/dashboard/_layout.gabinet.employees.$employeeId'

// Create Virtual Routes

const AppPatientImport = createFileRoute('/_app/patient')()
const AppLoginImport = createFileRoute('/_app/login')()
const AppAuthOnboardingImport = createFileRoute('/_app/_auth/onboarding')()
const AppAuthDashboardImport = createFileRoute('/_app/_auth/dashboard')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppPatientRoute = AppPatientImport.update({
  path: '/patient',
  getParentRoute: () => AppRoute,
} as any)

const AppLoginRoute = AppLoginImport.update({
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthRoute = AppAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthOnboardingRoute = AppAuthOnboardingImport.update({
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppAuthDashboardRoute = AppAuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppPatientLoginRoute = AppPatientLoginImport.update({
  path: '/login',
  getParentRoute: () => AppPatientRoute,
} as any)

const AppPatientLayoutRoute = AppPatientLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppPatientRoute,
} as any)

const AppLoginLayoutRoute = AppLoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppLoginRoute,
} as any)

const AppInviteTokenRoute = AppInviteTokenImport.update({
  path: '/invite/$token',
  getParentRoute: () => AppRoute,
} as any)

const AppPatientLayoutIndexRoute = AppPatientLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => AppPatientLayoutRoute,
} as any)

const AppLoginLayoutIndexRoute = AppLoginLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)

const AppPatientLayoutProfileRoute = AppPatientLayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => AppPatientLayoutRoute,
} as any)

const AppPatientLayoutDocumentsRoute = AppPatientLayoutDocumentsImport.update({
  path: '/documents',
  getParentRoute: () => AppPatientLayoutRoute,
} as any)

const AppPatientLayoutAppointmentsRoute =
  AppPatientLayoutAppointmentsImport.update({
    path: '/appointments',
    getParentRoute: () => AppPatientLayoutRoute,
  } as any)

const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthOnboardingRoute,
} as any)

const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthDashboardRoute,
} as any)

const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameImport.update({
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)

const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsImport.update({
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutImport.update({
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexImport.update({
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutProductsIndexRoute =
  AppAuthDashboardLayoutProductsIndexImport.update({
    path: '/products/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutPipelinesIndexRoute =
  AppAuthDashboardLayoutPipelinesIndexImport.update({
    path: '/pipelines/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutLeadsIndexRoute =
  AppAuthDashboardLayoutLeadsIndexImport.update({
    path: '/leads/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutInboxIndexRoute =
  AppAuthDashboardLayoutInboxIndexImport.update({
    path: '/inbox/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetIndexRoute =
  AppAuthDashboardLayoutGabinetIndexImport.update({
    path: '/gabinet/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutDocumentsIndexRoute =
  AppAuthDashboardLayoutDocumentsIndexImport.update({
    path: '/documents/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutContactsIndexRoute =
  AppAuthDashboardLayoutContactsIndexImport.update({
    path: '/contacts/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutCompaniesIndexRoute =
  AppAuthDashboardLayoutCompaniesIndexImport.update({
    path: '/companies/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutCallsIndexRoute =
  AppAuthDashboardLayoutCallsIndexImport.update({
    path: '/calls/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutActivitiesIndexRoute =
  AppAuthDashboardLayoutActivitiesIndexImport.update({
    path: '/activities/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutSettingsTeamRoute =
  AppAuthDashboardLayoutSettingsTeamImport.update({
    path: '/team',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsSourcesRoute =
  AppAuthDashboardLayoutSettingsSourcesImport.update({
    path: '/sources',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsPipelinesRoute =
  AppAuthDashboardLayoutSettingsPipelinesImport.update({
    path: '/pipelines',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsPermissionsRoute =
  AppAuthDashboardLayoutSettingsPermissionsImport.update({
    path: '/permissions',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsOrganizationRoute =
  AppAuthDashboardLayoutSettingsOrganizationImport.update({
    path: '/organization',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsLostReasonsRoute =
  AppAuthDashboardLayoutSettingsLostReasonsImport.update({
    path: '/lost-reasons',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsIntegrationsRoute =
  AppAuthDashboardLayoutSettingsIntegrationsImport.update({
    path: '/integrations',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsEmailRoute =
  AppAuthDashboardLayoutSettingsEmailImport.update({
    path: '/email',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsCustomFieldsRoute =
  AppAuthDashboardLayoutSettingsCustomFieldsImport.update({
    path: '/custom-fields',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingImport.update({
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsActivityTypesRoute =
  AppAuthDashboardLayoutSettingsActivityTypesImport.update({
    path: '/activity-types',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutLeadsNewRoute =
  AppAuthDashboardLayoutLeadsNewImport.update({
    path: '/leads/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutLeadsLeadIdRoute =
  AppAuthDashboardLayoutLeadsLeadIdImport.update({
    path: '/leads/$leadId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetReportsRoute =
  AppAuthDashboardLayoutGabinetReportsImport.update({
    path: '/gabinet/reports',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutDocumentsNewRoute =
  AppAuthDashboardLayoutDocumentsNewImport.update({
    path: '/documents/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutDocumentsDocumentIdRoute =
  AppAuthDashboardLayoutDocumentsDocumentIdImport.update({
    path: '/documents/$documentId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutContactsNewRoute =
  AppAuthDashboardLayoutContactsNewImport.update({
    path: '/contacts/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutContactsContactIdRoute =
  AppAuthDashboardLayoutContactsContactIdImport.update({
    path: '/contacts/$contactId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutCompaniesNewRoute =
  AppAuthDashboardLayoutCompaniesNewImport.update({
    path: '/companies/new',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutCompaniesCompanyIdRoute =
  AppAuthDashboardLayoutCompaniesCompanyIdImport.update({
    path: '/companies/$companyId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetTreatmentsIndexRoute =
  AppAuthDashboardLayoutGabinetTreatmentsIndexImport.update({
    path: '/gabinet/treatments/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetPatientsIndexRoute =
  AppAuthDashboardLayoutGabinetPatientsIndexImport.update({
    path: '/gabinet/patients/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetPackagesIndexRoute =
  AppAuthDashboardLayoutGabinetPackagesIndexImport.update({
    path: '/gabinet/packages/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetEmployeesIndexRoute =
  AppAuthDashboardLayoutGabinetEmployeesIndexImport.update({
    path: '/gabinet/employees/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetDocumentsIndexRoute =
  AppAuthDashboardLayoutGabinetDocumentsIndexImport.update({
    path: '/gabinet/documents/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetCalendarIndexRoute =
  AppAuthDashboardLayoutGabinetCalendarIndexImport.update({
    path: '/gabinet/calendar/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetSettingsSchedulingRoute =
  AppAuthDashboardLayoutGabinetSettingsSchedulingImport.update({
    path: '/gabinet/settings/scheduling',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetSettingsLeavesRoute =
  AppAuthDashboardLayoutGabinetSettingsLeavesImport.update({
    path: '/gabinet/settings/leaves',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetSettingsLeaveTypesRoute =
  AppAuthDashboardLayoutGabinetSettingsLeaveTypesImport.update({
    path: '/gabinet/settings/leave-types',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetSettingsLeaveBalancesRoute =
  AppAuthDashboardLayoutGabinetSettingsLeaveBalancesImport.update({
    path: '/gabinet/settings/leave-balances',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetSettingsDocumentTemplatesRoute =
  AppAuthDashboardLayoutGabinetSettingsDocumentTemplatesImport.update({
    path: '/gabinet/settings/document-templates',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetPatientsPatientIdRoute =
  AppAuthDashboardLayoutGabinetPatientsPatientIdImport.update({
    path: '/gabinet/patients/$patientId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutGabinetEmployeesEmployeeIdRoute =
  AppAuthDashboardLayoutGabinetEmployeesEmployeeIdImport.update({
    path: '/gabinet/employees/$employeeId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthImport
      parentRoute: typeof AppImport
    }
    '/_app/invite/$token': {
      id: '/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppInviteTokenImport
      parentRoute: typeof AppImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginImport
      parentRoute: typeof AppImport
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutImport
      parentRoute: typeof AppLoginRoute
    }
    '/_app/patient': {
      id: '/_app/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AppPatientImport
      parentRoute: typeof AppImport
    }
    '/_app/patient/_layout': {
      id: '/_app/patient/_layout'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AppPatientLayoutImport
      parentRoute: typeof AppPatientRoute
    }
    '/_app/patient/login': {
      id: '/_app/patient/login'
      path: '/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof AppPatientLoginImport
      parentRoute: typeof AppPatientImport
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutImport
      parentRoute: typeof AppAuthDashboardRoute
    }
    '/_app/_auth/onboarding': {
      id: '/_app/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutImport
      parentRoute: typeof AppAuthOnboardingRoute
    }
    '/_app/patient/_layout/appointments': {
      id: '/_app/patient/_layout/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof AppPatientLayoutAppointmentsImport
      parentRoute: typeof AppPatientLayoutImport
    }
    '/_app/patient/_layout/documents': {
      id: '/_app/patient/_layout/documents'
      path: '/documents'
      fullPath: '/patient/documents'
      preLoaderRoute: typeof AppPatientLayoutDocumentsImport
      parentRoute: typeof AppPatientLayoutImport
    }
    '/_app/patient/_layout/profile': {
      id: '/_app/patient/_layout/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AppPatientLayoutProfileImport
      parentRoute: typeof AppPatientLayoutImport
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexImport
      parentRoute: typeof AppLoginLayoutImport
    }
    '/_app/patient/_layout/': {
      id: '/_app/patient/_layout/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof AppPatientLayoutIndexImport
      parentRoute: typeof AppPatientLayoutImport
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameImport
      parentRoute: typeof AppAuthOnboardingLayoutImport
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/companies/$companyId': {
      id: '/_app/_auth/dashboard/_layout/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/dashboard/companies/$companyId'
      preLoaderRoute: typeof AppAuthDashboardLayoutCompaniesCompanyIdImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/companies/new': {
      id: '/_app/_auth/dashboard/_layout/companies/new'
      path: '/companies/new'
      fullPath: '/dashboard/companies/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutCompaniesNewImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/contacts/$contactId': {
      id: '/_app/_auth/dashboard/_layout/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/dashboard/contacts/$contactId'
      preLoaderRoute: typeof AppAuthDashboardLayoutContactsContactIdImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/contacts/new': {
      id: '/_app/_auth/dashboard/_layout/contacts/new'
      path: '/contacts/new'
      fullPath: '/dashboard/contacts/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutContactsNewImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/documents/$documentId': {
      id: '/_app/_auth/dashboard/_layout/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/dashboard/documents/$documentId'
      preLoaderRoute: typeof AppAuthDashboardLayoutDocumentsDocumentIdImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/documents/new': {
      id: '/_app/_auth/dashboard/_layout/documents/new'
      path: '/documents/new'
      fullPath: '/dashboard/documents/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutDocumentsNewImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/reports': {
      id: '/_app/_auth/dashboard/_layout/gabinet/reports'
      path: '/gabinet/reports'
      fullPath: '/dashboard/gabinet/reports'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetReportsImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/leads/$leadId': {
      id: '/_app/_auth/dashboard/_layout/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/dashboard/leads/$leadId'
      preLoaderRoute: typeof AppAuthDashboardLayoutLeadsLeadIdImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/leads/new': {
      id: '/_app/_auth/dashboard/_layout/leads/new'
      path: '/leads/new'
      fullPath: '/dashboard/leads/new'
      preLoaderRoute: typeof AppAuthDashboardLayoutLeadsNewImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/settings/activity-types': {
      id: '/_app/_auth/dashboard/_layout/settings/activity-types'
      path: '/activity-types'
      fullPath: '/dashboard/settings/activity-types'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsActivityTypesImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/custom-fields': {
      id: '/_app/_auth/dashboard/_layout/settings/custom-fields'
      path: '/custom-fields'
      fullPath: '/dashboard/settings/custom-fields'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsCustomFieldsImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/email': {
      id: '/_app/_auth/dashboard/_layout/settings/email'
      path: '/email'
      fullPath: '/dashboard/settings/email'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsEmailImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/integrations': {
      id: '/_app/_auth/dashboard/_layout/settings/integrations'
      path: '/integrations'
      fullPath: '/dashboard/settings/integrations'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIntegrationsImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/lost-reasons': {
      id: '/_app/_auth/dashboard/_layout/settings/lost-reasons'
      path: '/lost-reasons'
      fullPath: '/dashboard/settings/lost-reasons'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsLostReasonsImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/organization': {
      id: '/_app/_auth/dashboard/_layout/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsOrganizationImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/permissions': {
      id: '/_app/_auth/dashboard/_layout/settings/permissions'
      path: '/permissions'
      fullPath: '/dashboard/settings/permissions'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsPermissionsImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/pipelines': {
      id: '/_app/_auth/dashboard/_layout/settings/pipelines'
      path: '/pipelines'
      fullPath: '/dashboard/settings/pipelines'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsPipelinesImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/sources': {
      id: '/_app/_auth/dashboard/_layout/settings/sources'
      path: '/sources'
      fullPath: '/dashboard/settings/sources'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsSourcesImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/team': {
      id: '/_app/_auth/dashboard/_layout/settings/team'
      path: '/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsTeamImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/activities/': {
      id: '/_app/_auth/dashboard/_layout/activities/'
      path: '/activities'
      fullPath: '/dashboard/activities'
      preLoaderRoute: typeof AppAuthDashboardLayoutActivitiesIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/calls/': {
      id: '/_app/_auth/dashboard/_layout/calls/'
      path: '/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof AppAuthDashboardLayoutCallsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/companies/': {
      id: '/_app/_auth/dashboard/_layout/companies/'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof AppAuthDashboardLayoutCompaniesIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/contacts/': {
      id: '/_app/_auth/dashboard/_layout/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof AppAuthDashboardLayoutContactsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/documents/': {
      id: '/_app/_auth/dashboard/_layout/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AppAuthDashboardLayoutDocumentsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/': {
      id: '/_app/_auth/dashboard/_layout/gabinet/'
      path: '/gabinet'
      fullPath: '/dashboard/gabinet'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/inbox/': {
      id: '/_app/_auth/dashboard/_layout/inbox/'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof AppAuthDashboardLayoutInboxIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/leads/': {
      id: '/_app/_auth/dashboard/_layout/leads/'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AppAuthDashboardLayoutLeadsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/pipelines/': {
      id: '/_app/_auth/dashboard/_layout/pipelines/'
      path: '/pipelines'
      fullPath: '/dashboard/pipelines'
      preLoaderRoute: typeof AppAuthDashboardLayoutPipelinesIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/products/': {
      id: '/_app/_auth/dashboard/_layout/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AppAuthDashboardLayoutProductsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/employees/$employeeId': {
      id: '/_app/_auth/dashboard/_layout/gabinet/employees/$employeeId'
      path: '/gabinet/employees/$employeeId'
      fullPath: '/dashboard/gabinet/employees/$employeeId'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetEmployeesEmployeeIdImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/patients/$patientId': {
      id: '/_app/_auth/dashboard/_layout/gabinet/patients/$patientId'
      path: '/gabinet/patients/$patientId'
      fullPath: '/dashboard/gabinet/patients/$patientId'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetPatientsPatientIdImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/settings/document-templates': {
      id: '/_app/_auth/dashboard/_layout/gabinet/settings/document-templates'
      path: '/gabinet/settings/document-templates'
      fullPath: '/dashboard/gabinet/settings/document-templates'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetSettingsDocumentTemplatesImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/settings/leave-balances': {
      id: '/_app/_auth/dashboard/_layout/gabinet/settings/leave-balances'
      path: '/gabinet/settings/leave-balances'
      fullPath: '/dashboard/gabinet/settings/leave-balances'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetSettingsLeaveBalancesImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/settings/leave-types': {
      id: '/_app/_auth/dashboard/_layout/gabinet/settings/leave-types'
      path: '/gabinet/settings/leave-types'
      fullPath: '/dashboard/gabinet/settings/leave-types'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetSettingsLeaveTypesImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/settings/leaves': {
      id: '/_app/_auth/dashboard/_layout/gabinet/settings/leaves'
      path: '/gabinet/settings/leaves'
      fullPath: '/dashboard/gabinet/settings/leaves'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetSettingsLeavesImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/settings/scheduling': {
      id: '/_app/_auth/dashboard/_layout/gabinet/settings/scheduling'
      path: '/gabinet/settings/scheduling'
      fullPath: '/dashboard/gabinet/settings/scheduling'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetSettingsSchedulingImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/calendar/': {
      id: '/_app/_auth/dashboard/_layout/gabinet/calendar/'
      path: '/gabinet/calendar'
      fullPath: '/dashboard/gabinet/calendar'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetCalendarIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/documents/': {
      id: '/_app/_auth/dashboard/_layout/gabinet/documents/'
      path: '/gabinet/documents'
      fullPath: '/dashboard/gabinet/documents'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetDocumentsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/employees/': {
      id: '/_app/_auth/dashboard/_layout/gabinet/employees/'
      path: '/gabinet/employees'
      fullPath: '/dashboard/gabinet/employees'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetEmployeesIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/packages/': {
      id: '/_app/_auth/dashboard/_layout/gabinet/packages/'
      path: '/gabinet/packages'
      fullPath: '/dashboard/gabinet/packages'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetPackagesIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/patients/': {
      id: '/_app/_auth/dashboard/_layout/gabinet/patients/'
      path: '/gabinet/patients'
      fullPath: '/dashboard/gabinet/patients'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetPatientsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/gabinet/treatments/': {
      id: '/_app/_auth/dashboard/_layout/gabinet/treatments/'
      path: '/gabinet/treatments'
      fullPath: '/dashboard/gabinet/treatments'
      preLoaderRoute: typeof AppAuthDashboardLayoutGabinetTreatmentsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AppRoute: AppRoute.addChildren({
    AppAuthRoute: AppAuthRoute.addChildren({
      AppAuthDashboardRoute: AppAuthDashboardRoute.addChildren({
        AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRoute.addChildren({
          AppAuthDashboardLayoutCheckoutRoute,
          AppAuthDashboardLayoutSettingsRoute:
            AppAuthDashboardLayoutSettingsRoute.addChildren({
              AppAuthDashboardLayoutSettingsActivityTypesRoute,
              AppAuthDashboardLayoutSettingsBillingRoute,
              AppAuthDashboardLayoutSettingsCustomFieldsRoute,
              AppAuthDashboardLayoutSettingsEmailRoute,
              AppAuthDashboardLayoutSettingsIntegrationsRoute,
              AppAuthDashboardLayoutSettingsLostReasonsRoute,
              AppAuthDashboardLayoutSettingsOrganizationRoute,
              AppAuthDashboardLayoutSettingsPermissionsRoute,
              AppAuthDashboardLayoutSettingsPipelinesRoute,
              AppAuthDashboardLayoutSettingsSourcesRoute,
              AppAuthDashboardLayoutSettingsTeamRoute,
              AppAuthDashboardLayoutSettingsIndexRoute,
            }),
          AppAuthDashboardLayoutIndexRoute,
          AppAuthDashboardLayoutCompaniesCompanyIdRoute,
          AppAuthDashboardLayoutCompaniesNewRoute,
          AppAuthDashboardLayoutContactsContactIdRoute,
          AppAuthDashboardLayoutContactsNewRoute,
          AppAuthDashboardLayoutDocumentsDocumentIdRoute,
          AppAuthDashboardLayoutDocumentsNewRoute,
          AppAuthDashboardLayoutGabinetReportsRoute,
          AppAuthDashboardLayoutLeadsLeadIdRoute,
          AppAuthDashboardLayoutLeadsNewRoute,
          AppAuthDashboardLayoutActivitiesIndexRoute,
          AppAuthDashboardLayoutCallsIndexRoute,
          AppAuthDashboardLayoutCompaniesIndexRoute,
          AppAuthDashboardLayoutContactsIndexRoute,
          AppAuthDashboardLayoutDocumentsIndexRoute,
          AppAuthDashboardLayoutGabinetIndexRoute,
          AppAuthDashboardLayoutInboxIndexRoute,
          AppAuthDashboardLayoutLeadsIndexRoute,
          AppAuthDashboardLayoutPipelinesIndexRoute,
          AppAuthDashboardLayoutProductsIndexRoute,
          AppAuthDashboardLayoutGabinetEmployeesEmployeeIdRoute,
          AppAuthDashboardLayoutGabinetPatientsPatientIdRoute,
          AppAuthDashboardLayoutGabinetSettingsDocumentTemplatesRoute,
          AppAuthDashboardLayoutGabinetSettingsLeaveBalancesRoute,
          AppAuthDashboardLayoutGabinetSettingsLeaveTypesRoute,
          AppAuthDashboardLayoutGabinetSettingsLeavesRoute,
          AppAuthDashboardLayoutGabinetSettingsSchedulingRoute,
          AppAuthDashboardLayoutGabinetCalendarIndexRoute,
          AppAuthDashboardLayoutGabinetDocumentsIndexRoute,
          AppAuthDashboardLayoutGabinetEmployeesIndexRoute,
          AppAuthDashboardLayoutGabinetPackagesIndexRoute,
          AppAuthDashboardLayoutGabinetPatientsIndexRoute,
          AppAuthDashboardLayoutGabinetTreatmentsIndexRoute,
        }),
      }),
      AppAuthOnboardingRoute: AppAuthOnboardingRoute.addChildren({
        AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRoute.addChildren({
          AppAuthOnboardingLayoutUsernameRoute,
        }),
      }),
    }),
    AppInviteTokenRoute,
    AppLoginRoute: AppLoginRoute.addChildren({
      AppLoginLayoutRoute: AppLoginLayoutRoute.addChildren({
        AppLoginLayoutIndexRoute,
      }),
    }),
    AppPatientRoute: AppPatientRoute.addChildren({
      AppPatientLayoutRoute: AppPatientLayoutRoute.addChildren({
        AppPatientLayoutAppointmentsRoute,
        AppPatientLayoutDocumentsRoute,
        AppPatientLayoutProfileRoute,
        AppPatientLayoutIndexRoute,
      }),
      AppPatientLoginRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_auth",
        "/_app/invite/$token",
        "/_app/login",
        "/_app/patient"
      ]
    },
    "/_app/_auth": {
      "filePath": "_app/_auth.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_auth/dashboard",
        "/_app/_auth/onboarding"
      ]
    },
    "/_app/invite/$token": {
      "filePath": "_app/invite.$token.tsx",
      "parent": "/_app"
    },
    "/_app/login": {
      "filePath": "_app/login",
      "parent": "/_app",
      "children": [
        "/_app/login/_layout"
      ]
    },
    "/_app/login/_layout": {
      "filePath": "_app/login/_layout.tsx",
      "parent": "/_app/login",
      "children": [
        "/_app/login/_layout/"
      ]
    },
    "/_app/patient": {
      "filePath": "_app/patient",
      "parent": "/_app",
      "children": [
        "/_app/patient/_layout",
        "/_app/patient/login"
      ]
    },
    "/_app/patient/_layout": {
      "filePath": "_app/patient/_layout.tsx",
      "parent": "/_app/patient",
      "children": [
        "/_app/patient/_layout/appointments",
        "/_app/patient/_layout/documents",
        "/_app/patient/_layout/profile",
        "/_app/patient/_layout/"
      ]
    },
    "/_app/patient/login": {
      "filePath": "_app/patient/login.tsx",
      "parent": "/_app/patient"
    },
    "/_app/_auth/dashboard": {
      "filePath": "_app/_auth/dashboard",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/dashboard/_layout"
      ]
    },
    "/_app/_auth/dashboard/_layout": {
      "filePath": "_app/_auth/dashboard/_layout.tsx",
      "parent": "/_app/_auth/dashboard",
      "children": [
        "/_app/_auth/dashboard/_layout/checkout",
        "/_app/_auth/dashboard/_layout/settings",
        "/_app/_auth/dashboard/_layout/",
        "/_app/_auth/dashboard/_layout/companies/$companyId",
        "/_app/_auth/dashboard/_layout/companies/new",
        "/_app/_auth/dashboard/_layout/contacts/$contactId",
        "/_app/_auth/dashboard/_layout/contacts/new",
        "/_app/_auth/dashboard/_layout/documents/$documentId",
        "/_app/_auth/dashboard/_layout/documents/new",
        "/_app/_auth/dashboard/_layout/gabinet/reports",
        "/_app/_auth/dashboard/_layout/leads/$leadId",
        "/_app/_auth/dashboard/_layout/leads/new",
        "/_app/_auth/dashboard/_layout/activities/",
        "/_app/_auth/dashboard/_layout/calls/",
        "/_app/_auth/dashboard/_layout/companies/",
        "/_app/_auth/dashboard/_layout/contacts/",
        "/_app/_auth/dashboard/_layout/documents/",
        "/_app/_auth/dashboard/_layout/gabinet/",
        "/_app/_auth/dashboard/_layout/inbox/",
        "/_app/_auth/dashboard/_layout/leads/",
        "/_app/_auth/dashboard/_layout/pipelines/",
        "/_app/_auth/dashboard/_layout/products/",
        "/_app/_auth/dashboard/_layout/gabinet/employees/$employeeId",
        "/_app/_auth/dashboard/_layout/gabinet/patients/$patientId",
        "/_app/_auth/dashboard/_layout/gabinet/settings/document-templates",
        "/_app/_auth/dashboard/_layout/gabinet/settings/leave-balances",
        "/_app/_auth/dashboard/_layout/gabinet/settings/leave-types",
        "/_app/_auth/dashboard/_layout/gabinet/settings/leaves",
        "/_app/_auth/dashboard/_layout/gabinet/settings/scheduling",
        "/_app/_auth/dashboard/_layout/gabinet/calendar/",
        "/_app/_auth/dashboard/_layout/gabinet/documents/",
        "/_app/_auth/dashboard/_layout/gabinet/employees/",
        "/_app/_auth/dashboard/_layout/gabinet/packages/",
        "/_app/_auth/dashboard/_layout/gabinet/patients/",
        "/_app/_auth/dashboard/_layout/gabinet/treatments/"
      ]
    },
    "/_app/_auth/onboarding": {
      "filePath": "_app/_auth/onboarding",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/onboarding/_layout"
      ]
    },
    "/_app/_auth/onboarding/_layout": {
      "filePath": "_app/_auth/onboarding/_layout.tsx",
      "parent": "/_app/_auth/onboarding",
      "children": [
        "/_app/_auth/onboarding/_layout/username"
      ]
    },
    "/_app/patient/_layout/appointments": {
      "filePath": "_app/patient/_layout.appointments.tsx",
      "parent": "/_app/patient/_layout"
    },
    "/_app/patient/_layout/documents": {
      "filePath": "_app/patient/_layout.documents.tsx",
      "parent": "/_app/patient/_layout"
    },
    "/_app/patient/_layout/profile": {
      "filePath": "_app/patient/_layout.profile.tsx",
      "parent": "/_app/patient/_layout"
    },
    "/_app/login/_layout/": {
      "filePath": "_app/login/_layout.index.tsx",
      "parent": "/_app/login/_layout"
    },
    "/_app/patient/_layout/": {
      "filePath": "_app/patient/_layout.index.tsx",
      "parent": "/_app/patient/_layout"
    },
    "/_app/_auth/dashboard/_layout/checkout": {
      "filePath": "_app/_auth/dashboard/_layout.checkout.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/settings": {
      "filePath": "_app/_auth/dashboard/_layout.settings.tsx",
      "parent": "/_app/_auth/dashboard/_layout",
      "children": [
        "/_app/_auth/dashboard/_layout/settings/activity-types",
        "/_app/_auth/dashboard/_layout/settings/billing",
        "/_app/_auth/dashboard/_layout/settings/custom-fields",
        "/_app/_auth/dashboard/_layout/settings/email",
        "/_app/_auth/dashboard/_layout/settings/integrations",
        "/_app/_auth/dashboard/_layout/settings/lost-reasons",
        "/_app/_auth/dashboard/_layout/settings/organization",
        "/_app/_auth/dashboard/_layout/settings/permissions",
        "/_app/_auth/dashboard/_layout/settings/pipelines",
        "/_app/_auth/dashboard/_layout/settings/sources",
        "/_app/_auth/dashboard/_layout/settings/team",
        "/_app/_auth/dashboard/_layout/settings/"
      ]
    },
    "/_app/_auth/onboarding/_layout/username": {
      "filePath": "_app/_auth/onboarding/_layout.username.tsx",
      "parent": "/_app/_auth/onboarding/_layout"
    },
    "/_app/_auth/dashboard/_layout/": {
      "filePath": "_app/_auth/dashboard/_layout.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/companies/$companyId": {
      "filePath": "_app/_auth/dashboard/_layout.companies.$companyId.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/companies/new": {
      "filePath": "_app/_auth/dashboard/_layout.companies.new.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/contacts/$contactId": {
      "filePath": "_app/_auth/dashboard/_layout.contacts.$contactId.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/contacts/new": {
      "filePath": "_app/_auth/dashboard/_layout.contacts.new.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/documents/$documentId": {
      "filePath": "_app/_auth/dashboard/_layout.documents.$documentId.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/documents/new": {
      "filePath": "_app/_auth/dashboard/_layout.documents.new.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/reports": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.reports.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/leads/$leadId": {
      "filePath": "_app/_auth/dashboard/_layout.leads.$leadId.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/leads/new": {
      "filePath": "_app/_auth/dashboard/_layout.leads.new.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/settings/activity-types": {
      "filePath": "_app/_auth/dashboard/_layout.settings.activity-types.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/billing": {
      "filePath": "_app/_auth/dashboard/_layout.settings.billing.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/custom-fields": {
      "filePath": "_app/_auth/dashboard/_layout.settings.custom-fields.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/email": {
      "filePath": "_app/_auth/dashboard/_layout.settings.email.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/integrations": {
      "filePath": "_app/_auth/dashboard/_layout.settings.integrations.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/lost-reasons": {
      "filePath": "_app/_auth/dashboard/_layout.settings.lost-reasons.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/organization": {
      "filePath": "_app/_auth/dashboard/_layout.settings.organization.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/permissions": {
      "filePath": "_app/_auth/dashboard/_layout.settings.permissions.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/pipelines": {
      "filePath": "_app/_auth/dashboard/_layout.settings.pipelines.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/sources": {
      "filePath": "_app/_auth/dashboard/_layout.settings.sources.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/team": {
      "filePath": "_app/_auth/dashboard/_layout.settings.team.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/activities/": {
      "filePath": "_app/_auth/dashboard/_layout.activities.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/calls/": {
      "filePath": "_app/_auth/dashboard/_layout.calls.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/companies/": {
      "filePath": "_app/_auth/dashboard/_layout.companies.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/contacts/": {
      "filePath": "_app/_auth/dashboard/_layout.contacts.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/documents/": {
      "filePath": "_app/_auth/dashboard/_layout.documents.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/inbox/": {
      "filePath": "_app/_auth/dashboard/_layout.inbox.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/leads/": {
      "filePath": "_app/_auth/dashboard/_layout.leads.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/pipelines/": {
      "filePath": "_app/_auth/dashboard/_layout.pipelines.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/products/": {
      "filePath": "_app/_auth/dashboard/_layout.products.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/settings/": {
      "filePath": "_app/_auth/dashboard/_layout.settings.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/gabinet/employees/$employeeId": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.employees.$employeeId.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/patients/$patientId": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.patients.$patientId.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/settings/document-templates": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.settings.document-templates.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/settings/leave-balances": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.settings.leave-balances.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/settings/leave-types": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.settings.leave-types.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/settings/leaves": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.settings.leaves.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/settings/scheduling": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.settings.scheduling.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/calendar/": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.calendar.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/documents/": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.documents.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/employees/": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.employees.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/packages/": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.packages.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/patients/": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.patients.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/gabinet/treatments/": {
      "filePath": "_app/_auth/dashboard/_layout.gabinet.treatments.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
