-- Migrate scope_entities column from TEXT to JSONB
-- Enables direct Postgres containment queries (scope_entities @> '{"patient":"..."}')
-- and a GIN index, eliminating in-memory JSON parse on the read path.
--
-- All existing rows either have NULL or a valid JSON string (set only by
-- autoGenerateDocuments.ts via JSON.stringify), so the ::jsonb cast is safe.

ALTER TABLE form_documents
  ALTER COLUMN scope_entities TYPE JSONB USING scope_entities::jsonb;

CREATE INDEX form_documents_scope_entities_gin_idx
  ON form_documents USING gin (scope_entities);
