-- Add generated_for_treatment_id to form_documents so every auto-generated
-- appointment document carries an explicit FK to the treatment that triggered
-- its creation. Previously this was only stored inside the JSONB scope_entities
-- column, making future migration to documentInstances error-prone.
--
-- Backfill strategy (two steps):
--   1. Use scope_entities->>'treatment' for rows that already carry it
--      (documents created after autoGenerateDocuments started populating the field).
--   2. For remaining appointment documents still NULL, join through the
--      gabinet_appointment_treatments join table. NOTE: the original version
--      referenced gabinet_appointments.treatment_id, but that scalar column was
--      dropped in 00076 when the multi-treatment model (00069) moved treatments
--      into the gabinet_appointment_treatments join table. Best-effort: pick the
--      first treatment linked to the appointment.
--
-- Idempotent (IF NOT EXISTS) so a re-run after the prior failing apply is safe.

ALTER TABLE form_documents
  ADD COLUMN IF NOT EXISTS generated_for_treatment_id TEXT REFERENCES gabinet_treatments(id);

-- Step 1: backfill from scope_entities where treatment key exists
UPDATE form_documents
SET    generated_for_treatment_id = scope_entities->>'treatment'
WHERE  scope_entities ? 'treatment'
  AND  generated_for_treatment_id IS NULL;

-- Step 2: backfill from the appointment's treatments (multi-treatment model).
UPDATE form_documents fd
SET    generated_for_treatment_id = gat.treatment_id
FROM   gabinet_appointment_treatments gat
WHERE  fd.entity_type               = 'appointment'
  AND  fd.entity_id                 = gat.appointment_id
  AND  fd.generated_for_treatment_id IS NULL;

CREATE INDEX IF NOT EXISTS form_documents_generated_for_treatment_id_idx
  ON form_documents (generated_for_treatment_id)
  WHERE generated_for_treatment_id IS NOT NULL;
