-- Add generated_for_treatment_id to form_documents so every auto-generated
-- appointment document carries an explicit FK to the treatment that triggered
-- its creation. Previously this was only stored inside the JSONB scope_entities
-- column, making future migration to documentInstances error-prone.
--
-- Backfill strategy (two steps):
--   1. Use scope_entities->>'treatment' for rows that already carry it
--      (documents created after autoGenerateDocuments started populating the field).
--   2. For remaining appointment documents with scope_entities IS NULL or without
--      the treatment key, join through gabinet_appointments.treatment_id.

ALTER TABLE form_documents
  ADD COLUMN generated_for_treatment_id TEXT REFERENCES gabinet_treatments(id);

-- Step 1: backfill from scope_entities where treatment key exists
UPDATE form_documents
SET    generated_for_treatment_id = scope_entities->>'treatment'
WHERE  scope_entities ? 'treatment'
  AND  generated_for_treatment_id IS NULL;

-- Step 2: backfill from appointment for rows still NULL
UPDATE form_documents fd
SET    generated_for_treatment_id = ga.treatment_id
FROM   gabinet_appointments ga
WHERE  fd.entity_type               = 'appointment'
  AND  fd.entity_id                 = ga.id
  AND  ga.treatment_id              IS NOT NULL
  AND  fd.generated_for_treatment_id IS NULL;

CREATE INDEX form_documents_generated_for_treatment_id_idx
  ON form_documents (generated_for_treatment_id)
  WHERE generated_for_treatment_id IS NOT NULL;
