import { useState, useCallback, useMemo, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { useAction } from "convex/react";
import { api } from "@cvx/_generated/api";
import type { Id } from "@cvx/_generated/dataModel";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Check,
  ClipboardList,
  FileSignature,
  Loader2,
  Send,
} from "@/lib/ez-icons";
import { cn } from "@/lib/utils";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { DocumentFormFiller } from "./document-form-filler";
import {
  extractFormFields,
  renderDocument,
} from "./document-renderer";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface AfterCompletionDocumentsDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  appointmentId: string;
  organizationId: Id<"organizations">;
}

interface FormDoc {
  _id: Id<"formDocuments">;
  title: string;
  status: string;
  templateId: Id<"formTemplates">;
  responseData: string;
  timing?: string;
  autoGenerated?: boolean;
}

interface FormTemplate {
  contentJson?: string;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function AfterCompletionDocumentsDialog({
  open,
  onOpenChange,
  appointmentId,
  organizationId,
}: AfterCompletionDocumentsDialogProps) {
  const { t } = useTranslation();
  const submitEmployeeFormFields = useAction(
    api.documents.documents.submitEmployeeFormFields,
  );

  // Fetch documents linked to this appointment (Supabase-primary action)
  const listDocumentsByEntity = useAction(api.documents.documents.listByEntity);
  const { data: documents, refetch } = useQuery({
    queryKey: ["documents.documents.listByEntity", organizationId, "appointment", appointmentId],
    queryFn: () =>
      listDocumentsByEntity({
        organizationId,
        entityType: "appointment",
        entityId: appointmentId,
      }),
    enabled: open && !!organizationId && !!appointmentId,
    refetchInterval: open ? 2000 : false, // Poll while open to catch new docs
  });

  const afterDocs = useMemo(() => {
    if (!documents) return [];
    return (documents as unknown as FormDoc[]).filter(
      (d) => d.timing === "after_completion" && d.autoGenerated,
    );
  }, [documents]);

  // Track which documents have been filled this session
  const [filledDocIds, setFilledDocIds] = useState<Set<string>>(new Set());
  const [activeDocId, setActiveDocId] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Reset state when dialog opens
  useEffect(() => {
    if (open) {
      setFilledDocIds(new Set());
      setActiveDocId(null);
    }
  }, [open]);

  // Auto-select first unfilled doc
  useEffect(() => {
    if (open && afterDocs.length > 0 && !activeDocId) {
      const first = afterDocs.find(
        (d) => d.status === "draft" && !filledDocIds.has(d._id),
      );
      if (first) setActiveDocId(first._id);
    }
  }, [open, afterDocs, activeDocId, filledDocIds]);

  const activeDoc = afterDocs.find((d) => d._id === activeDocId);

  // Fetch template for the active document (Supabase-primary action)
  const getTemplateById = useAction(api.documents.templates.getById);
  const { data: activeTemplateRaw } = useQuery({
    queryKey: ["documents.templates.getById", organizationId, activeDoc?.templateId],
    queryFn: () =>
      getTemplateById({
        organizationId,
        templateId: String(activeDoc?.templateId ?? ""),
      }),
    enabled: !!activeDoc?.templateId,
  });
  const activeTemplate = activeTemplateRaw as unknown as FormTemplate | undefined;

  // Parse scope data from the document's responseData
  const scopeData = useMemo(() => {
    if (!activeDoc) return {};
    try {
      const parsed = JSON.parse(activeDoc.responseData);
      // responseData is the flat scope map if no html yet
      if (!parsed.html) {
        const flat: Record<string, string> = {};
        for (const [k, v] of Object.entries(parsed)) {
          if (v != null) flat[k] = String(v);
        }
        return flat;
      }
      // If already has html + scopeData
      if (parsed.scopeData) {
        const flat: Record<string, string> = {};
        for (const [k, v] of Object.entries(
          parsed.scopeData as Record<string, unknown>,
        )) {
          if (v != null) flat[k] = String(v);
        }
        return flat;
      }
      return {};
    } catch {
      return {};
    }
  }, [activeDoc]);

  // Extract employee form fields from template
  const formFields = useMemo(() => {
    if (!activeTemplate?.contentJson) return [];
    try {
      const all = extractFormFields(JSON.parse(activeTemplate.contentJson));
      return all.filter((f) => f.filledBy === "employee");
    } catch {
      return [];
    }
  }, [activeTemplate?.contentJson]);

  // All form fields (for rendering the final HTML)
  const allFormFields = useMemo(() => {
    if (!activeTemplate?.contentJson) return [];
    try {
      return extractFormFields(JSON.parse(activeTemplate.contentJson));
    } catch {
      return [];
    }
  }, [activeTemplate?.contentJson]);

  const handleFormComplete = useCallback(
    async (fieldValues: Record<string, string>) => {
      if (!activeDoc || !activeTemplate) return;
      setSubmitting(true);
      try {
        // Render the document with scope data + employee field values
        const html = activeTemplate.contentJson
          ? renderDocument(activeTemplate.contentJson, scopeData, fieldValues)
          : `<div class="document"><h1>${activeDoc.title}</h1></div>`;

        await submitEmployeeFormFields({
          organizationId,
          documentId: activeDoc._id as Id<"formDocuments">,
          renderedHtml: html,
          formFieldValues: JSON.stringify(fieldValues),
          scopeData: JSON.stringify(scopeData),
        });

        toast.success(
          t(
            "documents.afterCompletion.filled",
            "Dokument wypelniony i wyslany do klienta do podpisu.",
          ),
        );

        setFilledDocIds((prev) => new Set(prev).add(activeDoc._id));

        // Move to next unfilled doc
        const next = afterDocs.find(
          (d) =>
            d._id !== activeDoc._id &&
            d.status === "draft" &&
            !filledDocIds.has(d._id),
        );
        setActiveDocId(next?._id ?? null);

        refetch();
      } catch (err) {
        const message =
          err instanceof Error ? err.message : t("common.error");
        toast.error(message);
      } finally {
        setSubmitting(false);
      }
    },
    [
      activeDoc,
      activeTemplate,
      scopeData,
      submitEmployeeFormFields,
      organizationId,
      t,
      afterDocs,
      filledDocIds,
      refetch,
    ],
  );

  // For documents without employee form fields: auto-submit with just rendered HTML
  const handleAutoSubmit = useCallback(async () => {
    if (!activeDoc || !activeTemplate) return;
    setSubmitting(true);
    try {
      // Render HTML from TipTap contentJson if available; otherwise use a minimal wrapper
      const html = activeTemplate.contentJson
        ? renderDocument(activeTemplate.contentJson, scopeData)
        : `<div class="document"><h1>${activeDoc.title}</h1></div>`;
      await submitEmployeeFormFields({
        organizationId,
        documentId: activeDoc._id as Id<"formDocuments">,
        renderedHtml: html,
        formFieldValues: JSON.stringify({}),
        scopeData: JSON.stringify(scopeData),
      });

      toast.success(
        t(
          "documents.afterCompletion.sent",
          "Dokument wyslany do klienta do podpisu.",
        ),
      );

      setFilledDocIds((prev) => new Set(prev).add(activeDoc._id));

      const next = afterDocs.find(
        (d) =>
          d._id !== activeDoc._id &&
          d.status === "draft" &&
          !filledDocIds.has(d._id),
      );
      setActiveDocId(next?._id ?? null);

      refetch();
    } catch (err) {
      const message = err instanceof Error ? err.message : t("common.error");
      toast.error(message);
    } finally {
      setSubmitting(false);
    }
  }, [
    activeDoc,
    activeTemplate,
    scopeData,
    submitEmployeeFormFields,
    organizationId,
    t,
    afterDocs,
    filledDocIds,
    refetch,
  ]);

  const totalDocs = afterDocs.length;
  const filledCount =
    filledDocIds.size +
    afterDocs.filter(
      (d) =>
        d.status !== "draft" && !filledDocIds.has(d._id),
    ).length;
  const allDone = totalDocs > 0 && filledCount >= totalDocs;

  if (totalDocs === 0 && open) {
    // No after_completion docs — auto-close
    return null;
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileSignature className="h-5 w-5" />
            {t(
              "documents.afterCompletion.title",
              "Dokumenty po wizycie",
            )}
          </DialogTitle>
          <DialogDescription>
            {allDone
              ? t(
                  "documents.afterCompletion.allDone",
                  "Wszystkie dokumenty zostaly wypelnione i wyslane do klienta.",
                )
              : t(
                  "documents.afterCompletion.description",
                  "Wypelnij poniższe dokumenty. Po wypelnieniu każdy zostanie automatycznie wyslany do klienta do podpisu.",
                )}
          </DialogDescription>
        </DialogHeader>

        {/* Document list with progress */}
        <div className="space-y-3">
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span>
              {filledCount}/{totalDocs}{" "}
              {t("documents.documentsCompleted", "dokumentow")}
            </span>
          </div>

          <div className="rounded-lg border divide-y">
            {afterDocs.map((doc) => {
              const isFilled =
                filledDocIds.has(doc._id) || doc.status !== "draft";
              const isActive = activeDocId === doc._id;
              return (
                <button
                  key={doc._id}
                  type="button"
                  onClick={() => !isFilled && setActiveDocId(doc._id)}
                  disabled={isFilled}
                  className={cn(
                    "w-full flex items-center justify-between gap-3 px-4 py-3 text-left transition-colors",
                    isActive && "bg-accent",
                    isFilled && "opacity-60",
                    !isFilled && !isActive && "hover:bg-accent/50 cursor-pointer",
                  )}
                >
                  <div className="flex items-center gap-3 min-w-0">
                    {isFilled ? (
                      <div className="flex h-5 w-5 items-center justify-center rounded-full bg-green-100 dark:bg-green-900/30">
                        <Check className="h-3 w-3 text-green-600 dark:text-green-400" />
                      </div>
                    ) : (
                      <ClipboardList className="h-5 w-5 text-muted-foreground shrink-0" />
                    )}
                    <span className="text-sm font-medium truncate">
                      {doc.title}
                    </span>
                  </div>
                  {isFilled ? (
                    <Badge
                      variant="outline"
                      className="text-[10px] text-green-700 border-green-300 dark:text-green-400 dark:border-green-700"
                    >
                      <Send className="h-3 w-3 mr-1" />
                      {t("documents.afterCompletion.sentBadge", "Wyslano")}
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="text-[10px]">
                      {t("documents.afterCompletion.pending", "Do wypelnienia")}
                    </Badge>
                  )}
                </button>
              );
            })}
          </div>
        </div>

        {/* Active document form */}
        {activeDoc && activeTemplate && !allDone && (
          <div className="space-y-3 pt-2 border-t">
            <h4 className="text-sm font-medium flex items-center gap-2">
              <ClipboardList className="h-4 w-4" />
              {activeDoc.title}
            </h4>

            {submitting && (
              <div className="flex items-center justify-center gap-2 py-8">
                <Loader2 className="h-5 w-5 animate-spin" />
                <span className="text-sm text-muted-foreground">
                  {t("common.saving", "Zapisywanie...")}
                </span>
              </div>
            )}

            {!submitting && formFields.length > 0 && (
              <DocumentFormFiller
                formFields={allFormFields}
                filledByFilter="employee"
                onComplete={handleFormComplete}
                onCancel={() => {
                  // Skip this document — employee can fill later
                  const next = afterDocs.find(
                    (d) =>
                      d._id !== activeDoc._id &&
                      d.status === "draft" &&
                      !filledDocIds.has(d._id),
                  );
                  setActiveDocId(next?._id ?? null);
                }}
              />
            )}

            {!submitting && formFields.length === 0 && (
              <div className="space-y-3">
                <p className="text-sm text-muted-foreground">
                  {t(
                    "documents.afterCompletion.noEmployeeFields",
                    "Ten dokument nie wymaga wypelnienia pol przez pracownika. Kliknij przycisk ponizej aby wyslac go do klienta do podpisu.",
                  )}
                </p>
                <Button onClick={handleAutoSubmit}>
                  <Send className="h-4 w-4 mr-2" />
                  {t(
                    "documents.afterCompletion.sendToClient",
                    "Wyslij do klienta",
                  )}
                </Button>
              </div>
            )}
          </div>
        )}

        {/* All done state */}
        {allDone && (
          <div className="flex flex-col items-center gap-3 py-4">
            <div className="rounded-full bg-green-100 p-3 dark:bg-green-900/30">
              <Check className="h-8 w-8 text-green-600 dark:text-green-400" />
            </div>
            <p className="text-sm text-muted-foreground text-center">
              {t(
                "documents.afterCompletion.allSent",
                "Wszystkie dokumenty zostaly wyslane do klienta.",
              )}
            </p>
          </div>
        )}

        <DialogFooter>
          <Button
            variant={allDone ? "default" : "outline"}
            onClick={() => onOpenChange(false)}
          >
            {allDone
              ? t("common.close", "Zamknij")
              : t("documents.afterCompletion.later", "Wypelnie pozniej")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
